== Marlowe 3.0 tutorials

This document gives an overview of a set of Marlowe tutorials.


[start=2]
. xref:introducing-marlowe#introducing-marlowe[leveloffset=+ 1] Introducing Marlowe
This tutorial gives an overview of the ideas behind Marlowe, as a
domain-specific language embedded in Haskell. It also introduces
commitments and timeouts, which are central to how Marlowe works in a
blockchain context.
. xref:escrow-ex#escrow-ex[] A first example: the escrow contract
This tutorial introduces a simple financial contract in pseudocode,
before explaining how it is modified to work in Marlowe, giving the
first example of a Marlowe contract.
. xref:marlowe-model#marlowe-model[] The Marlowe Model
In this tutorial we look at our general approach to modelling contracts in Marlowe, and the context in which Marlowe contracts are executed: the Cardano blockchain. In doing this we also introduce some of the standard terminology that we will use in describing Marlowe.
. xref:marlowe-step-by-step#marlowe-step-by-step[] Marlowe step by step
This tutorial explains the five ways of building contracts in Marlowe. Four of these – `Pay`, `Let`, `If` and `When` – build a complex contract from simpler contracts, and the fifth, `Refund`, is a simple contract. 
In explaining these contracts we will also explain Marlowe _values_, _observations_ and _actions_, which are used to supply external information and inputs to a running contract to control how it will evolve.
. xref:marlowe-data#marlowe-data[] The Marlowe data types
This tutorial formally introduces Marlowe as a Haskell data type, as well as presenting 
the different types used by the model, and discussing a
number of assumptions about the infrastructure in which contracts will
be run.
. xref:embedded-marlowe#embedded-marlowe[] Embedded Marlowe 
This tutorial shows how to use some simple features of Haskell to write
Marlowe contracts that are more readable, maintainable and reusable, by
revisiting the escrow contract.
. xref:using-marlowe#using-marlowe[] Using Marlowe
This tutorial shows you how to use Marlowe from within Haskell, and in
particular shows how to exercise a contract using the semantics given earlier.
. xref:playground-overview#playground-overview[] The Marlowe Playground
This tutorial introduces the Marlowe Playground, an online tool for
creating embedded Marlowe contracts and interactively stepping through
their execution.
. xref:actus-marlowe#actus-marlowe[] ACTUS and Marlowe 
This tutorial gives an introduction to the general idea of the ACTUS
taxonomy, plus examples implemented in Marlowe.

// . xref:escrow-step-by-step#escrow-step-by-step[] Escrow step by step NOT YET UPDATED
// On this tutorial we build the escrow contract step by step. From a single contract with a single actor (Alice) to multiple actors (Alice,Bob,Carol) and multiple interactions. /This was the script for the example in the udemy class/.

//// 
. xref:marlowe-semantics#marlowe-semantics[] Understanding the semantics IGNORE THIS

This tutorial gives an introduction to the formal semantics of Marlowe
by presenting an overview of the key Haskell definitions that interpret
inputs and transactions, as well as fitting those into a schematic
overview of how the components of the semantics work together.
////

//// 
. xref:marlowe-plutus#marlowe-plutus[] Implementing Marlowe in Plutus NOT YET UPDATED

So far these tutorials have dealt with Marlowe as a “stand alone”
artefact; this tutorial describes how Marlowe is implemented on
blockchain, using the “mockchain” that provides a high-fidelity
simulation of the Cardano SL layer.
////
____
These tutorials address the current version of
Marlowe, 3.0, which is implemented in the _Marlowe Playground_, and
available {marloweplayground}[here].

The version covered in the ISoLA paper, and supported in the original
version of Meadow, is tagged as *v1.3* and is
available https://github.com/input-output-hk/marlowe/tree/v1.3[here].
____
