
== Marlowe tutorials

This document gives an overview of a set of Marlowe tutorials.


[start=2]
. xref:introducing-marlowe#introducing-marlowe[leveloffset=+ 1]
This tutorial gives an overview of the ideas behind Marlowe, as a
domain-specific language embedded in Haskell. It also introduces
commitments and timeouts, which are central to how Marlowe works in a
blockchain context.
. xref:escrow-ex#escrow-ex[]
This tutorial introduces a simple financial contract in pseudocode,
before explaining how it is modified to work in Marlowe, giving the
first example of a Marlowe contract.
. xref:marlowe-model#marlowe-model[]
In this tutorial we look at our general approach to modelling contracts in Marlowe, and the context in which Marlowe contracts are executed: the Cardano blockchain. In doing this we also introduce some of the standard terminology that we will use in describing Marlowe.
. xref:marlowe-step-by-step#marlowe-step-by-step[]
This tutorial explains the five ways of building contracts in Marlowe. Four of these – `Pay`, `Let`, `If` and `When` – build a complex contract from simpler contracts, and the fifth, `Close`, is a simple contract. 
In explaining these contracts we will also explain Marlowe _values_, _observations_ and _actions_, which are used to supply external information and inputs to a running contract to control how it will evolve.
. xref:playground-blockly#playground-blockly[]
This section shows how Marlowe contracts are built using the Blockly visual programming environment.
. xref:marlowe-data#marlowe-data[]
This tutorial formally introduces Marlowe as a Haskell data type, as well as presenting 
the different types used by the model, and discussing a
number of assumptions about the infrastructure in which contracts will
be run.
. xref:embedded-marlowe#embedded-marlowe[]
This tutorial shows how to use some simple features of Haskell to write
Marlowe contracts that are more readable, maintainable and reusable, illustrated by
revisiting the escrow contract.
. xref:javascript-embedding#javascript-embedding[]
Marlowe is also embedded in JavaScript, and here we show how Marlowe contracts can be created and edited in JavaScript.
. xref:playground-overview#playground-overview[]
This tutorial introduces the Marlowe Playground, an online tool for
creating embedded Marlowe contracts and interactively stepping through
their execution.
. xref:potential-problems-with-contracts#potential-problems-with-contracts[]
This tutorial reviews how not to write Marlowe contracts, and what can
go wrong when executing contracts even if they have been written correctly.
. xref:static-analysis#static-analysis[]
Marlowe contracts can be analysed without running them, and so, for instance, we 
can verify that a contract will always make the payments that it is required to, irrespective
of the inputs that it receives. This tutorial explains this, and how to run an analysis in the playground.
. xref:actus-marlowe#actus-marlowe[]
This tutorial gives an introduction to the general idea of the ACTUS
taxonomy, plus examples implemented in Marlowe.
. xref:actus-labs#actus-labs[]
The Actus Labs support generation of different styles of Actus contract from the parameters that describe the particular contract instance.
. xref:wallets-simulation#wallets-simulation[]
The wallets simulation present a view of a running contract from the perspective of a participant in that contract, rather than the ‘omniscient‘ view given in the simulation tab.
. xref:using-marlowe#using-marlowe[]
This tutorial shows you how to use Marlowe from the command line in ghci, and in
particular shows how to exercise a contract using the semantics given earlier.
. xref:migrating#migrating[]
Here we explain how the current version of Marlowe is related to earlier versions.
// . xref:escrow-step-by-step#escrow-step-by-step[] Escrow step by step NOT YET UPDATED
// On this tutorial we build the escrow contract step by step. From a single contract with a single actor (Alice) to multiple actors (Alice,Bob,Carol) and multiple interactions. /This was the script for the example in the udemy class/.

//// 
. xref:marlowe-semantics#marlowe-semantics[] Understanding the semantics IGNORE THIS

This tutorial gives an introduction to the formal semantics of Marlowe
by presenting an overview of the key Haskell definitions that interpret
inputs and transactions, as well as fitting those into a schematic
overview of how the components of the semantics work together.
////

//// 
. xref:marlowe-plutus#marlowe-plutus[] Implementing Marlowe in Plutus NOT YET UPDATED

So far these tutorials have dealt with Marlowe as a “stand alone”
artefact; this tutorial describes how Marlowe is implemented on
blockchain, using the “mockchain” that provides a high-fidelity
simulation of the Cardano SL layer.
////
____
These tutorials address the current version of
Marlowe, which is implemented in the _Marlowe Playground_, and
available {marloweplayground}[here].

The version covered in the ISoLA paper, and supported in the original
version of the Playground (called Meadow), is tagged as *v1.3* and is
available https://github.com/input-output-hk/marlowe/tree/v1.3[here].
____
