# This file was generated by Psc-Package2Nix
# You will not want to edit this file.
# To change the contents of this file, first fork Psc-Package2Nix
# And edit the $file_template

{ pkgs ? import <nixpkgs> {} }:

let
  inputs = {

    "ace" = pkgs.stdenv.mkDerivation {
      name = "ace";
      version = "v7.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-ace.git";
        rev = "v7.0.0";
        sha256 = "1fwr4gdj4fcrrqnqf1h2553zxhcfgss3s32snma9hmz34iswjh2p";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "ace-halogen" = pkgs.stdenv.mkDerivation {
      name = "ace-halogen";
      version = "purs012";
      src = pkgs.fetchgit {
        url = "https://github.com/shmish111/purescript-ace-halogen.git";
        rev = "purs012";
        sha256 = "1nqx1i0im0vqjxkmyz0ylkqnw1xl57svznvy5xw7lrzv31ha2rnn";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "aff" = pkgs.stdenv.mkDerivation {
      name = "aff";
      version = "v5.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-aff.git";
        rev = "v5.1.1";
        sha256 = "19v5psd6jz13gr5yqyx8286b5bpfq1dax51w906y0mqgnfz92yzr";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "affjax" = pkgs.stdenv.mkDerivation {
      name = "affjax";
      version = "v9.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-affjax.git";
        rev = "v9.0.0";
        sha256 = "04xij3q4802z58mzaaz661ifv1rd673fq2mjqj553dw326zplpvs";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "argonaut-core" = pkgs.stdenv.mkDerivation {
      name = "argonaut-core";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-argonaut-core.git";
        rev = "v5.0.0";
        sha256 = "1d3jgyap3vwc7mc01ji6brmd2n8lr9mmgx0fl88yalrm2j89jrcc";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "arraybuffer-types" = pkgs.stdenv.mkDerivation {
      name = "arraybuffer-types";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-arraybuffer-types.git";
        rev = "v2.0.0";
        sha256 = "059a8n49yhl46l1b1j2qj4ichzq6dzj29ajkfvw88npzj5w2rshy";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "arrays" = pkgs.stdenv.mkDerivation {
      name = "arrays";
      version = "v5.2.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-arrays.git";
        rev = "v5.2.1";
        sha256 = "1gzsgxc1fjx4kfqfkxamqz4qnmbhxkay0n3fvy0mwmfklp1q8703";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "avar" = pkgs.stdenv.mkDerivation {
      name = "avar";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-avar.git";
        rev = "v3.0.0";
        sha256 = "14g05jm2xricy5b9vn4k4lhc9lzi5jvpvv85h10s17kn4wwi9igk";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "bifunctors" = pkgs.stdenv.mkDerivation {
      name = "bifunctors";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-bifunctors.git";
        rev = "v4.0.0";
        sha256 = "1bdra5fbkraglqrrm484vw8h0wwk48kzkn586v4y7fg106q1q386";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "bigints" = pkgs.stdenv.mkDerivation {
      name = "bigints";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-bigints.git";
        rev = "v4.0.0";
        sha256 = "1m9v4an4y55rhiknr2spyllf80chl61w2xzmg90p58f8q4mzih8r";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "catenable-lists" = pkgs.stdenv.mkDerivation {
      name = "catenable-lists";
      version = "v5.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-catenable-lists.git";
        rev = "v5.0.1";
        sha256 = "0mbpb8xr9a7a4bvawhki7js5cbv7c0lv0vdwb6r8nmv6b61gzg27";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "console" = pkgs.stdenv.mkDerivation {
      name = "console";
      version = "v4.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-console.git";
        rev = "v4.2.0";
        sha256 = "1b2nykdq1dzaqyra5pi8cvvz4dsbbkg57a2c88yi931ynm19nnw6";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "const" = pkgs.stdenv.mkDerivation {
      name = "const";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-const.git";
        rev = "v4.1.0";
        sha256 = "0qbd2aisax52yw6sybdhs7na943cbsd6mylhhgsamrf7hzh6v51p";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "contravariant" = pkgs.stdenv.mkDerivation {
      name = "contravariant";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-contravariant.git";
        rev = "v4.0.0";
        sha256 = "0vvcgfclx236kg4y76nwih787wyqacq8mmx42q64xzl964yrwxkk";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "control" = pkgs.stdenv.mkDerivation {
      name = "control";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-control.git";
        rev = "v4.1.0";
        sha256 = "10703zvsnjm5fc74k6wzjsvpsfyc3jci3jxhm7rxf7ymya9z1z53";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "coroutines" = pkgs.stdenv.mkDerivation {
      name = "coroutines";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-coroutines.git";
        rev = "v5.0.0";
        sha256 = "1jax7by8kn9fjg00avhziy3n18i3510iwzs3d73ziplanbw4qw4k";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "datetime" = pkgs.stdenv.mkDerivation {
      name = "datetime";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-datetime.git";
        rev = "v4.1.1";
        sha256 = "06ghfvbvd5sd0q014qi8j8glk2g2j9f8z8cwq2318kllp92gz07q";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "debug" = pkgs.stdenv.mkDerivation {
      name = "debug";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/garyb/purescript-debug.git";
        rev = "v4.0.0";
        sha256 = "0gwjj80akys0h111i74n429fmny992gx0r4rk1n98gqlqm5cmi21";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "distributive" = pkgs.stdenv.mkDerivation {
      name = "distributive";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-distributive.git";
        rev = "v4.0.0";
        sha256 = "0zbn0yq1vv7fbbf1lncg80irz0vg7wnw9b9wrzxhdzpbkw4jinsl";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "dom-indexed" = pkgs.stdenv.mkDerivation {
      name = "dom-indexed";
      version = "v7.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-dom-indexed.git";
        rev = "v7.0.0";
        sha256 = "18is75gsiix9w3f3lkly15cvs7ma1qc13hhi6wkl8nsj2g9g55ld";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "effect" = pkgs.stdenv.mkDerivation {
      name = "effect";
      version = "v2.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-effect.git";
        rev = "v2.0.1";
        sha256 = "1vqw5wrdxzh1ww6z7271xr4kg4mx0r3k3mwg18dmgmzj11wbn2wh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "either" = pkgs.stdenv.mkDerivation {
      name = "either";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-either.git";
        rev = "v4.1.1";
        sha256 = "12j7vvjly0bgxidxmb2pflx0zy7x425dnvxk2y1pm66n0hbsq7ns";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "enums" = pkgs.stdenv.mkDerivation {
      name = "enums";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-enums.git";
        rev = "v4.0.1";
        sha256 = "0qq0pgmq497nfml0y8xb2qdpga5xqp9sqq4ilv1rpyhg1v7nzb6v";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "exceptions" = pkgs.stdenv.mkDerivation {
      name = "exceptions";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exceptions.git";
        rev = "v4.0.0";
        sha256 = "17s0rg9k4phivhx9j3l2vqqfdhk61gpj1xfqy8w6zj3rnxj0b2cv";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "exists" = pkgs.stdenv.mkDerivation {
      name = "exists";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exists.git";
        rev = "v4.0.0";
        sha256 = "0bbdbw3jaqyi8dj2d52zvfgx4vl84d8cr6hp43vy8lfjfcbj0wlk";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "fixed-points" = pkgs.stdenv.mkDerivation {
      name = "fixed-points";
      version = "v5.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-fixed-points.git";
        rev = "v5.1.0";
        sha256 = "14acfi7897z2vd8mq52h0gz8x31wyrvalb490rqjf4nyk73vhg36";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
      name = "foldable-traversable";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foldable-traversable.git";
        rev = "v4.1.1";
        sha256 = "03x89xcmphckzjlp4chc7swrpw347ll5bvr2yp7x9v2jqw2jlyi1";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "foreign" = pkgs.stdenv.mkDerivation {
      name = "foreign";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign.git";
        rev = "v5.0.0";
        sha256 = "15mz2s4f8crkd721z4df2aag4s0wil6fs07cpcmi7dpnkn7a4nab";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "foreign-generic" = pkgs.stdenv.mkDerivation {
      name = "foreign-generic";
      version = "purs012";
      src = pkgs.fetchgit {
        url = "https://github.com/shmish111/purescript-foreign-generic.git";
        rev = "purs012";
        sha256 = "09v7sxcryl682369y5harc56jini5pgsch20bqa57ns87migmg25";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "foreign-object" = pkgs.stdenv.mkDerivation {
      name = "foreign-object";
      version = "v2.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign-object.git";
        rev = "v2.0.1";
        sha256 = "0dhxwkd4lkwwjlcsfc7dabsw96xrs5lq7qyjw9cf9jgq9yhhirp8";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "fork" = pkgs.stdenv.mkDerivation {
      name = "fork";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-fork.git";
        rev = "v4.0.0";
        sha256 = "1jygqzyci40c28gw2ygnx8v52hilhajj1bdpn7ndvss4i7yh1lcp";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "form-urlencoded" = pkgs.stdenv.mkDerivation {
      name = "form-urlencoded";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-form-urlencoded.git";
        rev = "v4.0.1";
        sha256 = "14nb7mslmbms4wn4j6a7nrz8xmnach3qgcf8i1hgql1c8j7zkqz8";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "free" = pkgs.stdenv.mkDerivation {
      name = "free";
      version = "v5.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-free.git";
        rev = "v5.2.0";
        sha256 = "1bwj0ay7q9lm4ir29jy549m05jvaqik1s615biv23y51ngx3fn49";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "freeap" = pkgs.stdenv.mkDerivation {
      name = "freeap";
      version = "v5.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/ethul/purescript-freeap.git";
        rev = "v5.0.1";
        sha256 = "007840vpxa4gz0fvjbahyky2xzz625gzfaiy2wjpb50d9qacsr7y";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "freet" = pkgs.stdenv.mkDerivation {
      name = "freet";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-freet.git";
        rev = "v4.0.0";
        sha256 = "1kpgggwimxjvdvhn6s7z4lzg3yw1rqg5f7pyamx9gh232s4va40i";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "functions" = pkgs.stdenv.mkDerivation {
      name = "functions";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functions.git";
        rev = "v4.0.0";
        sha256 = "0675k5kxxwdvsjs6a3is8pwm3hmv0vbcza1b8ls10gymmfz3k3hj";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "functors" = pkgs.stdenv.mkDerivation {
      name = "functors";
      version = "v3.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functors.git";
        rev = "v3.1.1";
        sha256 = "1cnn3zhk6qcyiwbbpvrdqgsbch4qihx2y9d6sv45bvd8kzrbd306";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "gen" = pkgs.stdenv.mkDerivation {
      name = "gen";
      version = "v2.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-gen.git";
        rev = "v2.1.0";
        sha256 = "0ddsfb6a23rahkw9d3ymp2sf6d6vxndj73y61cdv74zrlr2nx74p";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "generics-rep" = pkgs.stdenv.mkDerivation {
      name = "generics-rep";
      version = "v6.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-generics-rep.git";
        rev = "v6.1.1";
        sha256 = "15vchzbcvf6byks90q14lvcwb8hnxqzm2mrlxi7v1f7has4s74kn";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "globals" = pkgs.stdenv.mkDerivation {
      name = "globals";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-globals.git";
        rev = "v4.0.0";
        sha256 = "150mc0kv0cb5fkx0szicwczjr54bglmlyaynj2grf1r4gnjg967s";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "halogen" = pkgs.stdenv.mkDerivation {
      name = "halogen";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-halogen.git";
        rev = "v4.0.0";
        sha256 = "13q1fj33wmqa8bhxp0k6cc7v218b0xnx8rnh4p3ci637x3via3bh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "halogen-vdom" = pkgs.stdenv.mkDerivation {
      name = "halogen-vdom";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-halogen-vdom.git";
        rev = "v3.0.0";
        sha256 = "0zs82fymvg1w2ifkj3h3hnq2cpa88lzkbl3i35rp1fccn5f70bpi";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "http-methods" = pkgs.stdenv.mkDerivation {
      name = "http-methods";
      version = "v4.0.2";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-http-methods.git";
        rev = "v4.0.2";
        sha256 = "1wfgrlnl33bcqw54hbc8icah2fi0rvi5zxhz07665vy9p5ppvkqs";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "identity" = pkgs.stdenv.mkDerivation {
      name = "identity";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-identity.git";
        rev = "v4.1.0";
        sha256 = "1scdgbfkphfmapw7p9rnsiynpmqzyvnal2glzj450q51f8g1dhld";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "integers" = pkgs.stdenv.mkDerivation {
      name = "integers";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-integers.git";
        rev = "v4.0.0";
        sha256 = "17d4bfpnrmbxlc7hhhrvnli70ydaqyr26zgvc9q52a76zgdcb4cf";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "invariant" = pkgs.stdenv.mkDerivation {
      name = "invariant";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-invariant.git";
        rev = "v4.1.0";
        sha256 = "1fimpbh3yb7clvqxcdf4yf9im64z0v2s9pbspfacgq5b4vshjas9";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "js-date" = pkgs.stdenv.mkDerivation {
      name = "js-date";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-date.git";
        rev = "v6.0.0";
        sha256 = "19qyzbr4a1ca8znbd8gcbz0a801f5p1v238ky3408gdx4ba32zjd";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "js-timers" = pkgs.stdenv.mkDerivation {
      name = "js-timers";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-timers.git";
        rev = "v4.0.1";
        sha256 = "1a8092sli7zqw1wflibhjza1ww21dxl7x7r602iazzwh2g70v4dg";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "lazy" = pkgs.stdenv.mkDerivation {
      name = "lazy";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lazy.git";
        rev = "v4.0.0";
        sha256 = "156q89l4nvvn14imbhp6xvvm82q7kqh1pyndmldmnkhiqyr84vqv";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "lcg" = pkgs.stdenv.mkDerivation {
      name = "lcg";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lcg.git";
        rev = "v2.0.0";
        sha256 = "1851cq2g84jzjbvbmncbivbhaqzj9zv5ni3gs14k04nmx2brxmvj";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "lists" = pkgs.stdenv.mkDerivation {
      name = "lists";
      version = "v5.4.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lists.git";
        rev = "v5.4.0";
        sha256 = "044qr0812wh6a5vz2snm5rrpav3jnykp75acri56qxih1gd3rqla";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "math" = pkgs.stdenv.mkDerivation {
      name = "math";
      version = "v2.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-math.git";
        rev = "v2.1.1";
        sha256 = "1msmy9w7y6fij62sdc55w68gpwkhm6lhgc8qjisjk4sxx1wdg1rr";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "matryoshka" = pkgs.stdenv.mkDerivation {
      name = "matryoshka";
      version = "v0.4.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-matryoshka.git";
        rev = "v0.4.0";
        sha256 = "1vm8papnpkmf4w51v6a2cnq408ayi75nz5b5zwiwksd35c8x2g64";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "maybe" = pkgs.stdenv.mkDerivation {
      name = "maybe";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-maybe.git";
        rev = "v4.0.1";
        sha256 = "073wa0d51daxdwacfcxg5pf6ch63n4ii55xm1ih87bxrg8mp52mx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "media-types" = pkgs.stdenv.mkDerivation {
      name = "media-types";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-media-types.git";
        rev = "v4.0.1";
        sha256 = "0ykwmxrhmwfy6c5mxjxa43xdf5xqakrqyvr5fn986yad50gjqj75";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "newtype" = pkgs.stdenv.mkDerivation {
      name = "newtype";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-newtype.git";
        rev = "v3.0.0";
        sha256 = "0qvk9p41miy806b05b4ikbr3if0fcyc35gfrwd2mflcxxp46011c";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-buffer" = pkgs.stdenv.mkDerivation {
      name = "node-buffer";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-buffer.git";
        rev = "v5.0.0";
        sha256 = "0ih2y29srdxgn526fw2v1y95hpivjil44vkl93w6nrqsymki36y0";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-fs" = pkgs.stdenv.mkDerivation {
      name = "node-fs";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-fs.git";
        rev = "v5.0.0";
        sha256 = "1hkg8j4zkyq71g2bn3vpfqb8x49rdd9k0ayv3zf6l8k80gp3qigx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-path" = pkgs.stdenv.mkDerivation {
      name = "node-path";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-path.git";
        rev = "v3.0.0";
        sha256 = "0j1ni52m62dpcrfakl1ik131i31bkg91yv0p1c40sdw0f59fzf6x";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "node-streams" = pkgs.stdenv.mkDerivation {
      name = "node-streams";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-node/purescript-node-streams.git";
        rev = "v4.0.0";
        sha256 = "098wdq0rj4nkc470fwmiaars7vxac9n1dh4d82jrji3m77n473da";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "nonempty" = pkgs.stdenv.mkDerivation {
      name = "nonempty";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-nonempty.git";
        rev = "v5.0.0";
        sha256 = "1vz174sg32cqrp52nwb2vz9frrzmdwzzlgl4vc2cm5wlf2anirxj";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "now" = pkgs.stdenv.mkDerivation {
      name = "now";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-now.git";
        rev = "v4.0.0";
        sha256 = "18h5pif2dy4r7w1xg2zw4mvdqlar9xqp3rawkiavmsc946ncf3zs";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "nullable" = pkgs.stdenv.mkDerivation {
      name = "nullable";
      version = "v4.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-nullable.git";
        rev = "v4.1.1";
        sha256 = "14qaxxga8gqlr4pijyvqycdyhjr6qpz3h4aarficw5j75b7x8nyv";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "numerics" = pkgs.stdenv.mkDerivation {
      name = "numerics";
      version = "v0.1.2";
      src = pkgs.fetchgit {
        url = "https://github.com/Proclivis/purescript-numerics";
        rev = "v0.1.2";
        sha256 = "1l1kxd87mlpwyxskfcnj01zxsrva35v10vc2rapqp8yg1n0rgwcr";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "ordered-collections" = pkgs.stdenv.mkDerivation {
      name = "ordered-collections";
      version = "v1.6.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-ordered-collections.git";
        rev = "v1.6.0";
        sha256 = "1drifyf25g8nclzmq40npm25av8slrr4l4lvlz9f0j07r893ir61";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "orders" = pkgs.stdenv.mkDerivation {
      name = "orders";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-orders.git";
        rev = "v4.0.0";
        sha256 = "13p1sm4dxkmxhld9x5qqg62iiajjb3qpzs66c1r24y5fs4zsfry4";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "parallel" = pkgs.stdenv.mkDerivation {
      name = "parallel";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-parallel.git";
        rev = "v4.0.0";
        sha256 = "1d5bnagabw2k8yxywkygwrpblb2ggqh2fhpqfrx2sj1y53x332hg";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "parsing" = pkgs.stdenv.mkDerivation {
      name = "parsing";
      version = "v5.0.2";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-parsing.git";
        rev = "v5.0.2";
        sha256 = "018bnplzjx5mndjqy6is16546fk91zacj8gky4i8q2v4naan4d1l";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "partial" = pkgs.stdenv.mkDerivation {
      name = "partial";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-partial.git";
        rev = "v2.0.0";
        sha256 = "0nw5989ydin2d12b97ch4pdynxkq91xpj7yym5gpd5fpbgy36mdi";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "prelude" = pkgs.stdenv.mkDerivation {
      name = "prelude";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-prelude.git";
        rev = "v4.1.0";
        sha256 = "1pwqhsba4xyywfflma5rfqzqac1vmybwq7p3wkm4wsackvbn34h5";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "profunctor" = pkgs.stdenv.mkDerivation {
      name = "profunctor";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-profunctor.git";
        rev = "v4.0.0";
        sha256 = "1v4kvmhmiwznd4lswp9339h64pgv5zvd3vm1q7gzj70767a3941i";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "profunctor-lenses" = pkgs.stdenv.mkDerivation {
      name = "profunctor-lenses";
      version = "v6.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-profunctor-lenses.git";
        rev = "v6.2.0";
        sha256 = "0bb8ib00in8d65kvympdlfncb7bp1qqsjvvpw9zfwiwf67ix4v57";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "proxy" = pkgs.stdenv.mkDerivation {
      name = "proxy";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-proxy.git";
        rev = "v3.0.0";
        sha256 = "0rqf25b1n9p5sgx7gdsxwrfv9rb3sqxgqmqpp5kdm30lfk7snz24";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "psci-support" = pkgs.stdenv.mkDerivation {
      name = "psci-support";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-psci-support.git";
        rev = "v4.0.0";
        sha256 = "0jd773zcklr6hjddqingzmk20a0afpm2r9pczfjbj0d93pbxb4xh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "quickcheck" = pkgs.stdenv.mkDerivation {
      name = "quickcheck";
      version = "v6.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-quickcheck.git";
        rev = "v6.1.0";
        sha256 = "0b6208067krf81kzq2hbxs68386hcicbscwxbj5nck07ivjjvqh0";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "random" = pkgs.stdenv.mkDerivation {
      name = "random";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-random.git";
        rev = "v4.0.0";
        sha256 = "0k37v7z529adx6ypxj0xjyfrz45qia6p0vki2wpvi8lik7c698gf";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "rationals" = pkgs.stdenv.mkDerivation {
      name = "rationals";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/anttih/purescript-rationals.git";
        rev = "v5.0.0";
        sha256 = "1idvjvvx5kwmi8kj2ps95bcvlsgij1xgin4jfw3rmcqd930wqq6q";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "record" = pkgs.stdenv.mkDerivation {
      name = "record";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-record.git";
        rev = "v2.0.0";
        sha256 = "1hf6y3bjz3hs16xr50a0pj6p4akw11nw7gpn74vjisjrpga3r1gz";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "refs" = pkgs.stdenv.mkDerivation {
      name = "refs";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-refs.git";
        rev = "v4.1.0";
        sha256 = "08161iy1xbafzblv033v84156azpcqkiw9v9d6gliphrq5fm17gm";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "remotedata" = pkgs.stdenv.mkDerivation {
      name = "remotedata";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/krisajenkins/purescript-remotedata.git";
        rev = "v4.1.0";
        sha256 = "16b5cfhgymhww81f64yagfxhq8zgv7wmi591w2gw1i5fq7hz5isc";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "servant-support" = pkgs.stdenv.mkDerivation {
      name = "servant-support";
      version = "purs012.2";
      src = pkgs.fetchgit {
        url = "https://github.com/shmish111/purescript-servant-support.git";
        rev = "purs012.2";
        sha256 = "14j5lvp5wmjnby5dzcjl2ndwnzrz2jc0wfly1mfp6skn5s0q190k";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "st" = pkgs.stdenv.mkDerivation {
      name = "st";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-st.git";
        rev = "v4.0.0";
        sha256 = "0m2jkb9dmpbr8s1c20l7sm2q11y5rx8gqfiyspnyhq5apzkknjr0";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "strings" = pkgs.stdenv.mkDerivation {
      name = "strings";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-strings.git";
        rev = "v4.0.1";
        sha256 = "147l3l3fzn7liparhm2y3p8j4ck1lblra5j493p2hy5yy5ndznc8";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "tailrec" = pkgs.stdenv.mkDerivation {
      name = "tailrec";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tailrec.git";
        rev = "v4.0.0";
        sha256 = "0z7k80nl8dgv8mc2w8xsl2n0637bd1l8ppxak8kaifgjjwa81hx3";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "test-unit" = pkgs.stdenv.mkDerivation {
      name = "test-unit";
      version = "v15.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/bodil/purescript-test-unit.git";
        rev = "v15.0.0";
        sha256 = "06lb90vppa7naqqwz7wbvlkkyz86pbdd3ycw3d2iygvxbzkz8xjn";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "transformers" = pkgs.stdenv.mkDerivation {
      name = "transformers";
      version = "v4.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-transformers.git";
        rev = "v4.2.0";
        sha256 = "03qmvl9s7lbvm73dy9ps6qp39pdcm91hb8yakgj7aq8hgpj7b6bg";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "tuples" = pkgs.stdenv.mkDerivation {
      name = "tuples";
      version = "v5.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tuples.git";
        rev = "v5.1.0";
        sha256 = "045nsy0r2g51gih0wjhcvhl6gfr8947mlrqwg644ygz72rjm8wq4";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "type-equality" = pkgs.stdenv.mkDerivation {
      name = "type-equality";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-type-equality.git";
        rev = "v3.0.0";
        sha256 = "1b7szyca5s96gaawvgwrw7fa8r7gqsdff7xhz3vvngnylv2scl3w";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "typelevel-prelude" = pkgs.stdenv.mkDerivation {
      name = "typelevel-prelude";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-typelevel-prelude.git";
        rev = "v4.0.0";
        sha256 = "0j59ibdzbs555pjqmh6v4rampg733kvnicpwmyyrp1xrq8vz9a97";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "uint" = pkgs.stdenv.mkDerivation {
      name = "uint";
      version = "v5.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/zaquest/purescript-uint.git";
        rev = "v5.1.1";
        sha256 = "13103kqj2abiy8p7v81w1dj8jm0mll177mfjb7ar6km0bsxjigc6";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "undefinable" = pkgs.stdenv.mkDerivation {
      name = "undefinable";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/ethul/purescript-undefinable.git";
        rev = "v4.0.0";
        sha256 = "03z91g1n6zmiqgqqxi65g99a9qxfb8dcnzg2wnb16i2rl8frsl3v";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "unfoldable" = pkgs.stdenv.mkDerivation {
      name = "unfoldable";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unfoldable.git";
        rev = "v4.0.0";
        sha256 = "077vl30j3pxr3zw6cw7wd0vi22j92j8va15r26rn53wzbzcgr41j";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "unicode" = pkgs.stdenv.mkDerivation {
      name = "unicode";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-unicode.git";
        rev = "v4.0.1";
        sha256 = "1a53jv7pzyjk5v6kmwwy50d3l8d26k0id59sn8g3lzkih24nalhp";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
      name = "unsafe-coerce";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unsafe-coerce.git";
        rev = "v4.0.0";
        sha256 = "0k9255mk2mz6xjb11pwkgfcblmmyvr86ig5kr92jwy95xim09zip";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "unsafe-reference" = pkgs.stdenv.mkDerivation {
      name = "unsafe-reference";
      version = "v3.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-unsafe-reference";
        rev = "v3.0.1";
        sha256 = "0q758dz59qz0li4s3w1qcg921xp5i5rh6i1l611iv7rr8cbj11al";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-clipboard" = pkgs.stdenv.mkDerivation {
      name = "web-clipboard";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-clipboard.git";
        rev = "v2.0.0";
        sha256 = "17i7rpzxi7pgas32xz8vjcs54m94gnmca3my0p70gzvf3rasnxyx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-dom" = pkgs.stdenv.mkDerivation {
      name = "web-dom";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-dom.git";
        rev = "v2.0.0";
        sha256 = "17vcby3mldgzbskp1113krdw9a7z5vc83200685s4sfbf7rhc6w6";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-events" = pkgs.stdenv.mkDerivation {
      name = "web-events";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-events.git";
        rev = "v2.0.0";
        sha256 = "0z2q9zjjyx3djlkbdhhnhb1aw175rgklb5ylf3rnk9makbfk1rnf";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-file" = pkgs.stdenv.mkDerivation {
      name = "web-file";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-file.git";
        rev = "v2.0.0";
        sha256 = "05cc4vn1kpn2rzh7b14216v0jidyl7kzfqq7q9ydhmxlwb2k8jix";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-html" = pkgs.stdenv.mkDerivation {
      name = "web-html";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-html.git";
        rev = "v2.0.0";
        sha256 = "06dvymqxh297zz9h2y07w9hd6p8nw08r79whxjwcyh3zlsjra99d";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-storage" = pkgs.stdenv.mkDerivation {
      name = "web-storage";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-storage.git";
        rev = "v3.0.0";
        sha256 = "1ycb2s29aw9w6lqik6hfmp9nf9i2yhn0q26hc4p3450jam5mj8bx";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-touchevents" = pkgs.stdenv.mkDerivation {
      name = "web-touchevents";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-touchevents.git";
        rev = "v2.0.0";
        sha256 = "0mhsfqlglx04q3vkjg4k33bkxcpx2cmbq4x1zxyhl48q1qqmnic8";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-uievents" = pkgs.stdenv.mkDerivation {
      name = "web-uievents";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-uievents.git";
        rev = "v2.0.0";
        sha256 = "04032nl0z9hjq7b799zhbn7in10dz9kgrrcs0adjbaf08rc2kcwh";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };

    "web-xhr" = pkgs.stdenv.mkDerivation {
      name = "web-xhr";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-xhr.git";
        rev = "v3.0.0";
        sha256 = "114a16b5igxd03nzbsh0kfgmjgj5ank2n2yk9rwq0pqz5kfa2d1k";
      };
      phases = "installPhase";
      installPhase = "ln -s $src $out";
    };
};

in {
  inherit inputs;

  set = "local";
  source = "";
  sha256 = "local-setup-no-hash";
}
