ghc \
    -package-env=- \
    --make \
    -fbuilding-cabal-package \
    -O \
    -prof \
    -fprof-auto-exported \
    -osuf \
    p_o \
    -hisuf \
    p_hi \
    -outputdir \
    /Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build \
    -odir \
    /Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build \
    -hidir \
    /Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build \
    -hiedir \
    /Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build/extra-compilation-artifacts/hie \
    -stubdir \
    /Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build \
    -i \
    -isrc \
    -i/Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build \
    -i/Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build/autogen \
    -i/Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build/global-autogen \
    -I/Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build/autogen \
    -I/Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build/global-autogen \
    -I/Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build \
    -optP-include \
    -optP/Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/build/autogen/cabal_macros.h \
    -this-unit-id \
    plutus-profiled-plugin-test-0.1.0.0-inplace \
    -hide-all-packages \
    -Wmissing-home-modules \
    -no-user-package-db \
    -package-db \
    /Users/zeme/.cabal/store/ghc-9.6.7/package.db \
    -package-db \
    /Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/packagedb/ghc-9.6.7 \
    -package-db \
    /Volumes/Repos/plutus/worktrees/profiled-ghc/dist-newstyle/build/x86_64-osx/ghc-9.6.7/plutus-profiled-plugin-test-0.1.0.0/package.conf.inplace \
    -package-id \
    base-4.18.3.0 \
    -package-id \
    ghc-9.6.7 \
    -XHaskell2010 \
    SimplePlugin \
    -hide-all-packages \
    -DXXX \
    +RTS -pj -hc -I0.4444 -RTS