(
  ("language-plutus-core"      . ((haskell-mode . ((dante-target . "language-plutus-core:lib")))))
  ("language-plutus-core/test" . ((haskell-mode . ((dante-target . "language-plutus-core:test:language-plutus-core-test")))))
  ("plutus-exe"                . ((haskell-mode . ((dante-target . "plutus-exe:exe:plc")))))
  ("plutus-ir"                 . ((haskell-mode . ((dante-target . "plutus-ir:lib")))))
  ("plutus-ir/test"            . ((haskell-mode . ((dante-target . "plutus-ir:test:plutus-ir-test")))))
  ("plutus-tx"                 . ((haskell-mode . ((dante-target . "plutus-tx:lib")))))
  ("plutus-tx-plugin"          . ((haskell-mode . ((dante-target . "plutus-tx-plugin:lib")))))
  ("plutus-tx-plugin/test"     . ((haskell-mode . ((dante-target . "plutus-tx-plugin:test:plutus-tx-tests")))))
  ("plutus-wallet-api"         . ((haskell-mode . ((dante-target . "plutus-wallet-api")))))
  ("plutus-emulator"           . ((haskell-mode . ((dante-target . "plutus-emulator:lib")))))
  ("metatheory"                . ((haskell-mode . ((dante-target . "plc-agda:exe:plc-agda")))))
  ("metatheory/test"           . ((haskell-mode . ((dante-target . "plc-agda:test:plc-agda-test")))))
)
