(
  ("language-plutus-core"      . ((haskell-mode . ((dante-target . "language-plutus-core:lib")))))
  ("language-plutus-core/test" . ((haskell-mode . ((dante-target . "language-plutus-core:language-plutus-core-test")))))
  ("plutus-exe"                . ((haskell-mode . ((dante-target . "plutus-exe:plc")))))
  ("plutus-ir"                 . ((haskell-mode . ((dante-target . "plutus-ir:lib")))))
  ("plutus-ir/test"            . ((haskell-mode . ((dante-target . "plutus-ir:plutus-ir-test")))))
  ("plutus-tx"                 . ((haskell-mode . ((dante-target . "plutus-tx:lib")))))
  ("plutus-tx-plugin"          . ((haskell-mode . ((dante-target . "plutus-tx-plugin:lib")))))
  ("plutus-tx-plugin/test"     . ((haskell-mode . ((dante-target . "plutus-tx-plugin:plutus-tx-tests")))))
)
