---
- functions:
  - {name: unsafePerformIO, within: [PlutusPrelude]}
  - {name: error, within: [Main, Evaluation.Constant.Success, Evaluation.Generator, Language.PlutusCore.Constant.Apply, Language.PlutusCore.TH]}
  - {name: undefined, within: [Language.PlutusCore.Constant.Apply]}
  - {name: fromJust, within: []}
  - {name: foldl, within: []}

- error: {lhs: "hylo embed", rhs: "ana", name: "Use anamorphism"}
- error: {lhs: "hylo f project", rhs: "cata f", name: "Use catamorphism"}
- error: {lhs: "concat", rhs: "fold", name: "Generalize concat"}
- error: {lhs: "concatMap", rhs: "foldMap", name: "Generalize concatMap"}
- error: {lhs: "f >> pure ()", rhs: "void f", name: "Use void"}
- error: {lhs: "over _1 f x", rhs: "first f x", name: "Use arrows"}
- error: {lhs: "over _2 f x", rhs: "second f x", name: "Use arrows"}
- error: {lhs: "bool x x p", rhs: "x", name: "Redundant bool"}
- error: {lhs: "maybe mempty", rhs: "foldMap", name: "Use foldMap"}
- error: {lhs: "mconcat", rhs: "fold", name: "Generalize mconcat"}

- ignore: {name: Reduce duplication, within: [Language.PlutusCore.Renamer, Language.PlutusCore.Constant.Prelude]}
# this is rarely an improvement, also ignored in cardano
- ignore: {name: Move brackets to avoid $}

- fixity: infixr 8 .*
- fixity: infixr 3 ***
- fixity: infixr 3 &&&
- fixity: infixr 1 <=<
