
version: 2

sphinx:
  configuration: doc/read-the-docs-site/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: doc/read-the-docs-site/requirements.txt
