---
steps:
  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
  - imports:
      align: none
      post_qualify: true
  - language_pragmas:
      remove_redundant: false

  - trailing_whitespace: {}
columns: 100
newline: native
language_extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - ExistentialQuantification
  - ExplicitNamespaces
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - ImportQualifiedPost
  - PackageImports
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
