= https://github.com/input-output-hk/plutus[The Plutus Platform and Marlowe]
:email: plutus@iohk.io
:author: Input Output HK Limited
:toc: left
:reproducible:

The Plutus Platform is an application development platform for developing distributed applications using the Cardano blockchain; and Marlowe is a platform specifically for financial products, built on top of Plutus.
For more information about the projects, see https://docs.cardano.org/projects/plutus/en/latest/[the documentation].

This repository contains:

* Plutus Platform
  * The implementation, specification, and mechanized metatheory of Plutus Core, the scripting language embedded in the Cardano ledger.
  * Plutus Tx, the compiler from Haskell to Plutus Core.
  * Libraries which implement the Plutus Application Framework, a framework for writing applications that work with Cardano.
  * A selection of end-to-end usecases written with the Plutus Application Framework
  * The Plutus Playground, a web-based playground for learning and writing basic Plutus Applications.
* Marlowe
  * The implementation of the Marlowe domain-specific language.
  * Tools for working with Marlowe, including static analysis.
  * A selection of examples using Marlowe, including a number based on the ACTUS financial standard.
  * The Marlowe Playground, a web-based playground for learning and writing Marlowe Applications.

[IMPORTANT]
====
The rest of this README is focussed on people who want to develop or contribute to the Platform.

For people who want to *use* the Platform, please consult https://docs.cardano.org/projects/plutus/en/latest/[the documentation].
====

[[cache-warning]]
[IMPORTANT]
====
DO NOT IGNORE THIS

If you want to use Nix with this project, make sure to set up the xref:iohk-binary-cache[IOHK binary cache].
If you do not do this, you will end up building GHC, which takes several hours.
If you find yourself building GHC, STOP and fix the cache.
====

== How to use the project

This section contains brief information about how to use this project.
For development work see <<how-to-develop>> for more information.

[[prerequisites]]
=== Prerequisites

The Haskell libraries in the Plutus Platform can be built in a number of ways.
The prerequisites depend on how you want to build the libraries.
The other artifacts (docs etc.) are most easily built with Nix, so we recommend installing it regardless.

==== Nix

Install https://nixos.org/nix/[Nix] (recommended). following the instructions on the https://nixos.org/nix/[Nix website].

Make sure you have read and understood the xref:cache-warning[cache warning].
DO NOT IGNORE THIS.

See <<nix-advice>> for further advice on using Nix.

==== Non-Nix

If you use Nix, these tools are provided for you via `shell.nix`, and you do *not* need to install them yourself.

* If you want to build our Haskell packages with https://www.haskell.org/cabal/[`cabal`], then install it.
* If you want to build our Haskell packages with https://haskellstack.org/[`stack`], then install it.
* If you want to build our Agda code, then install https://github.com/agda/agda[Agda] and the https://github.com/agda/agda-stdlib[standard library].

=== How to build the Haskell packages and other artifacts

[[building-with-nix]]
==== How to build Haskell packages and other artifacts with Nix

Run `nix build -f default.nix plutus.haskell.packages.plutus-core.components.library` from the root to build the Plutus Core library.

See <<nix-build-attributes>> to find out what other attributes you can build.

==== How to build Haskell packages with `cabal`

Run `cabal build plutus-core` from the root to build the Plutus Core library.

NOTE: you must have R installed for this to work. https://cran.r-project.org/[R Installation]

See the link:./cabal.project[cabal project file] to see the other projects that you can build with `cabal`.

==== How to build the Haskell packages with `stack`

Run `stack build plutus-core` from the root to build the Plutus Core library.
The `stack` build is less well supported than the `cabal` build, we do not promise that it will work.

See the link:./stack.yaml[stack project file] to see the other projects that you can build with stack.

=== How to get the most recent documentation PDFs from CI

==== Specifications and design

- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.plutus-report/latest/download-by-type/doc-pdf/plutus[Plutus Technical Report] (draft)
- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.plutus-core-spec/latest/download-by-type/doc-pdf/plutus-core-specification[Plutus Core Specification]
- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.extended-utxo-spec/latest/download-by-type/doc-pdf/extended-utxo-specification[Extended UTXO Model]

==== Academic papers

- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.papers.unraveling-recursion/latest/download-by-type/doc-pdf/unraveling-recursion[Unraveling Recursion] (https://doi.org/10.1007/978-3-030-33636-3_15[published version])
- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.papers.system-f-in-agda/latest/download-by-type/doc-pdf/paper[System F in Agda] (https://doi.org/10.1007/978-3-030-33636-3_10[published version])
- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.papers.eutxo/latest/download-by-type/doc-pdf/eutxo[The Extended UTXO Model] (in press)
- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.papers.utxoma/latest/download-by-type/doc-pdf/utxoma[UTXOma: UTXO with Multi-Asset Support] (in press)
- https://hydra.iohk.io/job/Cardano/plutus/linux.docs.papers.eutxoma/latest/download-by-type/doc-pdf/eutxoma[Native Custom Tokens in the Extended UTXO Model] (in press)

== Where to go next

=== How to submit an issue

User issues can be filed in the https://github.com/input-output-hk/plutus/issues[GitHub Issue tracker].

However, note that this is pre-release software, so we will not usually be providing support.

[[how-to-develop]]
=== How to develop and contribute to the project

See link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING], which describes our processes in more detail including development environments; and link:ARCHITECTURE{outfilesuffix}[ARCHITECTURE], which describes the structure of the repository.

[[nix-advice]]
== Nix

[[iohk-binary-cache]]
=== How to set up the IOHK binary caches

Adding the IOHK binary cache to your Nix configuration will speed up
builds a lot, since many things will have been built already by our CI.

If you find you are building packages that are not defined in this
repository, or if the build seems to take a very long time then you may
not have this set up properly.

To set up the cache:

. On non-NixOS, edit `/etc/nix/nix.conf` and add the following lines:
+
----
substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
----
+
[NOTE]
====
If you don't have an `/etc/nix/nix.conf` or don't want to edit it, you may add the `nix.conf` lines to `~/.config/nix/nix.conf` instead.
You must be a https://nixos.org/nix/manual/#ssec-multi-user[trusted user] to do this.
====
. On NixOS, set the following NixOS options:
+
----
nix = {
  binaryCaches          = [ "https://hydra.iohk.io" "https://iohk.cachix.org" ];
  binaryCachePublicKeys = [ "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" "iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo=" ];
};
----


=== Nix on macOS

Nix on macOS can be a bit tricky. In particular, sandboxing is disabled by default, which can lead to strange failures.

These days it should be safe to turn on sandboxing on macOS with a few exceptions. Consider setting the following Nix settings, in the same way as in xref:iohk-binary-cache[previous section]:

----
sandbox = true
extra-sandbox-paths = /System/Library/Frameworks /System/Library/PrivateFrameworks /usr/lib /private/tmp /private/var/tmp /usr/bin/env
----


[[nix-build-attributes]]
=== Which attributes to use to build different artifacts

link:./default.nix[`default.nix`] defines a package set with attributes for all the artifacts you can build from this repository.
These can be built using `nix build`.
For example:

----
nix build -f default.nix docs.papers.eutxo
----

.Example attributes
* Project packages: defined inside `plutus.haskell.packages`
** e.g. `plutus.haskell.packages.plutus-core.components.library`
* Documents: defined inside `docs`
** e.g. `docs.plutus-core-spec`

There are other attributes defined in link:./default.nix[`default.nix`].

== Licensing

You are free to copy, modify, and distribute the Plutus Platform with
under the terms of the Apache 2.0 license. See the link:./LICENSE[LICENSE]
and link:./NOTICE[NOTICE] files for details.
