resolver: nightly-2020-08-31

packages:
- plutus-core
- plutus-tx
- plutus-tx-plugin
- plutus-use-cases
- playground-common
- marlowe
- marlowe-playground-server
- marlowe-actus
- plutus-metatheory
- plutus-ledger
- plutus-playground-server
- plutus-book
- plutus-contract
- plutus-scb
- deployment-server
- iots-export
- marlowe-symbolic
- prettyprinter-configurable
- doc
- web-ghc

extra-deps:
# FEAT/NEAT and deps
- lazy-search-0.1.2.1
- size-based-0.1.2.0
- testing-feat-1.1.0.0
- Stream-0.4.7.2@sha256:ed78165aa34c4e23dc53c9072f8715d414a585037f2145ea0eb2b38300354c53,1009
- lazysmallcheck-0.6@sha256:dac7a1e4877681f1260309e863e896674dd6efc1159897b7945893e693f2a6bc,1696
# Other missing packages
- async-timer-0.1.4.1
- aws-lambda-haskell-runtime-3.0.4
- composition-prelude-3.0.0.0
- constraints-extras-0.3.0.2
- dependent-map-0.4.0.0
- dependent-sum-0.7.1.0
- dependent-sum-template-0.1.0.3
- eventful-memory-0.2.0
- barbies-2.0.2.0
# A revision was added to keep the bounds down, we don't actually want this!
# we work around the newer persistent-template by adding flags below
- eventful-sql-common-0.2.0@rev:0
- eventful-sqlite-0.2.0
- canonical-json-0.6.0.0
- github-0.26
- inline-r-0.10.3
- monoidal-containers-0.6.0.1
- nonempty-containers-0.3.3.0
- persistent-sqlite-2.10.6.2
- persistent-template-2.8.2.3
- row-types-0.4.0.0
- safe-exceptions-checked-0.1.0
- sbv-8.7
- servant-client-0.17
- servant-client-core-0.17
- servant-foreign-0.15.1
- servant-github-webhook-0.4.2.0
- servant-server-0.17
- servant-subscriber-0.7.0.0
- servant-websockets-2.0.0
- statistics-linreg-0.3
- time-interval-0.1.1
- time-out-0.2
- wl-pprint-1.2.1

# Needs some patches, but upstream seems to be fairly dead (no activity in > 1 year)
- git: https://github.com/shmish111/purescript-bridge.git
  commit: 28c37771ef30b0d751960c061ef95627f05d290e
- git: https://github.com/shmish111/servant-purescript.git
  commit: ece5d1dad16a5731ac22040075615803796c7c21
- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: 2547ad1e80aeabca2899951601079408becbc92c
# Needs a fix (https://github.com/wenkokke/unlit/pull/11) and a Hackage release
- git: https://github.com/michaelpj/unlit.git
  commit: 9ca1112093c5ffd356fc99c7dafa080e686dd748
- git: https://github.com/input-output-hk/ouroboros-network
  commit: 75153affa23a0e68e035d7bb19880fe1ae35b1d4
  subdirs:
    - typed-protocols
    - typed-protocols-examples
    - ouroboros-network
    - ouroboros-network-framework
    - io-sim
    - io-sim-classes
    - network-mux
    - Win32-network
- git: https://github.com/input-output-hk/cardano-prelude
  commit: 71ea865408f2e03e6d6832359423546699730849
  subdirs:
    - .
    - test
- git: https://github.com/input-output-hk/cardano-base
  commit: 5035c9ed95e9d47f050314a7d96b1b2043288f61
  subdirs:
    - binary
    - binary/test
    - cardano-crypto-class
    - slotting
# Making the repository compatible with GHC-8.8.X required a couple of
# source code changes, so I forked the original repository until it will
# be properly updated to GHC-8.8.X
- git: https://github.com/raduom/cardano-ledger-specs
  commit: 2cac85306d8b3e07006e9081f36ce7ebf2d9d0a3
  subdirs:
    - byron/chain/executable-spec
    - byron/ledger/executable-spec
    - semantics/executable-spec
    - shelley/chain-and-ledger/dependencies/non-integer
    - shelley/chain-and-ledger/executable-spec
    - shelley/chain-and-ledger/executable-spec/test
# Making the repository compatible with GHC-8.8.X required a couple of
# source code changes, so I forked the original repository until it will
# be properly updated to GHC-8.8.X
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: 5c9627b6aee487f9b7ec44981aba57a6afc659b1
  subdirs:
    - contra-tracer
    - iohk-monitoring
    - tracer-transformers
    - plugins/backend-ekg
- git: https://github.com/input-output-hk/goblins
  commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

allow-newer: true

flags:
  cardano-prelude:
    development: true
  cardano-prelude-test:
    development: true
  cardano-binary:
    development: true
  cardano-binary-test:
    development: true
  cardano-crypto-class:
    development: true
  small-steps:
    development: true
  byron-spec-ledger:
    development: true
  shelley-spec-ledger:
    development: true
  byron-spec-chain:
    development: true
  shelley-spec-ledger-test:
    development: true

## / Node protocols

extra-package-dbs: []

ghc-options:
  # Newer versions of persistent-template require some extra language extensions. Fortunately
  # we can hack around this here rather than having to fork eventful & co (for now)
  eventful-sql-common: "-XDerivingStrategies -XStandaloneDeriving -XUndecidableInstances"
  # Disable all warnings, we're building with a newer version of GHC
  iohk-monitoring: "-w"

nix:
  shell-file: shell.nix
