resolver: lts-13.15

packages:
- language-plutus-core
- plutus-core-interpreter
- plutus-exe
- plutus-ir
- plutus-tx
- plutus-use-cases
- playground-common
- marlowe
- meadow
- plutus-wallet-api
- plutus-playground-server
- plutus-playground-lib
- plutus-tutorial
- plutus-contract-exe
- plutus-emulator

# Needs some patches, but upstream seems to be fairly dead (no activity in > 1 year)
- location:
    git: https://github.com/shmish111/purescript-bridge.git
    commit: a7069a515800135ce932742e995f3a96bc1c7129
  extra-dep: true
- location:
    git: https://github.com/shmish111/servant-purescript.git
    commit: ab14502279c92084f06aa6222a17873275279e63
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto.git
    commit: f5cecb6e424cc84f85b6a3e1f803517bb7b4cfb1
  extra-dep: true
# Needs a fix (https://github.com/wenkokke/unlit/pull/11) and a Hackage release
- location:
    git: https://github.com/michaelpj/unlit.git
    commit: 9ca1112093c5ffd356fc99c7dafa080e686dd748
  extra-dep: true
# Needs looser containers bound, committed upstream but not released
- location:
    git: https://github.com/bitnomial/prometheus.git
    commit: 69e4cefeb7d04d61a54cb0ae9fd57e2de134badb
  extra-dep: true

extra-deps:
# Agda and deps
- Agda-2.6.0
- data-hash-0.2.0.1
- EdisonCore-1.3.2.1
- EdisonAPI-1.3.1
- equivalence-0.3.4
- STMonadTrans-0.4.3
- geniplate-mirror-0.7.6
# Other missing packages
- composition-prelude-2.0.2.1
- resolv-0.1.1.2
- monad-stm-0.1.0.2
- purescript-0.12.4
- servant-options-0.1.0.0
- servant-subscriber-0.6.0.2
- tasty-hedgehog-0.2.0.0
- jwt-0.9.0
- time-out-0.2@sha256:b9a6b4dee64f030ecb2a25dca0faff39b3cb3b5fefbb8af3cdec4142bfd291f2
- time-interval-0.1.1@sha256:7bfd3601853d1af7caa18248ec10b01701d035ac274a93bb4670fea52a14d4e8
- time-units-1.0.0@sha256:27cf54091c4a0ca73d504fc11d5c31ab4041d17404fe3499945e2055697746c1
- wl-pprint-1.2.1@sha256:aea676cff4a062d7d912149d270e33f5bb0c01b68a9db46ff13b438141ff4b7c
flags:
  language-plutus-core:
    development: true
  plutus-wallet-api:
    development: true
  plutus-exe:
    development: true
  plutus-core-interpreter:
    development: true
  plutus-playground-server:
    development: true
  plutus-contract-exe:
    development: true
extra-package-dbs: []
nix:
  packages: [gmp, openssl]
