resolver: lts-12.26

packages:
- language-plutus-core
- plutus-core-interpreter
- plutus-exe
- plutus-ir
- plutus-tx
- plutus-use-cases
- wallet-api
- plutus-playground/plutus-playground-server
- plutus-playground/plutus-playground-lib
- plutus-tutorial

# Needs some patches, but upstream seems to be fairly dead (no activity in > 1 year)
- location:
    git: https://github.com/shmish111/servant-purescript.git
    commit: 315ccf5d720937c091c8cf3aca8adc8110766a23
  extra-dep: true

extra-deps:
- serialise-0.2.1.0
- monad-stm-0.1.0.2
- servant-options-0.1.0.0
- hint-0.9.0
- exceptions-0.10.0
- purescript-bridge-0.13.0.0
- servant-subscriber-0.6.0.2
flags:
  language-plutus-core:
    development: true
  wallet-api:
    development: true
  plutus-exe:
    development: true
  plutus-core-interpreter:
    development: true
  plutus-playground-server:
    development: true
extra-package-dbs: []
nix:
  packages: [gmp, openssl]
