resolver: lts-12.14

packages:
- language-plutus-core
- plutus-core-interpreter
- plutus-exe
- plutus-ir
- plutus-tx
- plutus-tx-plugin
- plutus-use-cases
- wallet-api
- runfiles

# Add custom stylish-haskell while waiting for PR upstream: https://github.com/jaspervdj/stylish-haskell/pull/214
- location:
    git: https://github.com/input-output-hk/stylish-haskell.git
    commit: ecfd3b307d8d13a6d12aff03055f25a39a17e182
  extra-dep: true

extra-deps:
- serialise-0.2.1.0
- monad-stm-0.1.0.2
flags:
  language-plutus-core:
    development: true
  wallet-api:
    development: true
  plutus-tx-plugin:
    development: true
  plutus-exe:
    development: true
  plutus-core-interpreter:
    development: true
extra-package-dbs: []
nix:
  packages: [gmp, openssl]
