resolver: lts-11.11

packages:
- plutus-prototype
- language-plutus-core

- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 838b064d8a59286142aa2fe14434fe7601896ddb
  extra-dep: true

extra-deps:
- cryptonite-0.22
- containers-0.5.11.0
- value-supply-0.6
- recursion-1.2.0.1
- cborg-0.2.0.0

flags:
  language-plutus-core:
    development: true
extra-package-dbs: []
nix:
  packages: [gmp, openssl]
