resolver: lts-11.11

packages:
- plutus-prototype
- language-plutus-core
- plutus-core-interpreter
- plutus-exe
- core-to-plc
- plutus-th
- plutus-use-cases
- wallet-api
- plutus-playground/plutus-playground-server

- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 838b064d8a59286142aa2fe14434fe7601896ddb
  extra-dep: true
# Add custom stylish-haskell while waiting for PR upstream: https://github.com/jaspervdj/stylish-haskell/pull/214
- location:
    git: https://github.com/input-output-hk/stylish-haskell.git
    commit: ecfd3b307d8d13a6d12aff03055f25a39a17e182
  extra-dep: true

extra-deps:
- cryptonite-0.25
- cborg-0.2.0.0
- serialise-0.2.0.0
- monad-stm-0.1.0.2
- tasty-hedgehog-0.2.0.0
- servant-options-0.1.0.0
- hint-0.9.0
- exceptions-0.10.0
- purescript-bridge-0.13.0.0
flags:
  language-plutus-core:
    development: true
  wallet-api:
    development: true
  core-to-plc:
    development: true
  plutus-exe:
    development: true
  plutus-core-interpreter:
    development: true
extra-package-dbs: []
nix:
  packages: [gmp, openssl]
