resolver: lts-15.6

packages:
- prettyprinter-configurable
- language-plutus-core
- plutus-ir
- plutus-tx
- plutus-tx-plugin
- plutus-use-cases
- playground-common
- marlowe
- marlowe-hspec
- marlowe-playground-server
- metatheory
- plutus-ledger
- plutus-playground-server
- plutus-playground-lib
- plutus-tutorial
- plutus-book
- plutus-contract
- plutus-contract-tasty
- plutus-scb
- plutus-emulator
- deployment-server
- iots-export
- marlowe-symbolic

extra-deps:
# Other missing packages
- aws-lambda-haskell-runtime-2.0.4
- binary-instances-1.0.0.1
- composition-prelude-2.0.2.1
- constraints-extras-0.3.0.2
- dependent-map-0.3
- dependent-sum-0.6.2.0
- dependent-sum-template-0.1.0.3
- deriving-aeson-0.2.3
- ekg-0.4.0.15
- ekg-core-0.1.1.7
- ekg-json-0.1.0.6
- eventful-memory-0.2.0
# A revision was added to keep the bounds down, we don't actually want this!
# we work around the newer persistent-template by adding flags below
- eventful-sql-common-0.2.0@rev:0
- eventful-sqlite-0.2.0
- github-0.24
- github-webhooks-0.12.0
- monoidal-containers-0.6.0.1
- monad-stm-0.1.0.2
- prometheus-2.1.3
- row-types-0.3.1.0
- time-out-0.2@sha256:b9a6b4dee64f030ecb2a25dca0faff39b3cb3b5fefbb8af3cdec4142bfd291f2
- time-interval-0.1.1@sha256:7bfd3601853d1af7caa18248ec10b01701d035ac274a93bb4670fea52a14d4e8
- time-units-1.0.0@sha256:27cf54091c4a0ca73d504fc11d5c31ab4041d17404fe3499945e2055697746c1
- th-utilities-0.2.4.0
- servant-options-0.1.0.0
- servant-github-webhook-0.4.1.0@sha256:6ac456ccc6a2a96b30a7b80cd91b121f1b7e9bd33635641a6afbd6137700a753
- sbv-8.6
- random-strings-0.1.1.0@sha256:935a7a23dab45411960df77636a29b44ce42b89eeb15f2b1e809d771491fa677,2517
- wl-pprint-1.2.1@sha256:aea676cff4a062d7d912149d270e33f5bb0c01b68a9db46ff13b438141ff4b7c
# Needs some patches, but upstream seems to be fairly dead (no activity in > 1 year)
- git: https://github.com/shmish111/purescript-bridge.git
  commit: 28c37771ef30b0d751960c061ef95627f05d290e
  # nix-sha256: 0n6q7g2w1xafngd3dwbbmfxfn018fmq61db7mymplbrww8ld1cp3
- git: https://github.com/shmish111/servant-purescript.git
  commit: ece5d1dad16a5731ac22040075615803796c7c21
  # nix-sha256: 1axcbsaym64q67hvjc7b3izd48cgqwi734l7f7m22jpdc80li5f6
- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: 2547ad1e80aeabca2899951601079408becbc92c
  # nix-sha256: 1p2kg2w02q5w1cvqzhfhqmxviy4xrzada3mmb096j2n6hfr20kri
# Needs a fix (https://github.com/wenkokke/unlit/pull/11) and a Hackage release
- git: https://github.com/michaelpj/unlit.git
  commit: 9ca1112093c5ffd356fc99c7dafa080e686dd748
  # nix-sha256: 145sffn8gbdn6xp9q5b75yd3m46ql5bnc02arzmpfs6wgjslfhff
# Needs https://github.com/jpvillaisaza/slack-web/pull/80
- git: https://github.com/michaelpj/slack-web.git
  commit: 6ff88895c5da593e7bd09a46d7002441817aa6f8
  # nix-sha256: 1115jngzx2hbvznhnrnm4qs9vn6hsjklxwiwa5i11npr2kxd5rm2
extra-package-dbs: []

ghc-options:
  # Newer versions of persistent-template require some extra language extensions. Fortunately
  # we can hack around this here rather than having to fork eventful & co (for now)
  eventful-sql-common: "-XDerivingStrategies -XStandaloneDeriving -XUndecidableInstances"

nix:
  packages: [zlib, gmp, openssl]
