resolver: lts-17.2

packages:
- doc
- freer-extras
- marlowe
- marlowe-dashboard-server
- marlowe-actus
- marlowe-playground-server
- marlowe-symbolic
- playground-common
- plutus-benchmark
- plutus-contract
- plutus-core
- plutus-errors
- plutus-ledger
- plutus-ledger-api
- plutus-metatheory
- plutus-pab
- plutus-playground-server
- plutus-tx
- plutus-tx-plugin
- plutus-use-cases
- prettyprinter-configurable
- quickcheck-dynamic
- web-ghc

extra-deps:
# Flat compression
- pure-zlib-0.6.7@sha256:5a1cdf87bf3079b7d3abace1f94eeb3c597c687a38a08ee2908783e609271467,3487
# FEAT/NEAT and deps
- lazy-search-0.1.2.0
- size-based-0.1.2.0
- testing-feat-1.1.0.0
- Stream-0.4.7.2@sha256:ed78165aa34c4e23dc53c9072f8715d414a585037f2145ea0eb2b38300354c53,1009
- lazysmallcheck-0.6@sha256:dac7a1e4877681f1260309e863e896674dd6efc1159897b7945893e693f2a6bc,1696
# Other missing packages
- aws-lambda-haskell-runtime-3.0.3
- aws-lambda-haskell-runtime-wai-1.0.2@sha256:5ce655247461b562c8048011ddc022130135a03417def8203aad92366cc979ab,1965
- composition-prelude-3.0.0.2
- constraints-extras-0.3.0.2
- dependent-map-0.4.0.0
- dependent-sum-0.6.2.0
- dependent-sum-template-0.1.0.3
- eventful-memory-0.2.0
- barbies-2.0.2.0
- nothunks-0.1.2
- indexed-traversable-instances-0.1
- base16-bytestring-1.0.1.0
# A revision was added to keep the bounds down, we don't actually want this!
# we work around the newer persistent-template by adding flags below
- eventful-sql-common-0.2.0@rev:0
- eventful-sqlite-0.2.0
- monoidal-containers-0.6.0.1
- recursion-schemes-5.1.3
- row-types-0.4.0.0
- time-out-0.2@sha256:b9a6b4dee64f030ecb2a25dca0faff39b3cb3b5fefbb8af3cdec4142bfd291f2
- time-interval-0.1.1@sha256:7bfd3601853d1af7caa18248ec10b01701d035ac274a93bb4670fea52a14d4e8
- time-units-1.0.0@sha256:27cf54091c4a0ca73d504fc11d5c31ab4041d17404fe3499945e2055697746c1
- servant-websockets-2.0.0
- servant-subscriber-0.7.0.0
- safe-exceptions-checked-0.1.0
- async-timer-0.1.4.1
- sbv-8.9
- wl-pprint-1.2.1@sha256:aea676cff4a062d7d912149d270e33f5bb0c01b68a9db46ff13b438141ff4b7c
- witherable-0.4.1
- canonical-json-0.6.0.0@sha256:9021f435ccb884a3b4c55bcc6b50eb19d5fc3cc3f29d5fcbdef016f5bbae23a2,3488
- statistics-linreg-0.3@sha256:95c6efe6c7f6b26bc6e9ada90ab2d18216371cf59a6ef2b517b4a6fd35d9a76f,2544
# cabal.project is the source of truth for these pins, they are explained there
# and need to be kept in sync.
- git: https://github.com/shmish111/purescript-bridge.git
  commit: 6a92d7853ea514be8b70bab5e72077bf5a510596
- git: https://github.com/eskimor/servant-purescript.git
  commit: 6454d5bcb9aa2a5d6e3a3dc935423b67b6f3993c
- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: f73079303f663e028288f9f4a9e08bcca39a923e
- git: https://github.com/input-output-hk/ouroboros-network
  commit: 6cb9052bde39472a0555d19ade8a42da63d3e904
  subdirs:
    - typed-protocols
    - typed-protocols-examples
    - ouroboros-network
    - ouroboros-network-framework
    - io-sim
    - io-sim-classes
    - network-mux
    - Win32-network
- git: https://github.com/input-output-hk/cardano-prelude
  commit: ee4e7b547a991876e6b05ba542f4e62909f4a571
  subdirs:
    - cardano-prelude 
    - cardano-prelude-test
- git: https://github.com/input-output-hk/cardano-base
  commit: 4251c0bb6e4f443f00231d28f5f70d42876da055
  subdirs:
    - binary
    - cardano-crypto-class
    - cardano-crypto-tests
    - cardano-crypto-praos
    - slotting
- git: https://github.com/input-output-hk/cardano-ledger-specs
  commit: 097890495cbb0e8b62106bcd090a5721c3f4b36f
  subdirs:
    - byron/chain/executable-spec
    - byron/crypto
    - byron/crypto/test
    - byron/ledger/executable-spec
    - byron/ledger/impl
    - byron/ledger/impl/test
    - semantics/executable-spec
    - semantics/small-steps-test
    - shelley/chain-and-ledger/dependencies/non-integer
    - shelley/chain-and-ledger/executable-spec
    - shelley-ma/impl
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: a89c38ed5825ba17ca79fddb85651007753d699d
  subdirs:
    - contra-tracer
    - iohk-monitoring
    - tracer-transformers
    - plugins/backend-ekg

allow-newer: true

extra-package-dbs: []

ghc-options:
  # Newer versions of persistent-template require some extra language extensions. Fortunately
  # we can hack around this here rather than having to fork eventful & co (for now)
  eventful-sql-common: "-XDerivingStrategies -XStandaloneDeriving -XUndecidableInstances -XDataKinds -XFlexibleInstances -XMultiParamTypeClasses"

nix:
  shell-file: shell.nix
