resolver: lts-12.14

packages:
- language-plutus-core
- plutus-core-interpreter
- plutus-exe
- plutus-ir
- plutus-tx
- plutus-tx-plugin
- plutus-use-cases
- wallet-api
- plutus-playground/plutus-playground-server
- plutus-playground/plutus-playground-lib

# Add custom stylish-haskell while waiting for PR upstream: https://github.com/jaspervdj/stylish-haskell/pull/214
- location:
    git: https://github.com/input-output-hk/stylish-haskell.git
    commit: ecfd3b307d8d13a6d12aff03055f25a39a17e182
  extra-dep: true

- location:
    git: https://github.com/shmish111/servant-purescript.git
    commit: 315ccf5d720937c091c8cf3aca8adc8110766a23
  extra-dep: true

- location:
    git: https://github.com/smobs/servant-subscriber.git
    commit: 0354e99f5e1d244d5ec01f78e7e7439478b1d1d3
  extra-dep: true

extra-deps:
- serialise-0.2.1.0
- monad-stm-0.1.0.2
- servant-options-0.1.0.0
- hint-0.9.0
- exceptions-0.10.0
- purescript-bridge-0.13.0.0
flags:
  language-plutus-core:
    development: true
  wallet-api:
    development: true
  plutus-tx-plugin:
    development: true
  plutus-exe:
    development: true
  plutus-core-interpreter:
    development: true
  plutus-playground-server:
    development: true
extra-package-dbs: []
nix:
  packages: [gmp, openssl]
