[#intro]
= Introduction to Plutus

Plutus is the smart contract platform of the Cardano blockchain. Plutus
contracts consist of pieces that go on the blockchain (on-chain code)
and pieces that run on the user’s machine (off-chain or client code).

Both on-chain and off-chain code is written in Haskell, and Plutus smart
contracts are Haskell programs. Off-chain code is compiled by GHC, the
Haskell compiler, and on-chain code is compiled by the Plutus compiler.

== Smart contracts

From the smart contract author’s perspective, the blockchain is a
distributed bookkeeping system. It keeps track of who owns how much of a
virtual resource (Bitcoin, Ada, etc.) and records when assets are
transferred from one entity to another. The owners of digital assets are
identified by their public keys, and they may be people or machines.

Smart contracts are programs that control the transfer of resources on
the blockchain. When two parties decide to enter a smart contract, they
place some of their own assets under the control of the contract. Every
time somenone wants to take assets out of the contract, the program is
run and only if its output is positive are the assets released.

On the Cardano blockchain, the programs that run on the blockchain are
written in a language called _Plutus Core_. However, smart contract
authors do not write Plutus Core directly. The Plutus Platform is a
software development kit to enable smart contract authors to easily
write smart contracts, including the logic that will eventually be run
on the blockchain as Plutus Core.

To code a smart contract in Plutus, you can code directly in the Plutus 
Playground editor, or you can use your preferred code editor and save the 
files in Haskell format (.hs) to get the syntax highlighting, 
and most important, you can write on-chain and off-chain code in the same file, 
with the same syntax. You can use the same data types on both sides, 
and they will be converted automatically.

Once you have coded your smart contract, you can copy it in the 
Plutus Playground where you will be able to compile it to Plutus Core 
and test its behavior.
