= Overview

This document is a series of tutorials that explain various
aspects of the Plutus smart contract platform.

[arabic]
. xref:intro#intro[] introduces smart
contracts and related terms
. xref:01-plutus-tx#plutus-tx[] explains the basics of using
the Plutus Tx compiler to create embedded (on-chain) programs
. xref:02-validator-scripts#validator-scripts[] implements a
guessing game. Topics covered:
    * Signature of validator script
    * `Ledger.makeLift`, `Ledger.compileScript`
    * Contract endpoints
    * `Wallet.payToScript_`, `Wallet.collectFromScript`
    * Playground
. xref:03-wallet-api#wallet-api[] implements a
crowdfunding campaign. Topics covered:
    * Parameterising a contract through partial application using
    `Ledger.applyScript`
    * Operators in on-chain code
    * On-chain time (slot intervals)
    * Working with Ada values
    * Blockchain triggers
. xref:04-vesting#multi-stage[] implements a vesting scheme. Topics covered:
    * Writing a contract that extends over multiple transactions

Additional documentation will be added for the following
work-in-progress features, when they are available on the mockchain:

* Forging new currencies
* Using NFTs to represent permissions
* Decoding values from their on-chain representation back to Haskell

== Prerequisites

To follow the xref:02-validator-scripts#validator-scripts[],
xref:03-wallet-api#wallet-api[], and xref:04-vesting#multi-stage[] tutorials you
should have access to a recent version of the Plutus Playground.

The examples can all be run in GHCi using a local copy of the Plutus repository.

== Using the libraries locally

To use the libraries (not the Playground) locally, follow these steps.

=== Linux/macOS

[arabic]
. Install the nix package manager following the instructions on
https://nixos.org/nix/.
+
IMPORTANT: Make sure to add the IOHK binary cache to your Nix configuration. See
link:../README.md#binary-caches[the repository README] for details.
. Clone https://github.com/input-output-hk/plutus.
. Move to the plutus-tutorial folder.
. Type `nix-shell`. This will download all of the dependencies and
populate the PATH with a correctly configured cabal. If `nix-shell`
results in nix attempting to compile a lot of dependencies then
something went wrong earlier and you should go back to step 4.
. Type `cabal repl plutus-tutorial`.

=== Windows

[arabic]
. Install the "Ubuntu 18.04" app from the app store
. Open the "Ubuntu 18.04" terminal by clicking on the icon

Then follow the steps for "Linux" above.
