program
  1.1.0
  ((\`$fOrdInteger_$ccompare` ->
      (\validatePreds ->
         (\euclid ->
            (\unsafeRatio ->
               (\cse ->
                  (\validateParamValue ->
                     (\validateParamValues ->
                        (\runRules ->
                           (\matchData_go ->
                              (\cse ->
                                 (\cse ->
                                    (\cse ->
                                       (\cse ->
                                          (\cse ->
                                             (\cse ->
                                                (\cse ->
                                                   (\cse ->
                                                      (\cse ->
                                                         (\cse ->
                                                            (\cse ->
                                                               (\cse ->
                                                                  (\cse ->
                                                                     (\cse ->
                                                                        (\cse ->
                                                                           (\cse ->
                                                                              (\cse ->
                                                                                 (\cse ->
                                                                                    (\cse ->
                                                                                       (\cse ->
                                                                                          (\cse ->
                                                                                             (\cse ->
                                                                                                (\cse ->
                                                                                                   (\cse ->
                                                                                                      (\cse ->
                                                                                                         (\cse ->
                                                                                                            (\cse ->
                                                                                                               (\cse ->
                                                                                                                  (\fun
                                                                                                                    ds ->
                                                                                                                     case
                                                                                                                       ((\ds ->
                                                                                                                           (\x ->
                                                                                                                              case
                                                                                                                                (equalsInteger
                                                                                                                                   0
                                                                                                                                   x)
                                                                                                                                [ (case
                                                                                                                                     (equalsInteger
                                                                                                                                        2
                                                                                                                                        x)
                                                                                                                                     [ error
                                                                                                                                     , (constr 1
                                                                                                                                          [  ]) ])
                                                                                                                                , (constr 0
                                                                                                                                     [ ((\d ->
                                                                                                                                           force
                                                                                                                                             matchData_go
                                                                                                                                             (unMapData
                                                                                                                                                d))
                                                                                                                                          (force
                                                                                                                                             headList
                                                                                                                                             (force
                                                                                                                                                tailList
                                                                                                                                                (case
                                                                                                                                                   ds
                                                                                                                                                   [ (\l
                                                                                                                                                       r ->
                                                                                                                                                        r) ])))) ]) ])
                                                                                                                             (case
                                                                                                                                ds
                                                                                                                                [ (\l
                                                                                                                                    r ->
                                                                                                                                     l) ]))
                                                                                                                          (unConstrData
                                                                                                                             (force
                                                                                                                                headList
                                                                                                                                (force
                                                                                                                                   tailList
                                                                                                                                   (force
                                                                                                                                      tailList
                                                                                                                                      (case
                                                                                                                                         (unConstrData
                                                                                                                                            ((\si ->
                                                                                                                                                case
                                                                                                                                                  (equalsInteger
                                                                                                                                                     5
                                                                                                                                                     (case
                                                                                                                                                        si
                                                                                                                                                        [ (\l
                                                                                                                                                            r ->
                                                                                                                                                             l) ]))
                                                                                                                                                  [ error
                                                                                                                                                  , (force
                                                                                                                                                       headList
                                                                                                                                                       (force
                                                                                                                                                          tailList
                                                                                                                                                          (case
                                                                                                                                                             si
                                                                                                                                                             [ (\l
                                                                                                                                                                 r ->
                                                                                                                                                                  r) ]))) ])
                                                                                                                                               (unConstrData
                                                                                                                                                  (force
                                                                                                                                                     headList
                                                                                                                                                     (force
                                                                                                                                                        tailList
                                                                                                                                                        (force
                                                                                                                                                           tailList
                                                                                                                                                           (case
                                                                                                                                                              (unConstrData
                                                                                                                                                                 ds)
                                                                                                                                                              [ (\l
                                                                                                                                                                  r ->
                                                                                                                                                                   r) ])))))))
                                                                                                                                         [ (\l
                                                                                                                                             r ->
                                                                                                                                              r) ]))))))
                                                                                                                       [ (\cparams ->
                                                                                                                            case
                                                                                                                              (fun
                                                                                                                                 cparams)
                                                                                                                              [ error
                                                                                                                              , () ])
                                                                                                                       , () ])
                                                                                                                    (runRules
                                                                                                                       (constr 1
                                                                                                                          [ (constr 0
                                                                                                                               [ 0
                                                                                                                               , (constr 1
                                                                                                                                    [ (constr 1
                                                                                                                                         [ (constr 0
                                                                                                                                              [ (constr 1
                                                                                                                                                   [  ])
                                                                                                                                              , (constr 1
                                                                                                                                                   [ 30
                                                                                                                                                   , cse ]) ])
                                                                                                                                         , (constr 1
                                                                                                                                              [ (constr 0
                                                                                                                                                   [ (constr 0
                                                                                                                                                        [  ])
                                                                                                                                                   , (constr 1
                                                                                                                                                        [ 1000
                                                                                                                                                        , (constr 0
                                                                                                                                                             [  ]) ]) ])
                                                                                                                                              , (constr 0
                                                                                                                                                   [  ]) ]) ]) ]) ])
                                                                                                                          , (constr 1
                                                                                                                               [ (constr 0
                                                                                                                                    [ 1
                                                                                                                                    , (constr 1
                                                                                                                                         [ (constr 1
                                                                                                                                              [ (constr 0
                                                                                                                                                   [ (constr 1
                                                                                                                                                        [  ])
                                                                                                                                                   , (constr 1
                                                                                                                                                        [ 100000
                                                                                                                                                        , cse ]) ])
                                                                                                                                              , (constr 1
                                                                                                                                                   [ (constr 0
                                                                                                                                                        [ (constr 0
                                                                                                                                                             [  ])
                                                                                                                                                        , (constr 1
                                                                                                                                                             [ 10000000
                                                                                                                                                             , (constr 0
                                                                                                                                                                  [  ]) ]) ])
                                                                                                                                                   , (constr 0
                                                                                                                                                        [  ]) ]) ]) ]) ])
                                                                                                                               , (constr 1
                                                                                                                                    [ (constr 0
                                                                                                                                         [ 2
                                                                                                                                         , (constr 1
                                                                                                                                              [ (constr 1
                                                                                                                                                   [ (constr 0
                                                                                                                                                        [ (constr 1
                                                                                                                                                             [  ])
                                                                                                                                                        , (constr 1
                                                                                                                                                             [ 24576
                                                                                                                                                             , (constr 0
                                                                                                                                                                  [  ]) ]) ])
                                                                                                                                                   , (constr 1
                                                                                                                                                        [ (constr 0
                                                                                                                                                             [ (constr 0
                                                                                                                                                                  [  ])
                                                                                                                                                             , (constr 1
                                                                                                                                                                  [ 122880
                                                                                                                                                                  , (constr 0
                                                                                                                                                                       [  ]) ]) ])
                                                                                                                                                        , (constr 0
                                                                                                                                                             [  ]) ]) ]) ]) ])
                                                                                                                                    , (constr 1
                                                                                                                                         [ (constr 0
                                                                                                                                              [ 3
                                                                                                                                              , (constr 1
                                                                                                                                                   [ (constr 1
                                                                                                                                                        [ cse
                                                                                                                                                        , (constr 1
                                                                                                                                                             [ (constr 0
                                                                                                                                                                  [ (constr 0
                                                                                                                                                                       [  ])
                                                                                                                                                                  , (constr 1
                                                                                                                                                                       [ 32768
                                                                                                                                                                       , (constr 0
                                                                                                                                                                            [  ]) ]) ])
                                                                                                                                                             , (constr 0
                                                                                                                                                                  [  ]) ]) ]) ]) ])
                                                                                                                                         , (constr 1
                                                                                                                                              [ (constr 0
                                                                                                                                                   [ 4
                                                                                                                                                   , (constr 1
                                                                                                                                                        [ (constr 1
                                                                                                                                                             [ cse
                                                                                                                                                             , (constr 1
                                                                                                                                                                  [ (constr 0
                                                                                                                                                                       [ (constr 0
                                                                                                                                                                            [  ])
                                                                                                                                                                       , (constr 1
                                                                                                                                                                            [ 5000
                                                                                                                                                                            , (constr 0
                                                                                                                                                                                 [  ]) ]) ])
                                                                                                                                                                  , (constr 0
                                                                                                                                                                       [  ]) ]) ]) ]) ])
                                                                                                                                              , (constr 1
                                                                                                                                                   [ (constr 0
                                                                                                                                                        [ 5
                                                                                                                                                        , (constr 1
                                                                                                                                                             [ (constr 1
                                                                                                                                                                  [ (constr 0
                                                                                                                                                                       [ (constr 1
                                                                                                                                                                            [  ])
                                                                                                                                                                       , (constr 1
                                                                                                                                                                            [ 1000000
                                                                                                                                                                            , cse ]) ])
                                                                                                                                                                  , (constr 1
                                                                                                                                                                       [ (constr 0
                                                                                                                                                                            [ (constr 0
                                                                                                                                                                                 [  ])
                                                                                                                                                                            , (constr 1
                                                                                                                                                                                 [ 5000000
                                                                                                                                                                                 , (constr 0
                                                                                                                                                                                      [  ]) ]) ])
                                                                                                                                                                       , (constr 0
                                                                                                                                                                            [  ]) ]) ]) ]) ])
                                                                                                                                                   , (constr 1
                                                                                                                                                        [ (constr 0
                                                                                                                                                             [ 6
                                                                                                                                                             , (constr 1
                                                                                                                                                                  [ (constr 1
                                                                                                                                                                       [ (constr 0
                                                                                                                                                                            [ (constr 1
                                                                                                                                                                                 [  ])
                                                                                                                                                                            , (constr 1
                                                                                                                                                                                 [ 250000000
                                                                                                                                                                                 , cse ]) ])
                                                                                                                                                                       , cse ]) ]) ])
                                                                                                                                                        , (constr 1
                                                                                                                                                             [ (constr 0
                                                                                                                                                                  [ 7
                                                                                                                                                                  , (constr 1
                                                                                                                                                                       [ (constr 1
                                                                                                                                                                            [ cse
                                                                                                                                                                            , (constr 0
                                                                                                                                                                                 [  ]) ]) ]) ])
                                                                                                                                                             , (constr 1
                                                                                                                                                                  [ (constr 0
                                                                                                                                                                       [ 8
                                                                                                                                                                       , (constr 1
                                                                                                                                                                            [ (constr 1
                                                                                                                                                                                 [ (constr 0
                                                                                                                                                                                      [ (constr 1
                                                                                                                                                                                           [  ])
                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                           [ 250
                                                                                                                                                                                           , cse ]) ])
                                                                                                                                                                                 , (constr 1
                                                                                                                                                                                      [ (constr 0
                                                                                                                                                                                           [ (constr 0
                                                                                                                                                                                                [  ])
                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                [ 2000
                                                                                                                                                                                                , (constr 0
                                                                                                                                                                                                     [  ]) ]) ])
                                                                                                                                                                                      , cse ]) ]) ]) ])
                                                                                                                                                                  , (constr 1
                                                                                                                                                                       [ (constr 0
                                                                                                                                                                            [ 9
                                                                                                                                                                            , (constr 3
                                                                                                                                                                                 [ (constr 1
                                                                                                                                                                                      [ cse
                                                                                                                                                                                      , cse ]) ]) ])
                                                                                                                                                                       , (constr 1
                                                                                                                                                                            [ (constr 0
                                                                                                                                                                                 [ 10
                                                                                                                                                                                 , (constr 3
                                                                                                                                                                                      [ (constr 1
                                                                                                                                                                                           [ (constr 0
                                                                                                                                                                                                [ (constr 1
                                                                                                                                                                                                     [  ])
                                                                                                                                                                                                , (constr 1
                                                                                                                                                                                                     [ (cse
                                                                                                                                                                                                          1000)
                                                                                                                                                                                                     , cse ]) ])
                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                [ (constr 0
                                                                                                                                                                                                     [ (constr 0
                                                                                                                                                                                                          [  ])
                                                                                                                                                                                                     , (constr 1
                                                                                                                                                                                                          [ (cse
                                                                                                                                                                                                               200)
                                                                                                                                                                                                          , (constr 0
                                                                                                                                                                                                               [  ]) ]) ])
                                                                                                                                                                                                , (constr 0
                                                                                                                                                                                                     [  ]) ]) ]) ]) ])
                                                                                                                                                                            , (constr 1
                                                                                                                                                                                 [ (constr 0
                                                                                                                                                                                      [ 11
                                                                                                                                                                                      , (constr 3
                                                                                                                                                                                           [ (constr 1
                                                                                                                                                                                                [ cse
                                                                                                                                                                                                , (constr 1
                                                                                                                                                                                                     [ (constr 0
                                                                                                                                                                                                          [ (constr 0
                                                                                                                                                                                                               [  ])
                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                               [ (cse
                                                                                                                                                                                                                    10)
                                                                                                                                                                                                               , cse ]) ])
                                                                                                                                                                                                     , (constr 0
                                                                                                                                                                                                          [  ]) ]) ]) ]) ])
                                                                                                                                                                                 , (constr 1
                                                                                                                                                                                      [ (constr 0
                                                                                                                                                                                           [ 16
                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                [ (constr 1
                                                                                                                                                                                                     [ cse
                                                                                                                                                                                                     , cse ]) ]) ])
                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                           [ (constr 0
                                                                                                                                                                                                [ 17
                                                                                                                                                                                                , (constr 1
                                                                                                                                                                                                     [ (constr 1
                                                                                                                                                                                                          [ (constr 0
                                                                                                                                                                                                               [ (constr 1
                                                                                                                                                                                                                    [  ])
                                                                                                                                                                                                               , (constr 1
                                                                                                                                                                                                                    [ 3000
                                                                                                                                                                                                                    , cse ]) ])
                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                               [ (constr 0
                                                                                                                                                                                                                    [ (constr 0
                                                                                                                                                                                                                         [  ])
                                                                                                                                                                                                                    , (constr 1
                                                                                                                                                                                                                         [ 6500
                                                                                                                                                                                                                         , (constr 0
                                                                                                                                                                                                                              [  ]) ]) ])
                                                                                                                                                                                                               , cse ]) ]) ]) ])
                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                [ (constr 0
                                                                                                                                                                                                     [ 18
                                                                                                                                                                                                     , (constr 0
                                                                                                                                                                                                          [  ]) ])
                                                                                                                                                                                                , (constr 1
                                                                                                                                                                                                     [ (constr 0
                                                                                                                                                                                                          [ 19
                                                                                                                                                                                                          , (constr 2
                                                                                                                                                                                                               [ (constr 1
                                                                                                                                                                                                                    [ (constr 3
                                                                                                                                                                                                                         [ (constr 1
                                                                                                                                                                                                                              [ (constr 0
                                                                                                                                                                                                                                   [ (constr 1
                                                                                                                                                                                                                                        [  ])
                                                                                                                                                                                                                                   , (constr 1
                                                                                                                                                                                                                                        [ (cse
                                                                                                                                                                                                                                             25)
                                                                                                                                                                                                                                        , (constr 0
                                                                                                                                                                                                                                             [  ]) ]) ])
                                                                                                                                                                                                                              , (constr 1
                                                                                                                                                                                                                                   [ (constr 0
                                                                                                                                                                                                                                        [ (constr 0
                                                                                                                                                                                                                                             [  ])
                                                                                                                                                                                                                                        , (constr 1
                                                                                                                                                                                                                                             [ (cse
                                                                                                                                                                                                                                                  5)
                                                                                                                                                                                                                                             , (constr 0
                                                                                                                                                                                                                                                  [  ]) ]) ])
                                                                                                                                                                                                                                   , (constr 0
                                                                                                                                                                                                                                        [  ]) ]) ]) ])
                                                                                                                                                                                                                    , (constr 1
                                                                                                                                                                                                                         [ (constr 3
                                                                                                                                                                                                                              [ (constr 1
                                                                                                                                                                                                                                   [ (constr 0
                                                                                                                                                                                                                                        [ (constr 1
                                                                                                                                                                                                                                             [  ])
                                                                                                                                                                                                                                        , (constr 1
                                                                                                                                                                                                                                             [ (cse
                                                                                                                                                                                                                                                  20000)
                                                                                                                                                                                                                                             , (constr 0
                                                                                                                                                                                                                                                  [  ]) ]) ])
                                                                                                                                                                                                                                   , (constr 1
                                                                                                                                                                                                                                        [ (constr 0
                                                                                                                                                                                                                                             [ (constr 0
                                                                                                                                                                                                                                                  [  ])
                                                                                                                                                                                                                                             , (constr 1
                                                                                                                                                                                                                                                  [ (cse
                                                                                                                                                                                                                                                       5000)
                                                                                                                                                                                                                                                  , (constr 0
                                                                                                                                                                                                                                                       [  ]) ]) ])
                                                                                                                                                                                                                                        , (constr 0
                                                                                                                                                                                                                                             [  ]) ]) ]) ])
                                                                                                                                                                                                                         , (constr 0
                                                                                                                                                                                                                              [  ]) ]) ]) ]) ])
                                                                                                                                                                                                     , (constr 1
                                                                                                                                                                                                          [ (constr 0
                                                                                                                                                                                                               [ 20
                                                                                                                                                                                                               , (constr 2
                                                                                                                                                                                                                    [ (constr 1
                                                                                                                                                                                                                         [ (constr 1
                                                                                                                                                                                                                              [ (constr 1
                                                                                                                                                                                                                                   [ cse
                                                                                                                                                                                                                                   , (constr 1
                                                                                                                                                                                                                                        [ (constr 0
                                                                                                                                                                                                                                             [ (constr 0
                                                                                                                                                                                                                                                  [  ])
                                                                                                                                                                                                                                             , (constr 1
                                                                                                                                                                                                                                                  [ 40000000
                                                                                                                                                                                                                                                  , (constr 0
                                                                                                                                                                                                                                                       [  ]) ]) ])
                                                                                                                                                                                                                                        , (constr 0
                                                                                                                                                                                                                                             [  ]) ]) ]) ])
                                                                                                                                                                                                                         , (constr 1
                                                                                                                                                                                                                              [ (constr 1
                                                                                                                                                                                                                                   [ (constr 1
                                                                                                                                                                                                                                        [ cse
                                                                                                                                                                                                                                        , (constr 1
                                                                                                                                                                                                                                             [ (constr 0
                                                                                                                                                                                                                                                  [ (constr 0
                                                                                                                                                                                                                                                       [  ])
                                                                                                                                                                                                                                                  , (constr 1
                                                                                                                                                                                                                                                       [ 15000000000
                                                                                                                                                                                                                                                       , (constr 0
                                                                                                                                                                                                                                                            [  ]) ]) ])
                                                                                                                                                                                                                                             , (constr 0
                                                                                                                                                                                                                                                  [  ]) ]) ]) ])
                                                                                                                                                                                                                              , (constr 0
                                                                                                                                                                                                                                   [  ]) ]) ]) ]) ])
                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                               [ (constr 0
                                                                                                                                                                                                                    [ 21
                                                                                                                                                                                                                    , (constr 2
                                                                                                                                                                                                                         [ (constr 1
                                                                                                                                                                                                                              [ (constr 1
                                                                                                                                                                                                                                   [ (constr 1
                                                                                                                                                                                                                                        [ cse
                                                                                                                                                                                                                                        , (constr 1
                                                                                                                                                                                                                                             [ (constr 0
                                                                                                                                                                                                                                                  [ (constr 0
                                                                                                                                                                                                                                                       [  ])
                                                                                                                                                                                                                                                  , (constr 1
                                                                                                                                                                                                                                                       [ 120000000
                                                                                                                                                                                                                                                       , (constr 0
                                                                                                                                                                                                                                                            [  ]) ]) ])
                                                                                                                                                                                                                                             , (constr 0
                                                                                                                                                                                                                                                  [  ]) ]) ]) ])
                                                                                                                                                                                                                              , (constr 1
                                                                                                                                                                                                                                   [ (constr 1
                                                                                                                                                                                                                                        [ (constr 1
                                                                                                                                                                                                                                             [ cse
                                                                                                                                                                                                                                             , (constr 1
                                                                                                                                                                                                                                                  [ (constr 0
                                                                                                                                                                                                                                                       [ (constr 0
                                                                                                                                                                                                                                                            [  ])
                                                                                                                                                                                                                                                       , (constr 1
                                                                                                                                                                                                                                                            [ 40000000000
                                                                                                                                                                                                                                                            , (constr 0
                                                                                                                                                                                                                                                                 [  ]) ]) ])
                                                                                                                                                                                                                                                  , (constr 0
                                                                                                                                                                                                                                                       [  ]) ]) ]) ])
                                                                                                                                                                                                                                   , (constr 0
                                                                                                                                                                                                                                        [  ]) ]) ]) ]) ])
                                                                                                                                                                                                               , (constr 1
                                                                                                                                                                                                                    [ (constr 0
                                                                                                                                                                                                                         [ 22
                                                                                                                                                                                                                         , (constr 1
                                                                                                                                                                                                                              [ (constr 1
                                                                                                                                                                                                                                   [ cse
                                                                                                                                                                                                                                   , (constr 1
                                                                                                                                                                                                                                        [ (constr 0
                                                                                                                                                                                                                                             [ (constr 0
                                                                                                                                                                                                                                                  [  ])
                                                                                                                                                                                                                                             , (constr 1
                                                                                                                                                                                                                                                  [ 12288
                                                                                                                                                                                                                                                  , (constr 0
                                                                                                                                                                                                                                                       [  ]) ]) ])
                                                                                                                                                                                                                                        , (constr 0
                                                                                                                                                                                                                                             [  ]) ]) ]) ]) ])
                                                                                                                                                                                                                    , (constr 1
                                                                                                                                                                                                                         [ (constr 0
                                                                                                                                                                                                                              [ 23
                                                                                                                                                                                                                              , (constr 1
                                                                                                                                                                                                                                   [ (constr 1
                                                                                                                                                                                                                                        [ (constr 0
                                                                                                                                                                                                                                             [ (constr 1
                                                                                                                                                                                                                                                  [  ])
                                                                                                                                                                                                                                             , (constr 1
                                                                                                                                                                                                                                                  [ 100
                                                                                                                                                                                                                                                  , cse ]) ])
                                                                                                                                                                                                                                        , (constr 1
                                                                                                                                                                                                                                             [ (constr 0
                                                                                                                                                                                                                                                  [ (constr 0
                                                                                                                                                                                                                                                       [  ])
                                                                                                                                                                                                                                                  , (constr 1
                                                                                                                                                                                                                                                       [ 200
                                                                                                                                                                                                                                                       , (constr 0
                                                                                                                                                                                                                                                            [  ]) ]) ])
                                                                                                                                                                                                                                             , cse ]) ]) ]) ])
                                                                                                                                                                                                                         , (constr 1
                                                                                                                                                                                                                              [ (constr 0
                                                                                                                                                                                                                                   [ 24
                                                                                                                                                                                                                                   , (constr 1
                                                                                                                                                                                                                                        [ (constr 1
                                                                                                                                                                                                                                             [ cse
                                                                                                                                                                                                                                             , (constr 0
                                                                                                                                                                                                                                                  [  ]) ]) ]) ])
                                                                                                                                                                                                                              , (constr 1
                                                                                                                                                                                                                                   [ (constr 0
                                                                                                                                                                                                                                        [ 25
                                                                                                                                                                                                                                        , (constr 2
                                                                                                                                                                                                                                             [ (constr 1
                                                                                                                                                                                                                                                  [ cse
                                                                                                                                                                                                                                                  , (constr 1
                                                                                                                                                                                                                                                       [ cse
                                                                                                                                                                                                                                                       , (constr 1
                                                                                                                                                                                                                                                            [ cse
                                                                                                                                                                                                                                                            , (constr 1
                                                                                                                                                                                                                                                                 [ cse
                                                                                                                                                                                                                                                                 , cse ]) ]) ]) ]) ]) ])
                                                                                                                                                                                                                                   , (constr 1
                                                                                                                                                                                                                                        [ (constr 0
                                                                                                                                                                                                                                             [ 26
                                                                                                                                                                                                                                             , (constr 2
                                                                                                                                                                                                                                                  [ (constr 1
                                                                                                                                                                                                                                                       [ cse
                                                                                                                                                                                                                                                       , (constr 1
                                                                                                                                                                                                                                                            [ cse
                                                                                                                                                                                                                                                            , (constr 1
                                                                                                                                                                                                                                                                 [ cse
                                                                                                                                                                                                                                                                 , (constr 1
                                                                                                                                                                                                                                                                      [ (constr 3
                                                                                                                                                                                                                                                                           [ (constr 1
                                                                                                                                                                                                                                                                                [ (constr 0
                                                                                                                                                                                                                                                                                     [ (constr 1
                                                                                                                                                                                                                                                                                          [  ])
                                                                                                                                                                                                                                                                                     , (constr 1
                                                                                                                                                                                                                                                                                          [ cse
                                                                                                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                                                                                                               [ (unsafeRatio
                                                                                                                                                                                                                                                                                                    13
                                                                                                                                                                                                                                                                                                    20)
                                                                                                                                                                                                                                                                                               , (constr 0
                                                                                                                                                                                                                                                                                                    [  ]) ]) ]) ])
                                                                                                                                                                                                                                                                                , cse ]) ])
                                                                                                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                                                                                                           [ cse
                                                                                                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                                                                                                [ cse
                                                                                                                                                                                                                                                                                , (constr 1
                                                                                                                                                                                                                                                                                     [ cse
                                                                                                                                                                                                                                                                                     , (constr 1
                                                                                                                                                                                                                                                                                          [ cse
                                                                                                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                                                                                                               [ (constr 3
                                                                                                                                                                                                                                                                                                    [ (constr 1
                                                                                                                                                                                                                                                                                                         [ (constr 0
                                                                                                                                                                                                                                                                                                              [ (constr 1
                                                                                                                                                                                                                                                                                                                   [  ])
                                                                                                                                                                                                                                                                                                              , (constr 1
                                                                                                                                                                                                                                                                                                                   [ cse
                                                                                                                                                                                                                                                                                                                   , cse ]) ])
                                                                                                                                                                                                                                                                                                         , cse ]) ])
                                                                                                                                                                                                                                                                                               , cse ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])
                                                                                                                                                                                                                                        , (constr 1
                                                                                                                                                                                                                                             [ (constr 0
                                                                                                                                                                                                                                                  [ 27
                                                                                                                                                                                                                                                  , (constr 1
                                                                                                                                                                                                                                                       [ (constr 1
                                                                                                                                                                                                                                                            [ (constr 0
                                                                                                                                                                                                                                                                 [ (constr 1
                                                                                                                                                                                                                                                                      [  ])
                                                                                                                                                                                                                                                                 , (constr 1
                                                                                                                                                                                                                                                                      [ 0
                                                                                                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                                                                                                           [ 3
                                                                                                                                                                                                                                                                           , (constr 0
                                                                                                                                                                                                                                                                                [  ]) ]) ]) ])
                                                                                                                                                                                                                                                            , (constr 1
                                                                                                                                                                                                                                                                 [ (constr 0
                                                                                                                                                                                                                                                                      [ (constr 0
                                                                                                                                                                                                                                                                           [  ])
                                                                                                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                                                                                                           [ 10
                                                                                                                                                                                                                                                                           , (constr 0
                                                                                                                                                                                                                                                                                [  ]) ]) ])
                                                                                                                                                                                                                                                                 , (constr 0
                                                                                                                                                                                                                                                                      [  ]) ]) ]) ]) ])
                                                                                                                                                                                                                                             , (constr 1
                                                                                                                                                                                                                                                  [ (constr 0
                                                                                                                                                                                                                                                       [ 28
                                                                                                                                                                                                                                                       , (constr 1
                                                                                                                                                                                                                                                            [ (constr 1
                                                                                                                                                                                                                                                                 [ (constr 0
                                                                                                                                                                                                                                                                      [ (constr 1
                                                                                                                                                                                                                                                                           [  ])
                                                                                                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                                                                                                           [ 0
                                                                                                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                                                                                                [ 18
                                                                                                                                                                                                                                                                                , (constr 0
                                                                                                                                                                                                                                                                                     [  ]) ]) ]) ])
                                                                                                                                                                                                                                                                 , (constr 1
                                                                                                                                                                                                                                                                      [ (constr 0
                                                                                                                                                                                                                                                                           [ (constr 0
                                                                                                                                                                                                                                                                                [  ])
                                                                                                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                                                                                                [ 293
                                                                                                                                                                                                                                                                                , (constr 0
                                                                                                                                                                                                                                                                                     [  ]) ]) ])
                                                                                                                                                                                                                                                                      , cse ]) ]) ]) ])
                                                                                                                                                                                                                                                  , (constr 1
                                                                                                                                                                                                                                                       [ (constr 0
                                                                                                                                                                                                                                                            [ 29
                                                                                                                                                                                                                                                            , (constr 1
                                                                                                                                                                                                                                                                 [ (constr 1
                                                                                                                                                                                                                                                                      [ cse
                                                                                                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                                                                                                           [ (constr 0
                                                                                                                                                                                                                                                                                [ (constr 0
                                                                                                                                                                                                                                                                                     [  ])
                                                                                                                                                                                                                                                                                , (constr 1
                                                                                                                                                                                                                                                                                     [ 15
                                                                                                                                                                                                                                                                                     , (constr 0
                                                                                                                                                                                                                                                                                          [  ]) ]) ])
                                                                                                                                                                                                                                                                           , (constr 0
                                                                                                                                                                                                                                                                                [  ]) ]) ]) ]) ])
                                                                                                                                                                                                                                                       , (constr 1
                                                                                                                                                                                                                                                            [ (constr 0
                                                                                                                                                                                                                                                                 [ 30
                                                                                                                                                                                                                                                                 , (constr 1
                                                                                                                                                                                                                                                                      [ (constr 1
                                                                                                                                                                                                                                                                           [ cse
                                                                                                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                                                                                                [ (constr 0
                                                                                                                                                                                                                                                                                     [ (constr 0
                                                                                                                                                                                                                                                                                          [  ])
                                                                                                                                                                                                                                                                                     , (constr 1
                                                                                                                                                                                                                                                                                          [ 10000000000000
                                                                                                                                                                                                                                                                                          , (constr 0
                                                                                                                                                                                                                                                                                               [  ]) ]) ])
                                                                                                                                                                                                                                                                                , (constr 0
                                                                                                                                                                                                                                                                                     [  ]) ]) ]) ]) ])
                                                                                                                                                                                                                                                            , (constr 1
                                                                                                                                                                                                                                                                 [ (constr 0
                                                                                                                                                                                                                                                                      [ 31
                                                                                                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                                                                                                           [ (constr 1
                                                                                                                                                                                                                                                                                [ cse
                                                                                                                                                                                                                                                                                , (constr 1
                                                                                                                                                                                                                                                                                     [ (constr 0
                                                                                                                                                                                                                                                                                          [ (constr 0
                                                                                                                                                                                                                                                                                               [  ])
                                                                                                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                                                                                                               [ 100000000000
                                                                                                                                                                                                                                                                                               , (constr 0
                                                                                                                                                                                                                                                                                                    [  ]) ]) ])
                                                                                                                                                                                                                                                                                     , (constr 0
                                                                                                                                                                                                                                                                                          [  ]) ]) ]) ]) ])
                                                                                                                                                                                                                                                                 , (constr 1
                                                                                                                                                                                                                                                                      [ (constr 0
                                                                                                                                                                                                                                                                           [ 32
                                                                                                                                                                                                                                                                           , (constr 1
                                                                                                                                                                                                                                                                                [ (constr 1
                                                                                                                                                                                                                                                                                     [ (constr 0
                                                                                                                                                                                                                                                                                          [ (constr 1
                                                                                                                                                                                                                                                                                               [  ])
                                                                                                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                                                                                                               [ 13
                                                                                                                                                                                                                                                                                               , cse ]) ])
                                                                                                                                                                                                                                                                                     , (constr 1
                                                                                                                                                                                                                                                                                          [ (constr 0
                                                                                                                                                                                                                                                                                               [ (constr 0
                                                                                                                                                                                                                                                                                                    [  ])
                                                                                                                                                                                                                                                                                               , (constr 1
                                                                                                                                                                                                                                                                                                    [ 37
                                                                                                                                                                                                                                                                                                    , (constr 0
                                                                                                                                                                                                                                                                                                         [  ]) ]) ])
                                                                                                                                                                                                                                                                                          , (constr 0
                                                                                                                                                                                                                                                                                               [  ]) ]) ]) ]) ])
                                                                                                                                                                                                                                                                      , (constr 1
                                                                                                                                                                                                                                                                           [ (constr 0
                                                                                                                                                                                                                                                                                [ 33
                                                                                                                                                                                                                                                                                , (constr 3
                                                                                                                                                                                                                                                                                     [ (constr 1
                                                                                                                                                                                                                                                                                          [ (constr 0
                                                                                                                                                                                                                                                                                               [ (constr 1
                                                                                                                                                                                                                                                                                                    [  ])
                                                                                                                                                                                                                                                                                               , cse ])
                                                                                                                                                                                                                                                                                          , (constr 1
                                                                                                                                                                                                                                                                                               [ (constr 0
                                                                                                                                                                                                                                                                                                    [ (constr 0
                                                                                                                                                                                                                                                                                                         [  ])
                                                                                                                                                                                                                                                                                                    , (constr 1
                                                                                                                                                                                                                                                                                                         [ (unsafeRatio
                                                                                                                                                                                                                                                                                                              1000
                                                                                                                                                                                                                                                                                                              1)
                                                                                                                                                                                                                                                                                                         , (constr 0
                                                                                                                                                                                                                                                                                                              [  ]) ]) ])
                                                                                                                                                                                                                                                                                               , (constr 0
                                                                                                                                                                                                                                                                                                    [  ]) ]) ]) ]) ])
                                                                                                                                                                                                                                                                           , (constr 0
                                                                                                                                                                                                                                                                                [  ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])))
                                                                                                                 (constr 3
                                                                                                                    [ (constr 1
                                                                                                                         [ cse
                                                                                                                         , (constr 1
                                                                                                                              [ (constr 0
                                                                                                                                   [ (constr 0
                                                                                                                                        [  ])
                                                                                                                                   , (constr 1
                                                                                                                                        [ cse
                                                                                                                                        , cse ]) ])
                                                                                                                              , (constr 0
                                                                                                                                   [  ]) ]) ]) ]))
                                                                                                              (constr 3
                                                                                                                 [ (constr 1
                                                                                                                      [ cse
                                                                                                                      , cse ]) ]))
                                                                                                           (constr 3
                                                                                                              [ (constr 1
                                                                                                                   [ cse
                                                                                                                   , (constr 1
                                                                                                                        [ (constr 0
                                                                                                                             [ (constr 0
                                                                                                                                  [  ])
                                                                                                                             , (constr 1
                                                                                                                                  [ cse
                                                                                                                                  , (constr 1
                                                                                                                                       [ cse
                                                                                                                                       , (constr 0
                                                                                                                                            [  ]) ]) ]) ])
                                                                                                                        , (constr 0
                                                                                                                             [  ]) ]) ]) ]))
                                                                                                        (constr 1
                                                                                                           [ (constr 3
                                                                                                                [ (constr 1
                                                                                                                     [ (constr 0
                                                                                                                          [ (constr 1
                                                                                                                               [  ])
                                                                                                                          , (constr 1
                                                                                                                               [ cse
                                                                                                                               , (constr 0
                                                                                                                                    [  ]) ]) ])
                                                                                                                     , cse ]) ])
                                                                                                           , (constr 0
                                                                                                                [  ]) ]))
                                                                                                     (constr 1
                                                                                                        [ (constr 0
                                                                                                             [ (constr 0
                                                                                                                  [  ])
                                                                                                             , (constr 1
                                                                                                                  [ cse
                                                                                                                  , (constr 1
                                                                                                                       [ (cse
                                                                                                                            10)
                                                                                                                       , (constr 0
                                                                                                                            [  ]) ]) ]) ])
                                                                                                        , (constr 0
                                                                                                             [  ]) ]))
                                                                                                  (constr 0
                                                                                                     [ (constr 1
                                                                                                          [  ])
                                                                                                     , (constr 1
                                                                                                          [ cse
                                                                                                          , cse ]) ]))
                                                                                               (constr 0
                                                                                                  [ (constr 1
                                                                                                       [  ])
                                                                                                  , (constr 1
                                                                                                       [ cse
                                                                                                       , (constr 1
                                                                                                            [ cse
                                                                                                            , (constr 0
                                                                                                                 [  ]) ]) ]) ]))
                                                                                            (constr 1
                                                                                               [ (constr 0
                                                                                                    [ (constr 0
                                                                                                         [  ])
                                                                                                    , cse ])
                                                                                               , (constr 0
                                                                                                    [  ]) ]))
                                                                                         (constr 0
                                                                                            [ (constr 1
                                                                                                 [  ])
                                                                                            , (constr 1
                                                                                                 [ 0
                                                                                                 , (constr 1
                                                                                                      [ 1000000
                                                                                                      , (constr 0
                                                                                                           [  ]) ]) ]) ]))
                                                                                      (constr 1
                                                                                         [ (constr 0
                                                                                              [ (constr 2
                                                                                                   [  ])
                                                                                              , cse ])
                                                                                         , (constr 0
                                                                                              [  ]) ]))
                                                                                   (constr 1
                                                                                      [ cse
                                                                                      , (constr 0
                                                                                           [  ]) ]))
                                                                                (constr 1
                                                                                   [ (constr 0
                                                                                        [ (constr 0
                                                                                             [  ])
                                                                                        , (constr 1
                                                                                             [ 500000000
                                                                                             , (constr 0
                                                                                                  [  ]) ]) ])
                                                                                   , (constr 0
                                                                                        [  ]) ]))
                                                                             (constr 1
                                                                                [ cse
                                                                                , (constr 0
                                                                                     [  ]) ]))
                                                                          (constr 1
                                                                             [ (cse
                                                                                  1)
                                                                             , (constr 0
                                                                                  [  ]) ]))
                                                                       (cse 10))
                                                                    (cse 1))
                                                                 (constr 0
                                                                    [ (constr 1
                                                                         [])
                                                                    , cse ]))
                                                              (cse 4))
                                                           (constr 0
                                                              [ (constr 1 [])
                                                              , (constr 1
                                                                   [ 1
                                                                   , (constr 0
                                                                        [  ]) ]) ]))
                                                        (cse 100))
                                                     (cse 2))
                                                  (unsafeRatio 4 5))
                                               (unsafeRatio 51))
                                            (unsafeRatio 3))
                                         (unsafeRatio 0))
                                      (constr 1 [0, (constr 0 [])]))
                                   (unsafeRatio 1))
                                (unsafeRatio 9))
                             ((\s -> s s)
                                (\s arg ->
                                   delay
                                     (\xs ->
                                        case
                                          xs
                                          [ (\x xs ->
                                               constr 1
                                                 [ (case
                                                      x
                                                      [ (\l r ->
                                                           constr 0 [l, r]) ])
                                                 , (force
                                                      (s s (delay (\x -> x)))
                                                      xs) ])
                                          , (constr 0 []) ]))
                                (delay (\x -> x))))
                          ((\s -> s s)
                             (\s ds cparams ->
                                case
                                  ds
                                  [ (case cparams [True, (\ipv ipv -> False)])
                                  , (\ds cfgRest ->
                                       case
                                         ds
                                         [ (\expectedPid paramValue ->
                                              case
                                                cparams
                                                [ (case
                                                     cparams
                                                     [ True
                                                     , (\ipv ipv -> False) ])
                                                , (\ds cparamsRest ->
                                                     case
                                                       ds
                                                       [ (\ds actualValueData ->
                                                            case
                                                              (`$fOrdInteger_$ccompare`
                                                                 (unIData ds)
                                                                 expectedPid)
                                                              [ (case
                                                                   (validateParamValue
                                                                      paramValue
                                                                      actualValueData)
                                                                   [ False
                                                                   , (case
                                                                        (constr 0
                                                                           [ s
                                                                           , cfgRest
                                                                           , cparamsRest ])
                                                                        [s]) ])
                                                              , (case
                                                                   (constr 0
                                                                      [ s
                                                                      , cfgRest
                                                                      , cparams ])
                                                                   [s])
                                                              , False ]) ]) ]) ]) ])))
                       (cse (\arg_0 arg_1 -> arg_1)))
                    (cse (\arg_0 arg_1 -> arg_0)))
                 (force
                    ((\s -> s s)
                       (\s h ->
                          delay
                            (\fr ->
                               (\k ->
                                  fr
                                    (\x -> k (\f_0 f_1 -> f_0 x))
                                    (\x -> k (\f_0 f_1 -> f_1 x)))
                                 (\fq -> force (s s h) (force h fq))))
                       (delay
                          (\choose validateParamValue validateParamValues ->
                             choose
                               (\eta eta ->
                                  case
                                    eta
                                    [ True
                                    , (\preds ->
                                         case
                                           (constr 0
                                              [ (constr 0
                                                   [ (\x y -> equalsInteger x y)
                                                   , `$fOrdInteger_$ccompare`
                                                   , (\x y ->
                                                        lessThanInteger x y)
                                                   , (\x y ->
                                                        lessThanEqualsInteger
                                                          x
                                                          y)
                                                   , (\x y ->
                                                        case
                                                          (lessThanEqualsInteger
                                                             x
                                                             y)
                                                          [True, False])
                                                   , (\x y ->
                                                        case
                                                          (lessThanInteger x y)
                                                          [True, False])
                                                   , (\x y ->
                                                        case
                                                          (lessThanEqualsInteger
                                                             x
                                                             y)
                                                          [x, y])
                                                   , (\x y ->
                                                        case
                                                          (lessThanEqualsInteger
                                                             x
                                                             y)
                                                          [y, x]) ])
                                              , preds
                                              , (unIData eta) ])
                                           [validatePreds])
                                    , (\paramValues ->
                                         validateParamValues
                                           paramValues
                                           (unListData eta))
                                    , (\preds ->
                                         case
                                           (constr 0
                                              [ (constr 0
                                                   [ (\ds ds ->
                                                        case
                                                          ds
                                                          [ (\n d ->
                                                               case
                                                                 ds
                                                                 [ (\n' d' ->
                                                                      case
                                                                        (equalsInteger
                                                                           n
                                                                           n')
                                                                        [ False
                                                                        , (equalsInteger
                                                                             d
                                                                             d') ]) ]) ])
                                                   , (\ds ds ->
                                                        case
                                                          ds
                                                          [ (\n d ->
                                                               case
                                                                 ds
                                                                 [ (\n' d' ->
                                                                      (\x ->
                                                                         (\y ->
                                                                            case
                                                                              (equalsInteger
                                                                                 x
                                                                                 y)
                                                                              [ (case
                                                                                   (lessThanEqualsInteger
                                                                                      x
                                                                                      y)
                                                                                   [ (constr 1
                                                                                        [  ])
                                                                                   , (constr 2
                                                                                        [  ]) ])
                                                                              , (constr 0
                                                                                   [  ]) ])
                                                                           (multiplyInteger
                                                                              n'
                                                                              d))
                                                                        (multiplyInteger
                                                                           n
                                                                           d')) ]) ])
                                                   , (\ds ds ->
                                                        case
                                                          ds
                                                          [ (\n d ->
                                                               case
                                                                 ds
                                                                 [ (\n' d' ->
                                                                      lessThanInteger
                                                                        (multiplyInteger
                                                                           n
                                                                           d')
                                                                        (multiplyInteger
                                                                           n'
                                                                           d)) ]) ])
                                                   , (\ds ds ->
                                                        case
                                                          ds
                                                          [ (\n d ->
                                                               case
                                                                 ds
                                                                 [ (\n' d' ->
                                                                      lessThanEqualsInteger
                                                                        (multiplyInteger
                                                                           n
                                                                           d')
                                                                        (multiplyInteger
                                                                           n'
                                                                           d)) ]) ])
                                                   , (\ds ds ->
                                                        case
                                                          ds
                                                          [ (\n d ->
                                                               case
                                                                 ds
                                                                 [ (\n' d' ->
                                                                      case
                                                                        (lessThanEqualsInteger
                                                                           (multiplyInteger
                                                                              n
                                                                              d')
                                                                           (multiplyInteger
                                                                              n'
                                                                              d))
                                                                        [ True
                                                                        , False ]) ]) ])
                                                   , (\ds ds ->
                                                        case
                                                          ds
                                                          [ (\n d ->
                                                               case
                                                                 ds
                                                                 [ (\n' d' ->
                                                                      case
                                                                        (lessThanInteger
                                                                           (multiplyInteger
                                                                              n
                                                                              d')
                                                                           (multiplyInteger
                                                                              n'
                                                                              d))
                                                                        [ True
                                                                        , False ]) ]) ])
                                                   , (\x y ->
                                                        case
                                                          x
                                                          [ (\ipv ipv ->
                                                               case
                                                                 y
                                                                 [ (\ipv ipv ->
                                                                      case
                                                                        (lessThanEqualsInteger
                                                                           (multiplyInteger
                                                                              ipv
                                                                              ipv)
                                                                           (multiplyInteger
                                                                              ipv
                                                                              ipv))
                                                                        [ x
                                                                        , y ]) ]) ])
                                                   , (\x y ->
                                                        case
                                                          x
                                                          [ (\ipv ipv ->
                                                               case
                                                                 y
                                                                 [ (\ipv ipv ->
                                                                      case
                                                                        (lessThanEqualsInteger
                                                                           (multiplyInteger
                                                                              ipv
                                                                              ipv)
                                                                           (multiplyInteger
                                                                              ipv
                                                                              ipv))
                                                                        [ y
                                                                        , x ]) ]) ]) ])
                                              , preds
                                              , ((\bl ->
                                                    (\bl' ->
                                                       case
                                                         (force nullList
                                                            (force tailList
                                                               bl'))
                                                         [ (\ds -> error)
                                                         , (\ds ->
                                                              unsafeRatio
                                                                (unIData
                                                                   (force
                                                                      headList
                                                                      bl))
                                                                (unIData
                                                                   (force
                                                                      headList
                                                                      bl'))) ]
                                                         (constr 0 []))
                                                      (force tailList bl))
                                                   (unListData eta)) ])
                                           [validatePreds]) ])
                               (\ds ->
                                  case
                                    ds
                                    [ (\eta -> force nullList eta)
                                    , (\paramValueHd
                                        paramValueTl
                                        actualValueData ->
                                         case
                                           (validateParamValue
                                              paramValueHd
                                              (force headList actualValueData))
                                           [ False
                                           , (validateParamValues
                                                paramValueTl
                                                (force tailList
                                                   actualValueData)) ]) ]))))))
              ((\s -> s s)
                 (\s n d ->
                    case
                      (equalsInteger 0 d)
                      [ (case
                           (lessThanInteger d 0)
                           [ ((\gcd' ->
                                 constr 0
                                   [ (quotientInteger n gcd')
                                   , (quotientInteger d gcd') ])
                                (euclid n d))
                           , ((\x -> s s x)
                                (subtractInteger 0 n)
                                (subtractInteger 0 d)) ])
                      , error ])))
           ((\s -> s s)
              (\s x y ->
                 case
                   (equalsInteger 0 y)
                   [(case (constr 0 [s, y, (modInteger x y)]) [s]), x])))
        (\`$dOrd` ds ds ->
           (\s -> s s)
             (\s ds ->
                case
                  ds
                  [ True
                  , (\x xs ->
                       case
                         x
                         [ (\predKey expectedPredValues ->
                              (\meaning ->
                                 (\s -> s s)
                                   (\s ds ->
                                      case
                                        ds
                                        [ (s s xs)
                                        , (\x xs ->
                                             case
                                               (meaning x ds)
                                               [False, (s s xs)]) ])
                                   expectedPredValues)
                                (case
                                   predKey
                                   [ (case `$dOrd` [(\v v v v v v v v -> v)])
                                   , (case `$dOrd` [(\v v v v v v v v -> v)])
                                   , (\x y ->
                                        case
                                          (case
                                             `$dOrd`
                                             [(\v v v v v v v v -> v)]
                                             x
                                             y)
                                          [True, False]) ])) ]) ])
             ds))
     (\eta eta ->
        case
          (equalsInteger eta eta)
          [ (case
               (lessThanEqualsInteger eta eta)
               [(constr 1 []), (constr 2 [])])
          , (constr 0 []) ]))