[#01-preface]
= Preface

This book teaches you how to write reliable smart contracts with Plutus, the
new general purpose language developed by IOHK for smart contracts on the blockchain.

This book aims to educate beginner Haskell developers in the fundamentals of
Plutus. It is the first book written about Plutus and uses real life samples to
help anchor the application of this new and exciting smart contract language to
tangible use cases. This book will be continuously updated with the latest code
to ensure that the content is current and up to speed with the latest version of
Plutus.
‌
A general understanding of smart contracts would be useful to learn about and
work with Plutus, but is not essential for starting out. For general functional
programmers with blockchain domain knowledge, we recommend that you read about
and understand the basics of Haskell programming prior to reading this book.

Come and explore the world of Plutus and learn our new language through
real life scenarios and sample code snippets!

*Disclaimer:*

The Writing Reliable Smart Contracts in Plutus eBook is the property of IOHK. All content and materials have been produced by IOHK and can be reused in accordance with the Apache 2.0 license. The exercises and code samples included in this book are examples and are used as learning aids. The source files for this eBook are stored in the IOHK Plutus GitHub repository and are covered by our open source license agreement. 

