[#01-preface]
:sectnums:
= Preface

This book teaches you how to write reliable smart contracts with Plutus, the
new general purpose language developed by IOHK for smart contracts on the blockchain.

This book aims to educate beginner Haskell developers in the fundamentals of
Plutus. It is the first book written about Plutus and uses real life samples to
help anchor the application of this new and exciting smart contract language to
tangible use cases. This book will be continuously updated with the latest code
to ensure that the content is current and up to speed with the latest version of
Plutus.
‌
A general understanding of smart contracts would be useful to learn about and
work with Plutus, but is not essential for starting out. For general functional
programmers with blockchain domain knowledge, we recommend that you read about
and understand the basics of Haskell programming prior to reading this book.

Come and explore the world of Plutus and learn our new language through
real life scenarios and sample code snippets!
