[glossary#glossary]
= Glossary

Extended UTxO ::
The ledger model on which the Plutus platform is based. Extends the traditional UTxO model
with data scripts and transaction information

On-chain code ::
Code written as part of a smart contract which executes on the chain during transaction validation.

Off-chain code ::
Code written as part of a smart contract which executes off the chain, usually in a user's wallet.

Mockchain ::
A Cardano blockchain emulator which faithfully implements the Extended UTxO model.

Mock wallet ::
A wallet emulator which is used to interact with the mockchain

Plutus Core ::
A small functional programming language designed to run as on-chain code.

Plutus IR ::
An intermediate language that compiles to Plutus Core, for use as a target language for compiler writers.

Plutus Platform ::
The combined software support for writing smart contracts, including:
- libraries for writing off-chain code in Haskell.
- libraries for writing on-chain code in Plutus Tx.
- emulator support for testing smart contracts.

Plutus Tx ::
A subset of Haskell which is compiled into Plutus Core.

Non-fungible Token ::
A token that is not interchangeable with other tokens.

Contract Endpoints ::
Off-chain functions used by a wallet to interact with a smart contract.
