= Smart Contracts

Traditional contracts are legally-binding agreements concerning loans, sales,
tenancy, etc. Smart contracts seek to eliminate
this element of "agreement" from the concept of a contract, replacing it with a
software-ensured guarantee that no parties involved are able to sabotage the contract
through negligence or nefarious action.
This is achieved is by
forgoing relying on the actions of an individual, company, or government in favour of
relying on the execution of a (smart contract)
program to control the transfer of funds between a contract's participants,
immortalizing both the program and its outcome on the ledger on the blockchain.

From the smart contract author's perspective, the blockchain is a distributed
bookkeeping system. The ledger on the blockchain is a record that keeps track of
who owns how much of a virtual resource
(Bitcoin, Ada, etc.) and when assets are transferred from one entity to
another. The owners of digital assets are identified by their public keys, and
they may be people or machines.

On the Cardano blockchain, the smart contract programs that run on the blockchain are written
in a language called Plutus Core. However, smart contract authors do not write
Plutus Core directly. The Plutus Platform (discussed in the next chapter) is a
software development kit to enable smart contract authors to easily write smart
contracts, including the logic that will eventually be run on the blockchain as
Plutus Core.
We now give some heuristics, considerations and limitations of smart contracts
as a concept, as well as discuss an exhaustive classification of financial
contract use cases known as ACTUS.
We will explain the specific pieces of software and the roles that they play building, compiling
and executing a smart contract in the next chapter.

== The Power of the Smart Contract

Let us begin by discussing in broad terms what a smart contract is able to do. The
goal in building the Plutus smart contract platform is to be able to model the
broadest possible range of types of contracts, so we aim to make it as
versatile as possible.
A smart contract is, however, just a program whose
behaviour is completely deterministic, and it cannot compel a
participant to behave in a certain way, either through the legal system or with
other means of enforcement. Neither is a smart contract a legally-binding
document signed by the participants.

The power of a smart contract lies in
its ability to serve as a trusted entity to which all other actors can transfer some of their
assets, as required to participate in a contract. In the way a smart contract's
execution is carried out,
participants can only ever contribute money or other tokens to
this program directly rather than to other participants, thus denying them
the opportunity to misuse the funds and violate the agreement represented by
the contract.

The resources then get
redistributed according to the rules of the contract, but are never
locked in possession of the contract for an indefinite amount of time.
This property of never locking in participants' money indefinitely is a key
feature of any well-designed smart contract, and we will see
how this is guaranteed in the designs of some of out Plutus smart contract
examples in the upcoming chapters. Frequently, at timeout time set by the
author, all the funds contributed to a contract get refunded, however,
there are possible other options of what happens at timeout, depending on
the state of a contract.

Additionally, the code of the contract program is available to all participant
entering a contract, thus enabling them to make an informed decision about whether
to participate in it. These are some of the ways smart contracts
ensure that it is very difficult for human actors to perform dishonest actions.

Using this idea of a trusted program being in charge of tokens involved
in a contract as a basis for ensuring predictable outcomes, it is easy to envision a
variety of use cases for applying this paradigm to existing problems.
The purpose and the functionality of smart contracts is best illustrated by an
example, which we will continue working with throughout this book. Let us consider a
crowdfunding campaign. This type of resource transfer schedule can be interpreted
as a smart contract program.

The overall scheme for any basic crowd funder is usually the same.
The participants are able to contribute
to the cause in the hopes that the total money raised by a certain date is more than the
minimum amount set by the entity offering the crowd-funded product.
If enough money is raised, the product gets made and sent out to those
who contributed. If not, no product is built and all of the money is
refunded to the contributors.

Here, we can immediately make note of the role of agreement in the functionality of
the crowd funder. The purpose of this type of contract is that the entity
running the campaign must agree
that it will provide the contributors with the product in the case the goal
amount was reached, and refund the contributed money otherwise.
With a smart contract, this is possible to enforce.

The execution of some part of a crowdfunding smart contract, like all
smart contracts, is generally triggered by events of two types: the passage of time
and the actions of the participants involved, and only in the case that any relevant
preconditions in the contract also hold true. In Chapter
<<_lifecycle_of_a_plutus_contract>>,
we discuss the specifics of Plutus event triggers in detail.

== Real-world and Non Fungible Tokens

While we can enforce the correct transfer of funds between participants in a
contract by simply executing it on the
blockchain, contending with real-world items as tokens in a smart contract is somewhat
trickier. It is important to inform the reader of these types of challenges
before diving into the technical explanations of Plutus functionality.

There are two most popular options for dealing with items that must transfer
ownership in real life, especially ones that do not have ownership papers
associated with them (such as most small-scale items, e.g. cats, furniture, etc.).

=== Trusted Third Party

The first one is having a trusted third party witness confirm that the
item in question has indeed reached the intended recipient.
This party is expected to be privy of the true fate
of the item, and is trusted by both the original owner and the intended
new owner. This introduces an element of trust into the execution of a contract,
which is exactly the thing that blockchain technology is meant to eliminate
the need for. In this case, though, the trust will be confined to a disinterested
party that is agreed upon by both other parties off-line.
What must occur
as part of the implementation of this type of solution is:

* The party sending the object, the receiving party, and the trusted
third party each make a choice:
- either they believe the object was received by the intended recipient,
- or that it did not
* At least two out of three make the choice to confirm the reception
of the token
* The contract executes the branch of its code corresponding with the
successful item transfer

The reason that only two out of three parties are required to agree is that
if the original owner and the recipient disagree on whether the item has
successfully changed hands, the trusted third party is there to resolve the
disagreement by casting its vote.

This scheme
can be useful in implementing, for example, an escrow contract (we will see
a smart contract example of this using Plutus in the upcoming chapters).
In the case that the third party confirms the successful reception of
the item in escrow, the seller of the item gets the money. If the
reception was not confirmed by the third party, the money in the escrow contract
gets refunded. Note that if both the buyer and the seller confirm the
receipt of the item by the buyer, and the trusted third party does not,
the escrow money will still be allocated to the seller, but there is something
fishy going on with the "trusted" party.

A trusted third party scheme could also
be useful in confirming that all the contributors to a crowdfunding campaign
have received the funded product.
In this case, the successful transfer branch would be
releasing the funds to the seller of the item in escrow.
However, this would be rather difficult
in reality - would this trusted party have to travel around confirming that
the correct and non-defective item was delivered to every intended recipient?
Would we need more than one trusted third party? How does these get selected?
This situation may require a more creative token tracking solution, or
be integrated with a true contract that can result in legal consequences for
failing to distribute the crowdfunding item.

Now, in the case that one of the
contributors did not receive the item they funded, the creator of the
contract would be faced with a decision. One option would be to
issue refunds to everyone if one person did not receive their item, and another
would be to issue a refund to everyone. This choice depends on the purpose of
the contract, the real-world situation it must accommodate, the creator's
preference, etc.

Recall that one of the important features
of a smart contract is that money put into it never gets locked in. So,
if the author of the contract chooses to wait a predetermined amount of time
for the trusted third party or parties to confirm all the transfers, after that time passes,
every contributor necessarily gets a refund. It could be possible (and is on
the Plutus platform, in particular) to choose
another re-distribution of the funds locked in the contract upon timeout.
However, a full
refund for every participant upon failure of some party to fulfill their
expected duty to the contract within a given timeframe (thus impeding the
execution of the contract) is often a most natural choice.


=== Non Fungible Tokens on the Blockchain

Another solution is to make use of non fungible tokens on the blockchain.
Non fungible tokens are tokens whose value is not tied directly to the value
of a specific currency (in our case, ADA). One of the many possible examples
of such tokens would be coffee. Even a specific type of coffee, roasted to
aromatic perfection, is
not guaranteed to have the same price at different times, or from different
sellers. Its price will habitually fluctuate due to supply and demand changes.
These types of tokens are not automatically interchangeable with each other or
a set amount of money. With the sale or exchange of each such token, a price
(or, in the case of exchange, another non fungible token) must be agreed
upon by both parties.

These types of tokens can be tracked on a blockchain by a unique ID, that
would be associated with an address, and thus its owner, similar to a
regular ownership document.

== Loans

Items existing in the real world and not solely on the blockchain are not the
only problem that presents itself in the effort to build the broadest range
of smart contracts. Loans are another type of contract where the element of
trust is hard to replace without resorting to the threat of legal action.

A loan, by its very nature, is a contract where a party promises to pay (in the
future) money that it does not currently have. One solution to this problem
is again to rely on a third party. This time, the contract relies on this
party for providing the loan money ahead of time. This is not exactly a
perfectly sensible solution, partially defeating the purpose of the loan -
if there is a party willing to risk the full value of the loan (interest
included), and is not benefitting from the contract, why is this loan even
necessary?

There is another approach to making loans into smart contracts as well.

== ACTUS
