[#09-extended]
= Extended UTXO Model

This chapter is geared towards the reader that wants to have a clearer picture
of how the Plutus architecture uses the blockchain ledger as part of
the smart contract functionality it provides (or, more specifically,
the mockchain).
Here we present a high-level explanation of the extended
UTXO model and introduce the reader into the idea of using scripts as
tools for making smart contracts on the blockchain. In this chapter,
we use and build on concepts and notation from the <<03-UTXO#03-UTXO>> chapter.

In the basic UTXO model, the scheme for authorizing transactions
is reliable, but somewhat basic. It is also limited to strictly Ada accounting.
The extended UTXO model brings a significant portion of the expressiveness of
Ethereum’s account-based scripting model to the UTXO-based Cardano blockchain,
including smart contract support.
The extension has the following components:

. An extension to the data carried by
transactions and the corresponding processing scheme performed by the nodes
. An extension to the data stored on the chain UTXO
. An
extension to the wallet backend to facilitate off-chain code that coordinates
the execution of on-chain computations.
- Note that an extended UTXO wallet must have access to ledger data in
order to be able to watch (or to look up) outputs at specified addresses
at any time.

In this chapter, we focus on the first two components.
In the extended UTXO model, additional on-chain computations must be done to
validate a transaction, and in this chapter we only discuss those additional
EUTXO computations that are relevant to Plutus functionality.
Currently, the Shelley ledger UTXO state update
rule essentially consists of two steps (both of which are, of course, computations
performed by nodes, and are on-chain):

. Check that a transaction is valid, which includes verifying the following:
* it is live (the transactions time to live has not passed yet)
* the Ada values being spent are non-negative
* generalized accounting property holds
* the size of the transaction does not exceed the maximum
* the fee is being paid
* etc.

. Check that the every action the transaction is performing is witnessed
by the holder of the appropriate private key for
* the spending of every output (witnessed by the key holder for the address
from which the funds are being spent)
* claiming of rewards (witnessed by the holder of the staking key for
the reward address)
* the application of every certificate (witnessed by certificate author)
* genesis key delegations

For a detailed formal description of
this type of accounting, we refer the reader again to <<endmatter#deleg>>.
A major way to extend the functionality of the Cardano ledger is by adding
script capability to the second step.

== Scripts

Recall from the <<10-PlutusTx#10-PlutusTx>> chapter that
scripts (specifically, Plutus scripts) are Plutus Core expressions carried by
a transaction (or stored on the ledger). They are defined inside a specially-delimited
sections of a Haskell program, called Plutus Tx, which are then compiled into
Plutus Core.

Scripts are a way to add smart contract functionality
to the extended UTXO model. The code inside Plutus scripts defines the
contract functionality.
Many of the subsequent chapters of this book discuss building scripts
that define specific smart contracts. In this section, however,
we discuss in general how the EUTXO model enforces the functionality defined
by the contracts in the scripts.
For a draft of the formal specification of the extended UTXO model with
scripts, see <<endmatter#scripts>>.

The purpose of witnessing is to verify
that the wallet spending the output has the private key associated with the address
in the corresponding UTXO entry (i.e. the address from which it is spending the
money) by checking that it was indeed signed (witnessed)
by that key.
Scripts, like witnesses, are another
tool to ensure a transaction is spending only outputs it is authorized to.

A script to which it
is possible to pay has its own address in the UTXO, and it is the hash of this script.
Only spending from these _script addresses_ can be controlled by the script (whose
address this is). Let us look at a very small example that omits some of the
details, but gives the reader an idea of the kind of thing scripts can do.
Suppose the owner of (non-script) address `a` has promised to pay `x` Ada
to the first person to guess a word they are thinking of.
This is a kind of contract, and we can interpret it as a smart contract by
considering exactly how it controls the transfer of funds. This process
always starts with a contribution of funds to the contract.

Recall that in the classic model, UTXO entries are of the form
`(txid, ix) |-> (a,c)`. The pair `(a,c)` has type `TxOut` and is called an output,
where `a` is the address of the owner of the funds
(the paying or staking public key, usually), and `c` is the value of Ada in the output.

Roughly, we expect the owner of `a` to pay to the contract `c` Ada, which can
only be spent if the correct word guess is provided by the participant.
We also notice here that the secret word cannot be stored in plain text on
the blockchain, so we must only ever expose the hash of this word.
So, the contract we want should take a hashed secret word and a plain text
word guess provided by a participant, and allow him to spend the Ada `c`
locked at the contract address if the guess is correct.
To express this, we write in `PlutusTx` the following contract,
representing the condition under which the transfer of funds can take place:

----
s = "given the hash hs of a secret word, and a word guess wg,
check that wg hashes to hs"
----

The contract is created when the owner of `a` pays to this script (i.e. to the
address `hash s`) `c` Ada. So, he produces a transaction that contains some inputs spending
UTXO entries with `a` in the address field, and an output

----
ix |-> (hash s, c, hs)
----

Note that the hash of the secret word `hs` is a separate piece of data in the
output - we will explain
why in more detail when we give the validator-redeemer-data script model overview.
Once this transaction is processed, we will have the following entry in the UTXO:

----
(txid, ix) |-> (hash s, c, hs)
----

In the classic model, the inputs of a transaction are simply references to
the UTXO entries which the transaction is spending, so they are
of the form `(txid, ix)` - just like the keys of the UTXO finite map. In the
extended model, we have a bit more data in the inputs for Plutus functionality.
This `(txid, ix)`-key output can then be spent by a wallet that can provide the
word `wg` that hashes to `hs`. So, it can
be spent by a transaction containing an input which spends the output
corresponding to `(txid, ix)` and also carries the correct guess `wg`, so the
input data is,

----
(txid, ix, wg)
----

At a node processing this transaction, then, the computation applying
the check in the script `s` to the hashed word script `hs` and the plain
text word guess `wg` is performed that compares the hashes. The transaction
is not validated if they are different, because the guess is wrong and
the participant trying to collect the `c` Ada from this script is not allowed
to do so.

In this example, we see how an output can belong to a script (i.e. be locked by
a script), and how a smart contract really is a _program_ run to determine if someone
is allowed to spend certain funds under its control. This is all we mean
when we say "control the transfer of funds".

Note that role of a script is not to generate additional inputs or outputs in
the current UTXO or transaction (or make new transactions). Scripts are only used to
verify that if a given transaction is consuming an unspent
output, it is allowed to do so. This script locking approach is only
relevant to those outputs in the UTXO which are associated with a script
address, meaning that these outputs
belong to a script.

Let us not forget transaction fees here - the wallet is expected to compute the
fees and either add them to the inputs, or
subtract them to the outputs if possible.
Note that even with the addition of scripts into transaction data,
the fee can always be pre-computed
and paid in full, since a script-carrying transaction comes with all
the inputs, outputs, and other data that is needed to validate it. Thus,
there is never a problem of a transaction fee being insufficient.

As we just saw in the mini example above, several pieces of data
go into authorizing the spending of an output locked by
a script. This includes
the validator script, redeemer script, data script, and some of the transaction
data. These are very important features of Plutus and are the
tools that make it possible to perform contract state-dependent validation.

== Validator, Redeemer, and Data Scripts

A a term of type `Script` is a Plutus Core expression.
Validator scripts are Plutus Core functions that take several input
arguments (which are also scripts). Let us now look at the function of validator
scripts and their arguments on the blockchain, then we will explain how our
small example in the previous section fits into this model.

. Validator script
* Carried by a transaction spending funds from a script address
* Defines the _logic_ or _rules_ of a contract
* Not stored in full in the ledger UTXO
- only the hash is stored as the address of
the output to which the carrying transaction pays
* Is a function taking the following 3 types of scripts as parameters
- data script
- redeemer script
- transaction and ledger data
* returns a boolean, `False` if validation fails, `True` otherwise

. Data script
* Carried by a transaction which is paying to a script
* Defines the state of a given smart contract
* Stored in full in the UTXO
- each output belonging to a (validator) script address must have an associated data script

[start=3]
. Redeemer script
* Carried by a transaction which is spending funds from a script address
* A piece of information the wallet must provide in order for a
transaction to spend from a
script address
- can be thought of as an action the participant wants to take
* Value is never stored on-chain, and only appears as part of transaction data

Another argument that the validator data script takes which is put
together out of transaction and ledger data,

[start=4]
. A `PendingTx` value.
* Contains information about the current transaction
- inputs and outputs
- validity interval, etc.



Let us now consider how our example above conforms to this validator-data-redeemer
script model. The parts of the contract we saw above, `s`, `hs`, and `wg`, are
defined in `PlutusTx`, and are compiled into `Plutus Core` scripts. The

* The _validator_ script is `s`
* The _data_ script is `hs`
* The _redeemer_ script is `wg`

Then, the funds can be spent when

----
s hs wg
----

evaluates to `True`. The `PendingTx` value is not used in this example, but
we could have extended the contract logic to only allow a transaction to
spend the funds under the additional condition that it is doing so after
after a certain slot. This `currentSlot` data would be passed via `PendingTx`.

The address of the funds locked by the contract is always the _validator script
hash_. In this case, we could have included the hashed secret word directly
in the validator. Making it part of the data script (state) of the contract
makes the same validator usable for multiple word games (this is not the case
for most other more complex contracts). The use of the
redeemer, however, is inevitable here. It has to come from a participant,
and represents the act of guessing the secret word.

We just saw the the extension to the UTxO and transaction data necessary
to accommodate Plutus, and the different types of scripts used.
Now we would like to recap the process of paying and spending to and from
a script to solidify the reader's understand of the process:

. Paying to a script address
* Transaction contains an output `o` where the address in it is the hash of the
validator script
- this hash is computed off-chain by the wallet
* `o` also contains the corresponding data script
* `o` becomes a value in the ledger UTXO once the carrying transaction is processed
* No validation occurs for paying to a script
- The redeemer is not part of this payment process

. Spending from a script address
* Transaction contains an input `i` which
- references the output in the UTXO it is spending
- carries the full validator and redeemer scripts
* The UTXO entry which `i` references is a script address, and thus has a
data script stored in the output
- the validator script `i` provides hashes to this script address
* Validation is done at this point for the spending of the specific output
`i` references
- we have the validator, redeemer and data script all available
- if it succeeds, the transaction is allowed to spend the UTXO output `i` references
- validation is performed on-chain

If the validation computation returns true for a specific script-address UTXO
entry, the validation process proceeds.
Otherwise, the entire transaction is scrapped. Essentially, given the context
of the ledger state and carrying transaction data,
the validator is used to show that the provided action (redeemer), is allowed
to be performed given the current contract state (data script).
In other words, the smart
contract functionality defined by the code in the validator allows the spending
of script-owned output funds by the carrying transaction.
Note that,
in the spirit of UTXO style accounting, the contract state is never updated in
the UTXO entry. One can only spend that entry, and create a new one with a
different data script.

There is one more piece to the validator-redeemer-data script puzzle that
we have not discussed yet: the sealing mechanism. Its
purpose is to add functionality to the script model, but
implementation places different requirements on the type of the redeemer script as
a consequence. We will see how to build redeemer scripts that conform to
these in the upcoming chapters discussing concrete examples such as
state machines, see Chapter <<auction#auction>>.

.The Seal Mechanism
[NOTE]
====

Having access to the data scripts of a script address a transaction
is paying _to_ for the purposes of validation significantly expands the expressivity
of the validator-redeemer-data script model for locking outputs.
This additional functionality is useful when two or more contracts
interact, where both contracts have some resources that they need to control
across a chain of transactions.

In such cases, the types of the data scripts
associated with a script address to which a transaction is paying
are arbitrary and not necessarily known ahead of time. This does not impact
typing transaction data itself, as they will all still have type `DataScript`,
but without knowing the underlying Plutus Core types of these terms,
adding such functionality creates a typing
challenge for performing Plutus Core computations in the validation process.

Suppose there is a UTXO entry on the ledger with the validator script hash
address `v1`, and the associated data script `ds1`. If a transaction `t` is
trying to spend this entry and move the funds to an address `v2` of a
different validator script, but produce multiple outputs for this,
locked with different data scripts. For example, it wants to create two outputs
in the UTXO with data scripts `v2_ds1` and `v2_ds2` (at the address `v2`).

Now, in order to spend the funds at script address `v1`, our transaction `t` must
provide the validator that hashes to `v1`, along with the redeemer. Suppose
we want the validation result to depend on the contents of
the data scripts of the script outputs to which a transaction is paying (as well as
likely their script address as well).

In our example, this means that whether `t` is validated or not will depend
on `v2_ds1` and `v2_ds2`.
The validator which hashes to `v1` cannot know ahead of time the real types of the
Plutus Core terms hiding inside the two data scripts, since `v1` was defined
prior to `v2_ds1` and `v2_ds2` being defined. Thus, we must find
a way to have access to these during validation without being explicit about their
types anywhere in the code of the validator (which hashes to `v1`).

Now, the data script at `v1` is predefined and does not know anything about the
types of `v2_ds1` and `v2_ds2` either. The `PendingTx` argument has a set type
as well. The redeemer `r1`, however, is a piece of Plutus Core code we can work
with to navigate this typing issue. It is carried by `t`, which is built
by off-chain code in a wallet. As part of building `t`, this off-chain code
defines both the redeemer `r1`
for the validator with script address `v1` and also the data scripts
`v2_ds1` and `v2_ds2` for script address `v2`. So this code _can_ have access to
the information about the data scripts' types.

Let us see how we can make use of these unpredictably typed scripts in the
`runScript` validation by defining the redeemer in a special way.
Recall that `runScript` has an argument of type `DataScripts`. This
is how the data scripts are passed, `v2_ds1` and `v2_ds2` in our example.
The function `runScript` _seals_ these data scripts using

----
newtype Sealer = Sealer (forall a . a -> DataScriptHash -> Sealed (HashedDataScript a))
----

For the moment, ignore the hashing of the data script - we will elabourate
on this below.
The resulting terms are then
passed to the redeemer script `r1`, which in our example would have the
underlying type

----
Sealed (HashedDataScript t1) -> Sealed (HashedDataScript t2) -> r
----

Here, `t1` and `t2` correspond to the underlying types of `v2_ds1` and `v2_ds2`.
So, this `Sealer` type wrapper is actually never unwrapped, but instead compiled
directly into a term of the underlying type of the Plutus Core expression.
The redeemer is defined to have the type above by the same wallet that also
defined `v2_ds1` and `v2_ds2`, so it is aware of `t1` and `t2`. The redeemer
is also defined to be in charge of performing
any relevant computations involving the two data scripts. In most
simpler contract examples, the redeemer simply throws them away because
the data scripts of the script address
the funds are being paid to are irrelevant during validation for the purposes
of the contract.

We do not actually pass the two argument function `r1` directly to the
validator - the types would not make sense. Instead, we apply this function
to the sealed data scripts, and pass an argument of type `r` (i.e. the
type of an `appliedRedeemer`) to the validator `v1` instead. This type `r` is
fixed when the validator `v1` is defined, but we have the freedom to choose
the (necessarily `Sealed`) hashed data script argument types of the full redeemer.
Next, the following computation is performed as part of the validation, which
is done inside `runScript`. It is the centerpiece of the script validation model,
where the validator is applied to the (applied) redeemer, data script, and `PendingTx`,

----
((v1 `applyScript` ds1) `applyScript` appliedRedeemer) `applyScript` valData
----

Because the redeemer `r1` is untrusted, but we rely on it to compute with
or simply forward the data inside `v2_ds1` and `v2_ds2` to the validator `v1`,
we have a problem.
This is where the `HashedDataScript` comes in. The hash of a data script
is part of the sealed value, and the data scripts themselves are part of the transaction
data of `t`. So, the validator
can check (by comparing hashes) that it is being passed the sealed values that do indeed correspond
to the data scripts in the outputs of `t`, and the redeemer did not swap them.

====


Note that with this model, as with the classic UTXO
model, a transaction which was not validated does not incur fees. Unlike
the classic model, however, the extended model allows for spending from script
addresses that do not belong to the wallet that generated the transaction.
This is because instead of a private key, a validator script must be
provided to spend from such an address, and scripts are publicly available.

The reader will also note later on, as we discuss writing a complete Plutus contract,
the off-chain function that returns a PlutusTx validator script takes a parameter.
This parameter is of a different type for each kind of contract. For example,
it will be a term of type `Campaign` for a crowdfunder contract:

`contributionScript {two-colons} Campaign -> ValidatorScript`

This parameter for any kind of contract is a
data structure containing necessary non-state, immutable data about the contract
(e.g. the public key of the owner of the campaign).
The values passed to the validator via this data structure parameter are not only used in
defining some of the contract's functions within
the validator, but they serve to uniquely identify a specific contract (e.g. a
specific crowdfunding campaign or guessing game).
Generally, it is a good idea to define the type of this state-less contract
structure parameter in such a way that it necessarily makes the resulting
contract unique, thus making its validator-hash address unique also.
Then the user is able to, for example, pay exactly to the instance of the
crowdfunder they intended, and not accidentally end up with top hat instead of
a Plutus textbook!

== Additional Extended Model Notes

=== Sharing Plutus Code

The off-chain code, explored in detail in
the next chapter, is run by the users' wallet (or, in the Playground simulation,
the mock wallet). The main goal of the off-chain code is to generate
the correct script at the correct time and to build a transaction carrying it.

Recall that Plutus Playground is a platform where one can write on- and off-chain code
to simulate smart contract functionality on
the mockchain. All the code written in the Playground
is shared by the mock wallets during the simulation, and can be used by
any of them.
In the real Cardano blockchain environment, on- and off-chain
contract code is meant to be used by all wallets participating in the contract,
distributed over the network. This means there needs to be another reliable way
to share Plutus code. The on-chain code is hashed, and the hash is stored in the
UTXO, giving the participants a way to verify that it is indeed the right code
for the right contract. The off-chain code is simply a way to generate
scripts and transactions, which then get validated and authenticated as
part of transaction processing. Thus, it is not necessary to use the blockchain to
provide additional guarantees of its authenticity - simply sharing such code
via a reliable code repository like GitHub will suffice.

However, similar to the case of legal know-how being necessary to write and
understand legal contracts, it is up to the creators and users of a smart contract
to have sufficient understanding of Plutus code to trust the contract is doing
what they expect it to do. Cryptographic security is powerless in this case -
this is where this book comes in!

=== Rollbacks and Other Extended UTXO Model Considerations

Given that blockchain events, such as the confirmation of a transaction, can
trigger the execution of off-chain coordination code, we need to carefully
consider the implications of needing to rollback any action that depends on a
rolled back transaction. We do not give the details of this functionality here.

There are other features of the extended UTXO system that are less relevant to
a Plutus user, which we will also not explain in detail in this chapter.

=== Adding Ledger Functionality Using Scripts

In the upcoming examples in this book we walk the reader through the process
of building, testing and using Plutus contracts. For examples of work on using
scripts to add specific functionality to the UTXO ledger, we would like to
point the reader to the following documents,

* Multi-currency on the UTXO Ledger, see <<endmatter#multicur>>
- An implementation of a script-based model for different types of
currency as well as non-fungible tokens on the mockchain
* A Formal Specification of a Multi-Signature Scheme Using Scripts, see <<endmatter#multisig>>
- A formal specification of enforcing a custom witnessing policy for spending
outputs
