// This section exists to work around https://github.com/asciidoctor/asciidoctor/issues/3356
// Don't number this section
:sectnums!:
[#endmatter]
= Endmatter
:sectnums:

[glossary#glossary]
== Glossary

[[ada, Ada]]Ada ::
Currency provided by the Cardano blockchain.
Special <<custom-token>> whose <<currency-symbol>>
is the empty bytestring and does _not_ correspond to a monetary policy.

[[address, address]]Address ::
Part of a <<transaction-output>>,
determines how the <<value>> from that output can be unlocked.
There are two kinds of addresses, <<pubkey-address>>es
and <<script-address>>es.

Contract Endpoints ::
<<off-chain1,Off-chain>> functions used by a wallet to interact with the blockchain
and in particular with smart contracts.

[[currency-symbol, currency symbol]]Currency Symbol ::
A bytestring representing a custom currency (class of <<custom-token>>s).
For <<ada>>, it is the empty bytestring, for custom currencies, it is the
hash of the <<validator-script>> representing the monetary
policy that controls forging new tokens of that currency.

[[data-script, data script]]Data Script ::
Piece of <<plutus-core,Plutus Core>> code which is part of a
<<script-output>> and will be passed to the
<<validator-script>> to check the validity of a
<<script-input>>.

[[extended-utxo, Extended UTXO]]Extended UTXO ::
The ledger model on which the <<plutus-platform>> is based.
Extends the traditional <<utxo>> model
with <<data-script>> and <<tx>> information

[[fungible-token, fungible token]]Fungible Token ::
A <<custom-token>> that is interchangeable with other tokens.

[[mockchain, mockchain]]Mockchain ::
A Cardano blockchain emulator which faithfully implements the
<<extended-utxo>> model.

[[mock-wallet, mock wallet]]Mock wallet ::
A wallet emulator which is used to interact with the <<mockchain>>.

[[non-fungible-token, non-fungible token]]Non-fungible Token ::
A <<custom-token>> that is not interchangeable with other tokens.

[[off-chain1, off-chain code]]Off-chain code ::
Code written as part of a smart contract which executes off the chain, usually in a user's wallet.

[[on-chain, on-chain code]]On-chain code ::
Code written as part of a smart contract which executes on the chain during
<<tx>> validation.

[[plutus-core, Plutus Core]]Plutus Core ::
A small functional programming language designed to run as <<on-chain>>.

[[plutus-ir, Plutus IR]]Plutus IR ::
An intermediate language that compiles to <<plutus-core>>,
for use as a target language for compiler writers.

[[plutus-platform, Plutus Platform]]Plutus Platform ::
The combined software support for writing smart contracts, including:
- Libraries for writing <<off-chain1>> in Haskell.
- Libraries for writing <<on-chain>> in <<plutus-tx>>.
- Emulator support for testing smart contracts.

[[plutus-playground, Plutus Playground]]Plutus Playground ::
A browser based environment for writing and testing Plutus contracts.

[[plutus-tx, Plutus Tx]]Plutus Tx ::
A subset of Haskell which is compiled into <<plutus-core>>.

[[pubkey-address, public key address]]Public Key Address ::
Possible address type for a <<transaction-output>>.
In order to unlock funds at such an <<address>>, one has to prove owning the
corresponding private key.

[[pubkey-input, public key input]]Public Key Input ::
Type of <<transaction-input>> collecting <<value>>
from a <<pubkey-output>>.
A <<tx>> with such an input must be signed by the owner
of the corresponding private key in order to be valid.

[[pubkey-output, public key output]]Public Key Output ::
A <<transaction-output>>
which locks value at a <<pubkey-address>>:
A pair consisting of the <<pubkey-address>>
and the <<value>>.

[[redeemer-script, redeemer script]]Redeemer Script ::
Piece of <<plutus-core>> code which is part of a
<<script-input>> and used by the
<<validator-script>> to validate that input.

[[script-address, script address]]Script Address ::
Possible <<address>> type for a <<transaction-output>>:
hash of a <<validator-script>>.

[[script-input, script input]]Script Input ::
Type of <<transaction-input>> collecting <<value>>
from a <<script-output>>.
Contains a <<redeemer-script>>.

[[script-output, script output]]Script Output ::
A <<transaction-output>>
which locks value at a <<script-address>>:
a triple consisting of the <<script-address>>,
the <<value>>
and the <<data-script>>.

[[custom-token, token]]Token ::
A custom <<value>> defined by a <<currency-symbol>> and a
<<token-name>>.
Can be a <<fungible-token>>, a <<non-fungible-token>>
or mixed. <<ada>> is a special kind of token, where both
<<currency-symbol>>
and <<token-name>>
are the empty bytestring.

[[token-name, token name]]Token Name ::
Bytestring representing a <<custom-token>> (the empty bytestring in case
of <<ada>>).

[[tx, transaction]]Transaction ::
Collects <<value>> from zero or more <<transaction-input>>
and redistributes that value to zero or more <<transaction-output>>.
Can optionally forge new value.

[[transaction-input, transaction input]]Transaction Input ::
Determines from where the <<value>>
redistributed by a <<tx>> is taken.
Corresponding to the two <<transaction-output>>s,
there are two input types,
<<pubkey-input>>s and
<<script-input>>s.

[[transaction-output, transaction output]]Transaction Output ::
Determines how a <<tx>> distributes its
<<transaction-input,inputs>>. There are two types,
<<pubkey-output>>s and
<<script-output>>s.

[[unspent-transaction-output, Unspent Transaction Output]]Unspent Transaction Output ::
A <<transaction-output>> which has not yet
been collected by a <<transaction-input>>
for use in another <<tx>>.

[[utxo, UTXO]]UTXO ::
See <<unspent-transaction-output>>.

[[validator-script, validator script]]Validator Script ::
Piece of <<plutus-core>> code
used to validate whether a <<tx>> is allowed to use a
<<script-output>> as a <<transaction-input>>.

[[value, value]]Value ::
Technically a map from currency symbols to maps from token symbols to integers.
Represents a collection of Ada and <<custom-token>>s and is the "substance" being
redistributed by <<tx>>s.

[bibliography#bibliography]
== References

- [[[devtools,1]]] Plutus Team. 2019. The Plutus language implementation and
tools. https://github.com/input-output-hk/plutus.

- [[[plutuscore,2]]] Rebecca Valentine, Kenneth MacKenzie, James Chapman, Philip Wadler,
Michael Peyton Jones, and Manuel Chakravarty.
Formal Specification of the Plutus Core Language. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/plutus/tree/master/plutus-core-spec.

- [[[bitcoin,3]]] Massimo Bartoletti and Roberto Zunino. 2018. BitML: A Calculus for Bitcoin Smart
Contracts. In Proceedings of the 2018
ACM SIGSAC Conference on Computer and Communications Security (CCS ’18). ACM, 83–100.

- [[[multicur,4]]] Jann Müller and Michael Peyton Jones.
Multi-currency on the UTXO Ledger. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/plutus/tree/master/docs/multi-currency.

- [[[marlowe,5]]] (Anonymous). 2018. Marlowe: Financial Contracts on Blockchain. In Leveraging
Applications of Formal Methods, Verification
and Validation. Industrial Practice. ISoLA 2018. (LNCS), Vol. 11247.

- [[[hybrid,6]]] Joachim Zahnentferner. 2018. Chimeric Ledgers: Translating and
Unifying UTXO-based and Account-based Cryptocurrencies.
IACR Cryptology ePrint Archive 2018 (2018), 262. http://eprint.iacr.org/2018/262

- [[[deleg,7]]] Jared Corduan, Polina Vinogradova, and Matthias Gudemann.
A formal specification of the Cardano ledger. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/cardano-ledger-specs.

- [[[scripts,8]]] Kenneth MacKenzie.
An Abstract Model of UTXO-based Cryptocurrencies with Scripts, IOHK, 2019.
Available at https://github.com/input-output-hk/plutus/tree/master/extended-utxo-spec.

- [[[multisig,9]]] Jared Corduan and Matthias Gudemann.
A Formal Specification of a Multi-Signature Scheme Using Scripts. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/cardano-ledger-specs.
