// This section exists to work around https://github.com/asciidoctor/asciidoctor/issues/3356
// Don't number this section
:sectnums!:
[#endmatter]
= Endmatter
:sectnums:

[glossary#glossary]
== Glossary

Contract Endpoints ::
Off-chain functions used by a wallet to interact with a smart contract.

Extended UTxO ::
The ledger model on which the Plutus platform is based. Extends the traditional UTxO model
with data scripts and transaction information

Fungible Token ::
A token that is interchangeable with other tokens.

Mockchain ::
A Cardano blockchain emulator which faithfully implements the Extended UTxO model.

Mock wallet ::
A wallet emulator which is used to interact with the mockchain

Non-fungible Token ::
A token that is not interchangeable with other tokens.

Off-chain code ::
Code written as part of a smart contract which executes off the chain, usually in a user's wallet.

On-chain code ::
Code written as part of a smart contract which executes on the chain during transaction validation.

Plutus Core ::
A small functional programming language designed to run as on-chain code.

Plutus IR ::
An intermediate language that compiles to Plutus Core, for use as a target language for compiler writers.

Plutus Platform ::
The combined software support for writing smart contracts, including:
- libraries for writing off-chain code in Haskell.
- libraries for writing on-chain code in Plutus Tx.
- emulator support for testing smart contracts.

Plutus Playground ::
A browser based environment for writing and testing Plutus contracts.

Plutus Tx ::
A subset of Haskell which is compiled into Plutus Core.

[bibliography#bibliography]
== References

- [[[devtools,1]]] Plutus Team. 2019. The Plutus language implementation and
tools. https://github.com/input-output-hk/plutus.

- [[[plutuscore,2]]] Rebecca Valentine, Kenneth MacKenzie, James Chapman, Philip Wadler,
Michael Peyton Jones, and Manuel Chakravarty.
Formal Specification of the Plutus Core Language. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/plutus/tree/master/plutus-core-spec.

- [[[bitcoin,3]]] Massimo Bartoletti and Roberto Zunino. 2018. BitML: A Calculus for Bitcoin Smart
Contracts. In Proceedings of the 2018
ACM SIGSAC Conference on Computer and Communications Security (CCS ’18). ACM, 83–100.

- [[[multicur,4]]] Jann Müller and Michael Peyton Jones.
Multi-currency on the UTXO Ledger. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/plutus/tree/master/docs/multi-currency.

- [[[marlowe,5]]] (Anonymous). 2018. Marlowe: Financial Contracts on Blockchain. In Leveraging
Applications of Formal Methods, Verification
and Validation. Industrial Practice. ISoLA 2018. (LNCS), Vol. 11247.

- [[[hybrid,6]]] Joachim Zahnentferner. 2018. Chimeric Ledgers: Translating and
Unifying UTxO-based and Account-based Cryptocurrencies.
IACR Cryptology ePrint Archive 2018 (2018), 262. http://eprint.iacr.org/2018/262

- [[[deleg,7]]] Jared Corduan, Polina Vinogradova, and Matthias Gudemann.
A formal specification of the Cardano ledger. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/cardano-ledger-specs.

- [[[scripts,8]]] Kenneth MacKenzie.
An Abstract Model of UTXO-based Cryptocurrencies with Scripts, IOHK, 2019.
Available at https://github.com/input-output-hk/plutus/tree/master/extended-utxo-spec.

- [[[multisig,9]]] Jared Corduan and Matthias Gudemann.
A Formal Specification of a Multi-Signature Scheme Using Scripts. Technical report, IOHK, 2019.
Available at https://github.com/input-output-hk/cardano-ledger-specs.
