= Marlowe Run Architecture

*Marlowe Run* (formerly the Marlowe Dashboard) consists of a client application
written in PureScript together with the *Marlowe PAB*, a version of the *PAB*
(Plutus Application Backend) with the three *Marlowe Plutus Applications*
bundled in.

== 1. Client <-> PAB Relationship

In general, the relationship between the client and the PAB is very
straightforward:

1. The PAB includes a simple webserver that serves up the client code (a single
page app).

2. The PAB exposes an API that the client uses to activate and manage instances
of the Marlowe Plutus Applications. (These, in turn, use the PAB to create and
manage Marlowe Contracts on the blockchain; see section 2 below.)

3. The PAB exposes a proxy wallet API that the client uses to manage wallet
integration.

4. The PAB includes a websocket server. The client subscribes (and unsubscribes)
to receive updates about the wallets and Marlowe Plutus Applications that it is
interested in at any given time.

Complications arise because of the asynchronous nature of the client <-> PAB
communication. The main difficulty is that the PAB does not allow its
applications (in this case, the Marlowe Plutus Applications) to return any data
from their endpoint calls. The best we can hope for from an endpoint call to a
Marlowe Plutus Application is an HTTP OK response. But all this means is that
the request was successfully received. It does *not* mean that the action this
endpoint call was meant to trigger was successfully completed.

In practice, the only way we can find out the result of these application
endpoint calls is to wait for an update through the websocket.

Note that this restriction only applies to the endpoints of the (Marlowe) Plutus
Applications. The endpoints of the PAB itself can and do return meaningful data.
For example, the endpoint for activating an instance of a Plutus Application
returns its instance ID.

== 2. The Marlowe Plutus Applications

Marlowe Run includes three Marlowe Plutus Applications, bundled with the Marlowe
PAB. (In Plutus, these would typically be referred to as "contracts", but to
avoid confusion with Marlowe contracts - which are something quite different -
the more generic term "application" is preferred here.)

=== 2.1. The `MarloweApp` Application

The main Marlowe Plutus Application - simply called `MarloweApp` in the code -
is essentially an interpreter for the Marlowe language, implemented in Plutus.

It exposes three endpoints that can be used to "create" a Marlowe contract, to
"apply-inputs" to a contract (i.e. move that contract forward), and to "redeem"
any payments that the contract makes to a wallet. (It also exposes two further
endpoints, "auto" and "close", which are not currently used.)

To "create" a Marlowe contract, we must provide the Marlowe source code for that
contract, and also a map of roles to wallet pubKeyHashes. The `MarloweApp` will
then create the roles currency, distribute the role tokens to the specified
wallets, and create the contract's validation script on the blockchain.

Having done that, we will now have a `CurrencySymbol` for the roles currency,
and a `ValidatorHash` for the role payout validator script. These two things
together are the Marlowe contract's `MarloweParams`, which can be used to
uniquely identify that contract. In order to "apply-inputs" to a contract, or to
"redeem" any payments made by a contract, you must pass the relevant
`MarloweParams` to these other two endpoints.

As noted above, the PAB does not provide a way for Plutus Applications to return
data from their endpoint calls. But we need some way for the client to know the
result of its endpoint calls to the `MarloweApp` - we need to know if the call
was successful, and what the error was if it was not successful. This need is
served by the `MarloweApp`'s observable state (all Plutus applications have an
observable state that can be queried through the API and subscribed to through
the websocket). This observable state stores the result of the last endpoint
call.

=== 2.2. The `WalletCompanion` Application

The need to know the `MarloweParams` of any contract in order to "apply-inputs"
or "redeem" presents a problem: where are users to get this information from? If
a user is given a role token for a new contract, they will see that token in
their wallet, and from that they can deduce the `CurrencySymbol`. But there is
no such way to determine the `ValidatorHash` of the role payout validator
script.

(Note: As it happens, the hash of the role payout validator script is currently
a function of the roles currency symbol. But this might change in the future,
and so we don't rely on this fact here.)

In order to know the `ValidatorHash` of the contracts they are interested in,
users need to create a `WalletCompanion` application. This application exposes
no endpoints. It simply runs continuously, watching for any payments of role
tokens to the wallet it is tied to. When it sees such a payment, it updates its
observable state to include the `MarloweParams` for the contract in question.

The client uses the PAB's API to query the observable state of this
`WalletCompanion` application (and the websocket to remain informed of any
changes). In this way, the client can determine which contracts any wallet has a
role in, and can use the `MarloweParams` for those contracts, in conjunction
with the main `MarloweApp`, to interact with that contract.

Rather than just a list of `MarloweParams`, the `WalletCompanion` application's
observable state is a map of `MarloweParams` to `MarloweData`, where the
`MarloweData` contains the _initial_ state and continuation contract of the
contract itself. (The initial continuation contract just is the contract, of
course.) It is not essential for the `WalletCompanion` to include the initial
`MarloweData` in its observable state, since we have another way to fetch this
data using just the `MarloweParams` (see section 2.3 below). But it is
convenient, and saves us an extra round trip to the backend.

Using this `MarloweData` value - in particular the initial contract - the client
can determine what kind of contract we are dealing with. This is done by
matching up the contract with our (currently quite limited) set of contract
templates. Note, however, that this is a short-term hack that is unlikely to
work when more Marlowe contracts are made available (including contracts that
users write and upload themselves). In order to match up contracts with their
originating templates may ultimately require (something like) the metadata
server. At that point, it may be that the `MarloweData` value is no longer used
here, and could be removed from the `WalletCompanion` application's observable
state.

=== 2.3. The `MarloweFollower` Application

The `MarloweFollower` application is used to keep track of Marlowe contracts on
the blockchain. Once created, each instance of the `MarloweFollower` application
exposes a "follow" endpoint, which can be called with the `MarloweParams` of the
contract you want to follow.

When this endpoint has been called, no endpoints will be available any more. The
application then just runs continuously, watching for changes to the contract in
question, and updating its observable state accordingly. This observable state
combines the `MarloweParams` and the _initial_ `MarloweData` (i.e. the same
information that is available within the `WalletCompanion` application for each
contract) with an array of `TransactionInput`s. This array will contain the
result of all (successful) "apply-inputs" calls related to this contract.

By applying all the `TransactionInput`s to the initial state, the client can
determine the current state of the contract.

=== 2.4. Summary

To integrate a wallet with Marlowe Run, you need:

1. One `MarloweApp` application to create Marlowe contracts, apply inputs, and
redeem payments.

2. One `WalletCompanion` application to listen for payments of role tokens to
that wallet, and inform you of the `MarloweParams` for the corresponding
contract.

3. Zero or more `MarloweFollower` applications, one for each Marlowe contract
for which the wallet has a role.

The observable state of the `WalletCompanion` application needs to be kept in
line with the `MarloweFollower` applications: for each `MarloweParams` in the
`WalletCompanion`'s state, there should be exactly one corresponding
`MarloweFollower` application. It is the responsibility of the client to ensure
that this is the case. Whenever the client receives notification that the
observable state of the `WalletCompanion` application has changed, it compares
that state with the list of active `MarloweFollower` applications, and creates
new ones as necessary.

== 3. Marlowe Run in Action

This section describes what happens during a "normal" workflow, which is
designed to illustrate all the moving parts of the app.

=== 3.1. Alice Generates a Demo Wallet

1. *Alice's Client -> API* A new user, Alice, comes to the starting page and
clicks the button to generate a demo wallet. Alice's client calls the
"/wallet/create" endpoint of the PAB (which is a proxy to the "/create" endpoint
of the mock wallet API).

2. *API -> Alice's Client* The PAB creates a wallet and gives it 100,000 pretend
ada to play with, then responds with the `WalletInfo` for this wallet. The
`WalletInfo` is a record containing the wallet's ID, pubKey, and pubKeyHash.

3. *Alice's Client -> API* Alice's client then uses the PAB API to activate a
`MarloweApp` and a `WalletCompanion` for this wallet, and uses the proxy wallet
API to query the wallet's current funds. All of these data are bundled together
with a wallet nickname (initially the empty string) in a `WalletDetails` record.

=== 3.2. Alice Connects this Demo Wallet to the App

1. *Alice's Client* Alice is now presented with a form which displays the
"Wallet ID" of the wallet she just created, and a text input box for entering a
nickname for this wallet. She copies the "Wallet ID"* and saves it somewhere for
later. She gives her wallet the nickname "Alice", and clicks the button to
connect this wallet.

2. *Alice's Client* The `WalletDetails` for this wallet are saved in memory to
her `WalletLibrary`, and also saved to the browser's localStorage. This will
make it easier for her to connect this wallet again in the same browser. But to
connect in another browser or computer, she will need her "Wallet ID". Note that
the wallet nickname, "Alice", is not persisted on the server, and is now only
associated with this wallet in Alice's browser, through localStorage.

3. *Alice's Client -> API* Alice's client queries the PAB to get all of the
active applications associated with her wallet.

4. *Alice's Client -> Websocket* Alice's client subscribes to websocket updates
for the wallet's funds, the wallet's `MarloweApp` application, the wallet's
`WalletCompanion` application, and any `MarloweFollower` applications.

5. *Alice's Client* Alice's client moves into the `Dashboard` state, presenting
Alice with a view of her running contracts.

6. *Websocket -> Alice's Client* Alice's client gets initial updates from the
websocket for Alice's wallet's funds, her `MarloweApp` application, and her
`WalletCompanion` application. The only interesting one here is the
`WalletCompanion` application, which tells us the `MarloweParams` of any
contracts for which Alice has a role...

7. *Alice's Client -> API* If Alice's client finds any `MarloweParams` in the
`WalletCompanion` application's observable state for which there is no
corresponding `MarloweFollower` application, it activates a new
`MarloweFollower` and calls its "follow" endpoint with those `MarloweParams`.

8. *Alice's Client -> Websocket* Alice's client then also subscribes to the
websocket to receive updates about these new `MarloweFollower` applications.

9. *Websocket -> Alice's Client* The observable state of the new
`MarloweFollower` applications will be updated to show the state of the
corresponding contract, and the websocket will inform Alice's client. Alice's
client can then display the status of these contracts to Alice.

*A note about the "Wallet ID"*

The "Wallet ID" as displayed to the user is in fact the instance ID of the
wallet's `WalletCompanion` application, and not the actual wallet ID. This is
because we can get the wallet ID itself if we have the instance ID of the
`WalletCompanion`, but (when we started building this app) not the other way
around. Now, however, it is possible to get the `WalletCompanion` instance ID
from the wallet ID, so this should be changed; see SCP-2878.

=== 3.3. Bob Generates a Demo Wallet and Connects it to the App

Bob does the same as Alice, but calls his wallet "Bob".

Bob gives Alice his "Wallet ID".

=== 3.4. Alice Adds Bob to her Contacts

1. *Alice's Client -> API* Alice enters Bob's "Wallet ID" into the new contact
form. Alice's client looks up Bob's `CompanionContract` application using this
"Wallet ID", and uses this to find the actual wallet ID. Alice's client then
uses the actual wallet ID to lookup the complete `WalletInfo`.

2. *Alice's Client* Alice's client wraps up this `WalletInfo` in a `WalletData`
record, and saves it to localStorage. The record includes some empty fields that
there is no point in looking up - because all Alice needs to know is the
`WalletInfo`.

=== 3.5. Alice Creates a Contract Between Her and Bob

1. *Alice's Client* Alice fills out a contract template to create a full
contract. Using her locally saved contacts, she assigns roles in this contract
to both Bob and herself.

2. *Alice's Client -> API* Alice's client asks Alice's `MarloweApp` to create
the contract. The `MarloweApp` does what it needs to do, which includes creating
the roles currency and paying a role token to each of Alice's and Bob's wallets.

3. *Alice's Client -> API* Alice's client asks to activate a new placeholder
`MarloweFollower` application, ready to follow the new contract that we are
expecting to be created. The PAB replies with the instance ID of the new
`MarloweFollower` application, which Alice's client associates with the metadata
for this contract.

4. *Alice's Client -> Websocket* Alice's client subscribes to websocket
notifications about the status of this `MarloweFollower` application.

5. *Websocket -> Alice's Client* Alice's client is informed through the
websocket of a status update to the `MarloweApp`, which tells it whether the
request to create a contract was successful or not.

[TODO: This is not as it should be. Steps 3 and 4 here should happen *after*
step 5, and *only if* the status update tells us that the request to create a
contract was successful. See SCP-2879.]

=== 3.6. Alice's Dashboard is Updated

1. *Websocket -> Alice's Client* Alice receives the role token for the contract
she created, and her `WalletCompanion` application notices. Alice's client is
informed through the websocket of a status update to the `WalletCompanion`
application, and compares its observable state to the `MarloweFollower` apps
Alice has running. It finds there is a new contract that is not yet being
followed. It also finds a placeholder `MarloweFollower` application
corresponding to a contract with the right metadata (that was created at step 3
in the previous section).

2. *Alice's Client -> API* Alice's client calls the "follow" endpoint of this
placeholder `MarloweFollower` application, so that the application now starts
listening for updates to this contract.

3. *Websocket -> Alice's Client* The `MarloweFollower` application finds the
contract, and its observable state is updated to reflect the initial state of
the contract. Because Alice's client is subscribed to updates for this
application, the websocket informs it of the change, and it can now display the
state of this new contract to Alice.

=== 3.7. Bob's Dashboard is Updated

1. *Websocket -> Bob's Client* Bob receives the role token for the contract
Alice created, and his `WalletCompanion` application notices. Bob's client is
informed through the websocket of a status update to his `WalletCompanion`
application, and compares its observable state to the `MarloweFollower` apps Bob
has running. It finds there is a new contract that is not yet being followed. It
doesn't find any placeholder `MarloweFollower` application corresponding to a
contract with the right metadata (Alice had one because she created the
contract; Bob does not).

2. *Bob's Client -> API* Bob's client asks to activate a new `MarloweFollower`
application. The PAB activates one and returns its instance ID.

3. *Bob's Client -> Websocket* Bob's client subscribes to websocket
notifications about the status of this `MarloweFollower` application.

4. *Bob's Client -> API* Bob's client calls the "follow" endpoint of this new
`MarloweFollower` application, so that the application now starts listening for
updates to the contract in question.

5. *Websocket -> Bob's Client* The `MarloweFollower` application finds the
contract, and its observable state is updated to reflect the initial state of
the contract. Because Bob's client is subscribed to updates for this
application, the websocket informs it of the change, and it can now display the
state of this new contract to Bob.

=== 3.8. Alice Applies Inputs to the Contract

1. *Alice's Client -> API* Alice fills in a form and presses a button to move
the contract forward. Alice's client calls the "apply-inputs" endpoint of
Alice's `MarloweApp`.

2. *Websocket -> Alice's Client* A status update about Alice's `MarloweApp`
informs Alice's client whether the "apply-inputs" call was successful or not.

=== 3.9. Alice's Dashboard is Updated

1. *Websocket -> Alice's Client* Assuming the "apply-inputs" call was
successful, the contract will move forward, and Alice's `MarloweFollower`
application for this contract will be updated accordingly. Then the websocket
will tell Alice's client about this update, and it can display the new state of
the contract to Alice.

2. *Alice's Client -> API* Following each notification of an update to the state
of a `MarloweFollower` application, Alice's client tests to see if the contract
has made any payments to roles which Alice owns. If so, it calls the "redeem"
endpoint of Alice's `MarloweApp` application to ensure automatically that
Alice's wallet receives these payments. Note that this results in "redeem" very
likely being called more often than is necessary, since we do not attempt to
keep track of which payments have already been redeemed.

=== 3.10. Bob's Dashboard is Updated

1. *Websocket -> Bob's Client* Assuming the "apply-inputs" call was successful,
the contract will move forward, and Bob's `MarloweFollower` application for this
contract will be updated accordingly. Then the websocket will tell Bob's client
about this update, and it can display the new state of the contract to Bob.

2. *Bob's Client -> API* Following each notification of an update to the state
of a `MarloweFollower` application, Bob's client tests to see if the contract
has made any payments to roles which Bob owns. If so, it calls the "redeem"
endpoint of Bob's `MarloweApp` application to ensure automatically that Bob's
wallet receives these payments. (Note, again, that this results in "redeem" very
likely being called more often than is necessary.)
