(program
   1.1.0
   ((\s ->
       s
         s
         (constr 1
            [ True
            , (constr 1
                 [ True
                 , (constr 1
                      [ True
                      , (constr 1
                           [ True
                           , (constr 1
                                [ True
                                , (constr 1
                                     [ True
                                     , (constr 1
                                          [ True
                                          , (constr 1
                                               [ True
                                               , (constr 1
                                                    [ True
                                                    , (constr 1
                                                         [ True
                                                         , (constr 0
                                                              [  ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]))
      (\s ds -> case ds [True, (\x xs -> case x [False, (s s xs)])])))