(program
   1.1.0
   ((\s ->
       (\s ->
          case
            (s s 1000)
            [ 42
            , (\x
                xs ->
                 case
                   xs
                   [ 42
                   , (\x
                       xs ->
                        case
                          xs
                          [ 42
                          , (\x
                              xs ->
                               case
                                 xs
                                 [ 42
                                 , (\x
                                     xs ->
                                      case
                                        xs
                                        [ 42
                                        , (\x
                                            xs ->
                                             case
                                               xs
                                               [ 42
                                               , (\x
                                                   xs ->
                                                    case
                                                      xs
                                                      [ 42
                                                      , (\x
                                                          xs ->
                                                           case
                                                             xs
                                                             [ 42
                                                             , (\x
                                                                 xs ->
                                                                  case
                                                                    xs
                                                                    [ 42
                                                                    , (\x
                                                                        xs ->
                                                                         case
                                                                           xs
                                                                           [ 42
                                                                           , (\x
                                                                               xs ->
                                                                                case
                                                                                  xs
                                                                                  [ 42
                                                                                  , (\x
                                                                                      xs ->
                                                                                       case
                                                                                         xs
                                                                                         [ 42
                                                                                         , (\x
                                                                                             xs ->
                                                                                              case
                                                                                                xs
                                                                                                [ 42
                                                                                                , (\x
                                                                                                    xs ->
                                                                                                     case
                                                                                                       xs
                                                                                                       [ 42
                                                                                                       , (\x
                                                                                                           xs ->
                                                                                                            s
                                                                                                              s
                                                                                                              xs) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])
         (\s n ->
            case
              (lessThanEqualsInteger n 0)
              [ (constr 1 [1, ((\x -> s s x) (subtractInteger n 1))])
              , (constr 0 []) ]))
      (\s ds -> case ds [42, (\x xs -> s s xs)])))