(program
   1.1.0
   ((\forced
      d ->
       case
         d
         [ (\args ->
              case
                args
                [ (\hd tl ->
                     case
                       tl
                       [ (\hd tl ->
                            case
                              tl
                              [ (\hd tl ->
                                   case
                                     tl
                                     [ (\hd tl ->
                                          case
                                            tl
                                            [ (\hd tl ->
                                                 (\ds ->
                                                    (\b ->
                                                       (\ds ->
                                                          (\ds ->
                                                             (\ds ->
                                                                (\ds -> b)
                                                                  (unIData
                                                                     (forced
                                                                        tl)))
                                                               (unIData hd))
                                                            (unIData hd))
                                                         (unIData hd))
                                                      (unIData hd))
                                                   (unIData hd)) ]) ]) ]) ]) ])
         , (\args ->
              case
                args
                [ (\hd
                    tl ->
                     case
                       tl
                       [ (\hd
                           tl ->
                            case
                              tl
                              [ (\hd
                                  tl ->
                                   case
                                     tl
                                     [ (\hd
                                         tl ->
                                          case
                                            tl
                                            [ (\hd
                                                tl ->
                                                 case
                                                   tl
                                                   [ (\hd
                                                       tl ->
                                                        (\ds ->
                                                           (\ds ->
                                                              (\c ->
                                                                 (\ds ->
                                                                    (\ds ->
                                                                       (\ds ->
                                                                          addInteger
                                                                            c
                                                                            (unIData
                                                                               (forced
                                                                                  tl)))
                                                                         (unIData
                                                                            hd))
                                                                      (unIData
                                                                         hd))
                                                                   (unIData hd))
                                                                (unIData hd))
                                                             (unIData hd))
                                                          (unIData
                                                             hd)) ]) ]) ]) ]) ]) ])
         , (\args ->
              case
                args
                [ (\hd
                    tl ->
                     case
                       tl
                       [ (\hd
                           tl ->
                            case
                              tl
                              [ (\hd
                                  tl ->
                                   case
                                     tl
                                     [ (\hd
                                         tl ->
                                          case
                                            tl
                                            [ (\hd
                                                tl ->
                                                 case
                                                   tl
                                                   [ (\hd
                                                       tl ->
                                                        case
                                                          tl
                                                          [ (\hd
                                                              tl ->
                                                               case
                                                                 tl
                                                                 [ (\hd
                                                                     tl ->
                                                                      case
                                                                        tl
                                                                        [ (\hd
                                                                            tl ->
                                                                             case
                                                                               tl
                                                                               [ (\hd
                                                                                   tl ->
                                                                                    case
                                                                                      tl
                                                                                      [ (\hd
                                                                                          tl ->
                                                                                           case
                                                                                             tl
                                                                                             [ (\hd
                                                                                                 tl ->
                                                                                                  case
                                                                                                    tl
                                                                                                    [ (\hd
                                                                                                        tl ->
                                                                                                         case
                                                                                                           tl
                                                                                                           [ (\hd
                                                                                                               tl ->
                                                                                                                case
                                                                                                                  tl
                                                                                                                  [ (\hd
                                                                                                                      tl ->
                                                                                                                       (\ds ->
                                                                                                                          (\ds ->
                                                                                                                             (\ds ->
                                                                                                                                (\d ->
                                                                                                                                   (\ds ->
                                                                                                                                      (\ds ->
                                                                                                                                         (\ds ->
                                                                                                                                            (\ds ->
                                                                                                                                               (\i ->
                                                                                                                                                  (\ds ->
                                                                                                                                                     (\ds ->
                                                                                                                                                        (\ds ->
                                                                                                                                                           (\ds ->
                                                                                                                                                              (\n ->
                                                                                                                                                                 (\ds ->
                                                                                                                                                                    (\ds ->
                                                                                                                                                                       addInteger
                                                                                                                                                                         d
                                                                                                                                                                         (addInteger
                                                                                                                                                                            i
                                                                                                                                                                            n))
                                                                                                                                                                      (unIData
                                                                                                                                                                         (forced
                                                                                                                                                                            tl)))
                                                                                                                                                                   (unIData
                                                                                                                                                                      hd))
                                                                                                                                                                (unIData
                                                                                                                                                                   hd))
                                                                                                                                                             (unIData
                                                                                                                                                                hd))
                                                                                                                                                          (unIData
                                                                                                                                                             hd))
                                                                                                                                                       (unIData
                                                                                                                                                          hd))
                                                                                                                                                    (unIData
                                                                                                                                                       hd))
                                                                                                                                                 (unIData
                                                                                                                                                    hd))
                                                                                                                                              (unIData
                                                                                                                                                 hd))
                                                                                                                                           (unIData
                                                                                                                                              hd))
                                                                                                                                        (unIData
                                                                                                                                           hd))
                                                                                                                                     (unIData
                                                                                                                                        hd))
                                                                                                                                  (unIData
                                                                                                                                     hd))
                                                                                                                               (unIData
                                                                                                                                  hd))
                                                                                                                            (unIData
                                                                                                                               hd))
                                                                                                                         (unIData
                                                                                                                            hd)) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])
      (force headList)))