(program
   1.1.0
   (\d ->
      case
        (case (unConstrData d) [(\l r -> r)])
        [ (\ds
            ds ->
             case
               ds
               [ (\ds
                   ds ->
                    case
                      ds
                      [ (\ds
                          ds ->
                           case
                             ds
                             [ (\ds
                                 ds ->
                                  case
                                    ds
                                    [ (\ds
                                        ds ->
                                         case
                                           ds
                                           [ (\ds
                                               ds ->
                                                case
                                                  ds
                                                  [ (\ds
                                                      ds ->
                                                       case
                                                         ds
                                                         [ (\ds
                                                             ds ->
                                                              case
                                                                ds
                                                                [ (\ds
                                                                    ds ->
                                                                     case
                                                                       ds
                                                                       [ (\ds
                                                                           ds ->
                                                                            case
                                                                              ds
                                                                              [ (\ds
                                                                                  ds ->
                                                                                   case
                                                                                     ds
                                                                                     [ (\ds
                                                                                         ds ->
                                                                                          case
                                                                                            ds
                                                                                            [ (\ds
                                                                                                ds ->
                                                                                                 case
                                                                                                   ds
                                                                                                   [ (\ds
                                                                                                       ds ->
                                                                                                        case
                                                                                                          ds
                                                                                                          [ (\ds
                                                                                                              ds ->
                                                                                                               addInteger
                                                                                                                 (unIData
                                                                                                                    ds)
                                                                                                                 (addInteger
                                                                                                                    (unIData
                                                                                                                       ds)
                                                                                                                    (unIData
                                                                                                                       ds))) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]))