=== `plutus-wallet-api`

This package should probably be split in two!

The `ledger` sublibrary defines our model of an Extended UTXO ledger, including:

- The types that describe transactions, pending transactions, keys, currencies, etc.
- Functions that implement the ledger validation rules.

The rest of the package defines the "wallet API", which was our attempt at
defining the interface that contracts would use to the wallet. As it turns out,
we need to do things somewhat differently, and so `plutus-contract` is the
future, but the functions in here are still used fairly widely.

`Language.PlutusTx.StateMachine` defines the `StateMachine` type. State machines are an abstraction that lets you write contracts as transition functions `State -> Input -> State`, hiding some of the details of the script validation mechanism. Not all contracts can be written as state machines, but those that can are often easier to understand and test because they don't have to deal with the pending transaction directly. (The off-chain part of the state machine library lives in the `plutus-contract` package)