ci:
    cabal new-build all
    cabal new-test
    hlint src bench test
    stack build --bench --test --no-run-benchmarks --no-run-tests
    weeder .
    cabal check

docs:
    google-chrome $(fd '\.html$' -I | tail -n1) &
