[#marlowe]
= Marlowe: Financial Contracts on Cardano Computation Layer

Now that you have become comfortable with the idea of smart contracts and have
(we hope) gotten the hang of writing basic Plutus contract code, we
present a more powerful universal smart contract that can be used to model
a whole class of contracts - financial contracts. Recall, from the
<<04-smartcont#04-smartcont>> chapter, that financial contracts encompass those
contracts dealing exclusively with currency and financial products changing
ownership.

The Peyton Jones et al have created a domain-specific
language (DSL) to express every possible contract in this type, called Marlowe
(see <<bibliography#bibliography>>). Every expression in this DSL is a term
of type `Contract`, which is a Haskell data structure. This DSL is expressive
enough to build every kind of contract found in the ACTUS classification
of financial contracts (we shall see examples of building some of these later
on).

The Marlowe DSL is a tool for building smart contracts.
We would strongly suggest you read the aforementioned paper about it, and
try using the Meadow platform for testing and building Marlowe contracts at

https://input-output-hk.github.io/marlowe/

For the curious reader, the full code repositories for both Meadow and Marlowe
itself are found at

https://github.com/input-output-hk/marlowe/

Note that as a DSL, Marlowe is specifically built to have only the functionality
needed for its intended purpose, and be maximally restrict expressiveness
otherwise. In particular, Marlowe contract evaluation is guaranteed to terminate
in a finite amount of time, and the funds at a contract address are never
locked there indefinitely, so they become available to be spent (by who depends on
the contract) or redeemed by the original payer after a finite amount of time.

This chapter focuses on explaining the details of the implementation
of the Marlowe DSL in Plutus, which allows users
to make use of Marlowe functionality within the
Cardano system. We will, of course, clarify the relevant Marlowe details
along the way.
The semantics of Marlowe are changing regularly as the software takes its
final form, and at this time the Plutus implementation is not completely in sync with
the current version of Marlowe, but this does not affect the lessons
to be learned from interpreting a whole class of contracts on the Plutus
platform.

As with building any smart contract, in order to implement Marlowe, we
must interpret the language in the validator-redeemer-data script model.
It is important to note here that in Marlowe, the time unit in use is a `Block`.
However, in the Cardano system, time in measured in terms of `Slot`. A `Block`
explicitly refers to the piece of data that is produced by a slot leader,
containing transactions submitted in the preceding time slot, as well
as other information used in updating the ledger. Currently, the block creation
is done exactly once per slot, so that that timekeeping can be done in terms of
either one. In the future, however, this will not be the case, due to changes
to the Cardano consensus algorithms (see <<bibliography#bibliography>>), and
there may be none or several blocks produced in one slot.
However, in this Plutus implementation of Marlowe, all timekeeping is done
in terms of `Slot` numbers. Thus, independent of the evolution of the system,
the timekeeping in this interpretation will remain consistent with the passage
of actual time.

The approach this Marlowe implementation takes is somewhat similar to state machine
approach described in Chapter <<statemachine#statemachine>>. The idea in
is that the validator compares the following:

* the contract and state which the wallet submitting a transaction includes
in the redeemer script (i.e. the `expectedContract` and `expectedState`), and the

* the result of applying the input (which may be external data such as time,
or participant actions) to the contract and state contained in the data script
- this is called _evaluating_ the contract

The input is also provided as part of the redeemer script.
If the state and contract in both cases are the same, the contract-locked
funds may be spent. Additionally, validation of the contract and state
in the data script is performed - more on this topic in a note following the
code explanations. Once the validator approves the spending of the
contract-locked funds, the state and contract used as the data script
for the remaining or newly contributed funds must be the new state and contract
submitted in the redeemer script.

We also make the following assumptions in this Marlowe interpreter:

* The transaction fees are zero
* Every contract is created by the contract owner (and issuer of the carrying transaction)

== Marlowe Primitives and Validation

We will now dive right in to studying the code to see what a Marlowe `Contract`
looks like, and how to interpret its state. In the `Common` module, all the
primitives for building and validating a Marlowe contract are found.

include::Language/Marlowe/common.adoc[]

== Marlowe Endpoints

Next, we will discuss the endpoints to engage with a Marlowe contract, which
are in the `Client` module.

include::Language/Marlowe/client.adoc[]

== Escrow Example

Now it is time to look at how to use the Marlowe interpreter
to build some real-world contract examples. First, let us
consider an escrow contract.

include::Language/Marlowe/escrow.adoc[]

== ACTUS Examples

An main application of Marlowe is the implementation of
financial contracts. Recall that financial contracts have been classified
by the ACTUS project (see the <<04-smartcont#04-smartcont>> Chapter).
We can look at the algorithmic description of
each type and use our Marlowe interpreter to model this behaviour.
In the `Actus` module, we give an example of implementing contracts of the
the zero coupon bond type, which are part of the PAM (Principal at Maturity)
class. We include a basic, a trusted, and a guaranteed version.

include::Language/Marlowe/actus.adoc[]
