[#marlowe]
= Marlowe: Financial Contracts on Cardano Computation Layer

Now that you have become comfortable with the idea of smart contracts and have
(we hope) gotten the hang of writing basic Plutus contract code, we
present a more powerful universal smart contract that can be used to model
a whole class of contracts - financial contracts. Recall, from the
<<04-smartcont#04-smartcont>> chapter, that financial contracts encompass those
contracts dealing exclusively with currency and financial products changing
ownership.

The Peyton Jones et al have created a domain-specific
language (DSL) to express every possible contract in this type, called Marlowe
(see <<bibliography#bibliography>>). Every expression in this DSL is a term
of type `Contract`, which is a Haskell data structure. This DSL is expressive
enough to build every kind of contract found in the ACTUS classification
of financial contracts (we shall see examples of building some of these later
on).

A full introduction and tutorial is available online 

https://github.com/input-output-hk/marlowe/tree/master/docs/tutorial-v3.0
