name: Feature Request
description: Submit a feature request
#title: ""
labels: ["enhancement"]
#assignees:
#  -
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      description: A clear and detailed description of what you are suggesting.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false