name: Feature Request
description: Submit a feature request
#title: ""
labels: ["enhancement"]
#assignees:
#  -
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this enhancement.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      description: A clear and detailed description of what you are suggesting.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: additional-screenshots
    attributes:
      label: Additional context / screenshots
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
