name: Security Report
description: Report a security issue
#title: ""
labels: ["security"]
#assignees:
#  -
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and specific description of what the issue is
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Do you have a proposed solution for this issue?
      description: Describe what solutions you've considered
    validations:
      required: false
  - type: textarea
    id: system-info
    attributes:
      label: System info
      placeholder: |
        OS: [e.g. Ubuntu]
        Version: [e.g. 20.04]
        Plutus: version or commit hash
    validations:
      required: true
  - type: textarea
    id: screenshots-attachments
    attributes:
      label: Screenshots and attachments
      description: |
        If applicable, add screenshots, config files and/or logs to help explain the problem.
        If the issue is related to the Plutus Playground, please include a link to a gist that reproduces the issue
    validations:
      required: false

