name: Weakness Report
description: Report a weakness in the sense of the CWE; a potential source of vulnerabilities.
#title: ""
labels: ["weakness"]
#assignees:
#  -
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and specific description of what the weakness is.
    validations:
      required: true
  - type: checkboxes
    id: source-of-vulnerability
    attributes:
      label: Security vulnerability
      description: Would you consider this weakness a potential source of vulnerabilities?
      options:
        - label: Yes, and I will add the 'security' label to this issue.
          required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce known vulnerabilities
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
    validations:
      required: false
  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: What is the reproducible outcome?
      placeholder: Secret information is exposed on the blockchain
    validations:
      required: false
  - type: textarea
    id: proposed-solution
    attributes:
      label: Do you have a proposed solution for this weakness?
      description: What steps have you taken to try and understand the issue? Context will enable us to help you faster, or, even better, will help you solve it yourself!
    validations:
      required: true
  - type: checkboxes
    id: checked-readme
    attributes:
      label: Checked our docs?
      description: Have you looked over our [readme](https://github.com/input-output-hk/plutus-apps/blob/main/README.adoc), [documentation](https://plutus-apps.readthedocs.io/en/latest/), and [technical report](https://github.com/input-output-hk/plutus-apps/blob/main/README.adoc#specifications-and-design)?
      options:
        - label: Yes, I have looked in the the readme, plutus docs, and technical report for help on this issue.
          required: true
  - type: checkboxes
    id: checked-stackexchange
    attributes:
      label: Checked Stack Exchange?
      description: Have you tried searching on [cardano stackexchange](https://cardano.stackexchange.com/)?
      options:
        - label: Yes, I have searched Stack Exchange for this issue and it doesn't exist.
          required: true
        - label: I have considered raising this issue in Stack Exchange.
          required: true
  - type: textarea
    id: system-info
    attributes:
      label: System info
      placeholder: |
        OS: [e.g. Ubuntu]
        Version: [e.g. 20.04]
        Plutus: version or commit hash
    validations:
      required: true
  - type: textarea
    id: screenshots-attachments
    attributes:
      label: Screenshots and attachments
      description: |
        If applicable, add screenshots, config files and/or logs to help explain the problem.
        If the issue is related to the Plutus Playground, please include a link to a gist that reproduces the issue
    validations:
      required: false

