name: Run Linkchecker

description: |
  Run linkchecker on a URL or a list of files.
  This only checks external links.

inputs:
  target-url:
    default: ""
    description: | 
      Target url to check for external broken links.
      Either this or target-url must be non-empty, not both.

  target-files: 
    default: ""
    description: |
      String of space-separated target filepath patterns.
      Each pattern will be fed to find using the -name directive.
      URLs beginning with "https?" will be regex-matched and extracted from each file.
      Either this or target-url must be non-empty, not both.

  ignore-urls:
    default: ""
    description: |
      String of space-separated URL patterns to ignore.
      Each URL is fed to linkchecker using the --ignore-url option.

runs:
  using: "composite"
  steps:
    - name: Check Valid Inputs 
      if: ${{ inputs.target-url == "" && inputs.target-files == "" || inputs.target-url != "" && inputs.target-files != ""}}
      run: 
        echo "Provide a value for either target-url xor target-files."
        exit 1 

    - name: Checkout Repo
      if: ${{ inputs.target-url != "" }}
      uses: actions/checkout@main

    - name: Check URL
      if: ${{ inputs.target-url != "" }}
      run: | 
        linkchecker
        echo "Collecting --ignore-url options"
        IGNORE_URL_OPTIONS=()
        for failure in "${BROKEN_LINKS[@]}"; do
          url="${failure##* }"
          IGNORE_URL_OPTIONS+=("--ignore-url=${url}")
        done

for file in "${TARGETS[@]}"; do 
    echo "Checking ${file}"
    grep -oE "\b(https?://|www\.)[^\[\(\)\"]+\b" "${file}" \
        | linkchecker --no-warnings --recursion-level 0 --output failures --check-extern --stdin \
        --ignore-url https://img.shields.io/matrix/plutus-core%3Amatrix.org # For some reason linkchecker fails to check this URL though it is valid
    if [ $? -ne 0 ]; then 
        echo "${file} has broken links, see output above"
        FAILED=1
    fi 
done 

exit "${FAILED}"


    - name: Check Files
      if: ${{ inputs.target-files != "" }}
      run: | 
        FAILED=0
        for file in "${TARGETS[@]}"; do 
            echo "Checking ${file}"
            grep -oE "\b(https?://|www\.)[^\[\(\)\"]+\b" "${file}" \
                | linkchecker --no-warnings --recursion-level 0 --output failures --check-extern --stdin \
                --ignore-url https://img.shields.io/matrix/plutus-core%3Amatrix.org # For some reason linkchecker fails to check this URL though it is valid
            if [ $? -ne 0 ]; then 
                echo "${file} has broken links, see output above"
                FAILED=1
            fi 
        done 
        
        exit "${FAILED}"