{ inputs, cell }:

let
  src = cell.library.pkgs.lib.sourceFilesBySuffices
    (cell.library.gitignore-source inputs.self)
    [ ".hs" ".yaml" ];
in

cell.library.pkgs.runCommand "stylish-haskell-checker"
{
  buildInputs = [
    cell.packages.fix-stylish-haskell
    cell.library.pkgs.diffutils
    cell.library.pkgs.glibcLocales
  ];
} ''
  echo FIXME > $out && exit 0

  set +e
  cp -a ${src} orig
  cp -a ${src} stylish
  chmod -R +w stylish
  cd stylish
  fix-stylish-haskell
  EXIT_CODE=$?
  if [[ $EXIT_CODE != 0 ]]
  then
    echo "*** stylish-haskell failed to format some files"
    exit $EXIT_CODE
  fi
  cd ..
  diff --brief --recursive orig stylish > /dev/null
  EXIT_CODE=$?
  if [[ $EXIT_CODE != 0 ]]
  then
    mkdir -p $out/nix-support
    diff -ur orig stylish > $out/stylish.diff
    echo "file none $out/stylish.diff" > $out/nix-support/hydra-build-products
    echo "*** Stylish-haskell found changes that need addressed first"
    echo "*** Please run \`nix-shell --run fix-stylish-haskell\` and commit changes"
    echo "*** or apply the diff generated by hydra if you don't have nix."
    exit $EXIT_CODE
  else
    echo $EXIT_CODE > $out
  fi
''
