"use strict";

module.exports = {
  purge: [
    "src/**/*.purs",
    "web-common/**/*.purs",
    "web-common-marlowe/**/*.purs",
    "web-common-playground/**/*.purs",
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    // FIXME: we need to unify colors between the website, dashboard and playground
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: "black",
      white: "white",
      primary: "#832dc4",
      secondary: "#1746a0",
      success: "#2cbb69",
      error: "#ff0000",
      gray: {
        light: "#f8f8f8",
        dark: "#e7e7e9",
        darker: "#d0d0d4",
        darkest: "#a0a0a0",
      },
      blue: {
        DEFAULT: "rgba(23, 70, 160, 1)",
        900: "rgba(23, 70, 160, 0.9)",
        800: "rgba(23, 70, 160, 0.8)",
        700: "rgba(23, 70, 160, 0.7)",
        600: "rgba(23, 70, 160, 0.6)",
        500: "rgba(23, 70, 160, 0.5)",
        400: "rgba(23, 70, 160, 0.4)",
        300: "rgba(23, 70, 160, 0.3)",
        200: "rgba(23, 70, 160, 0.2)",
        100: "rgba(23, 70, 160, 0.1)",
      },
    },
    borderRadius: {
      sm: "5px",
      DEFAULT: "10px",
      lg: "25px",
      full: "9999px",
    },
    boxShadow: {
      none: "none",
      sm: "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)",
      DEFAULT:
        "0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)",
      lg: "0 20px 25px -5px rgba(0,0,0,0.2), 0 10px 10px -5px rgba(0,0,0,0.04)",
      xl: "0 25px 50px -12px rgba(0,0,0,0.25)",
      deep: "0 2.5px 5px 0 rgba(0, 0, 0, 0.22)",
    },
    extend: {
      gridTemplateColumns: {
        /* This property was thought for the error and warning tabs. It's a grid of two columns.
             The second one occupies all the space it needs (normally the header title) and the first
             one occupies the space remaining. */
        "description-location": "1fr max-content",
      },
      spacing: {
        small: "0.687rem",
        medium: "1.375rem",
        big: "2.750rem",
      },
      width: {
        "30p": "30%",
      },
      maxHeight: {
        "70p": "70%",
      },
    },
  },
  variants: {},
  plugins: [],
  corePlugins: {
    container: false,
    space: true,
    divideWidth: false,
    divideColor: false,
    divideStyle: false,
    divideOpacity: false,
    accessibility: false,
    appearance: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundColor: true,
    backgroundImage: true,
    gradientColorStops: true,
    backgroundOpacity: false,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    borderCollapse: false,
    borderColor: true,
    borderOpacity: false,
    borderRadius: true,
    borderStyle: false,
    borderWidth: true,
    boxSizing: false,
    cursor: true,
    display: true,
    flexDirection: true,
    flexWrap: false,
    placeItems: false,
    placeContent: false,
    placeSelf: false,
    alignItems: true,
    alignContent: true,
    alignSelf: true,
    justifyItems: false,
    justifyContent: true,
    justifySelf: false,
    flex: true,
    flexGrow: true,
    flexShrink: true,
    order: false,
    float: true,
    clear: false,
    fontFamily: false,
    fontWeight: true,
    height: true,
    lineHeight: true,
    listStylePosition: false,
    listStyleType: false,
    maxHeight: true,
    maxWidth: true,
    minHeight: true,
    minWidth: true,
    objectFit: false,
    objectPosition: false,
    opacity: true,
    outline: true,
    overflow: true,
    overscrollBehavior: false,
    placeholderColor: false,
    placeholderOpacity: false,
    pointerEvents: true,
    position: true,
    inset: true,
    resize: false,
    boxShadow: true,
    ringWidth: true,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringColor: true,
    ringOpacity: false,
    fill: false,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    textAlign: true,
    textOpacity: false,
    textOverflow: true,
    fontStyle: false,
    textTransform: true,
    textDecoration: true,
    fontSmoothing: false,
    fontVariantNumeric: false,
    letterSpacing: false,
    userSelect: false,
    verticalAlign: false,
    visibility: true,
    whitespace: true,
    wordBreak: false,
    width: true,
    zIndex: true,
    gap: true,
    gridAutoFlow: false,
    gridTemplateColumns: true,
    gridAutoColumns: false,
    gridColumn: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridTemplateRows: true,
    gridAutoRows: false,
    gridRow: false,
    gridRowStart: false,
    gridRowEnd: false,
    transform: true,
    transformOrigin: true,
    scale: true,
    rotate: true,
    translate: true,
    skew: false,
    transitionProperty: true,
    transitionTimingFunction: true,
    transitionDuration: true,
    transitionDelay: false,
    animation: true,
  },
};
