(program
   1.1.0
   (\d ->
      (\cse ->
         (\cse ->
            (\cse ->
               (\cse ->
                  (\cse ->
                     (\cse ->
                        (\cse ->
                           (\cse ->
                              (\cse ->
                                 addInteger
                                   (addInteger
                                      (addInteger
                                         (addInteger (cse cse) cse)
                                         cse)
                                      (case
                                         (lessThanInteger (cse cse) (cse cse))
                                         [(cse cse), (cse cse)]))
                                   (case
                                      (lessThanInteger (cse cse) (cse cse))
                                      [(cse cse), (cse cse)]))
                                (addInteger cse))
                             (addInteger cse))
                          (addInteger cse))
                       (addInteger cse))
                    (cse (\ds ds ds ds -> ds) (\void -> error)))
                 (cse (\ds ds ds ds -> ds) (\void -> error)))
              (cse (\ds ds ds ds -> ds) (\void -> error)))
           (cse (\ds ds ds ds -> ds) (\void -> error)))
        (\cont fail ->
           (\cse ->
              (\cse ->
                 (\cse ->
                    (\cse ->
                       (\cse ->
                          cont
                            (unIData (cse cse))
                            (unIData (cse cse))
                            (unIData (cse cse))
                            (unIData (cse (cse cse))))
                         (cse cse))
                      (force headList))
                   (cse cse))
                (case (unConstrData d) [(\l r -> r)]))
             (force tailList))))