(program
   1.1.0
   ((\forced
      d ->
       case
         (case (unConstrData d) [(\l r -> r)])
         [ (\ds
             ds ->
              case
                ds
                [ (\ds
                    ds ->
                     case
                       ds
                       [ (\ds
                           ds ->
                            case
                              ds
                              [ (\ds
                                  ds ->
                                   case
                                     ds
                                     [ (\ds
                                         ds ->
                                          case
                                            ds
                                            [ (\ds
                                                ds ->
                                                 case
                                                   ds
                                                   [ (\ds
                                                       ds ->
                                                        case
                                                          ds
                                                          [ (\ds
                                                              ds ->
                                                               case
                                                                 ds
                                                                 [ (\ds
                                                                     ds ->
                                                                      case
                                                                        ds
                                                                        [ (\ds
                                                                            ds ->
                                                                             case
                                                                               ds
                                                                               [ (\ds
                                                                                   ds ->
                                                                                    case
                                                                                      ds
                                                                                      [ (\ds
                                                                                          ds ->
                                                                                           case
                                                                                             ds
                                                                                             [ (\ds
                                                                                                 ds ->
                                                                                                  case
                                                                                                    ds
                                                                                                    [ (\ds
                                                                                                        ds ->
                                                                                                         case
                                                                                                           ds
                                                                                                           [ (\ds
                                                                                                               ds ->
                                                                                                                unIData
                                                                                                                  (forced
                                                                                                                     ds)) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])
      (force headList)))