{-# LANGUAGE DeriveGeneric #-}
{-# OPTIONS -Wall #-}







-- | This module defines some general name constructs that replace raw string
-- names in many variants.

module Utils.Names where


import GHC.Generics






-- | A local name is a name for an item that's been brought into scope usually
-- via module importing. It can be either a bare name, or a dotted name, used
-- for qualified imports. An absolute name is like a dotted local name only it
-- uses the actual name of the module and the item, independent of renaming.

data Name
  = BareLocal String
  | DottedLocal String String
  | Absolute String String
  deriving (Show,Eq,Generic)


showName :: Name -> String
showName (BareLocal n) = n
showName (DottedLocal m n) = m ++ "." ++ n
showName (Absolute m n) = "!" ++ m ++ "." ++ n





-- A sourced item is either supplied by the user or, or generated by the
-- system.

data Sourced a = User a | Generated a
  deriving (Show,Eq,Generic)

unsourced :: Sourced a -> a
unsourced (User a) = a
unsourced (Generated a) = a


showSourced :: Sourced String -> String
showSourced (User a) = a
showSourced (Generated a) = "generated:" ++ a