{-# LANGUAGE OverloadedStrings #-}

{-| Reproducible encoding generator for Flat test coverage.

Run with: cabal run flat-encoding-generator

Prints the expected byte sequences for all Flat test values.
Anyone can re-run this to see current encodings and compare
with committed test constants.

Note: PIR and UPLC encodings are generated by functions in their
respective test modules (generatePIREncodings, etc.) since those
internal libraries cannot be depended on from an executable. -}
module Main where

import Data.ByteString qualified as B
import Data.Complex (Complex ((:+)))
import Data.DList qualified as DList
import Data.Fixed (E0, Fixed (..))
import Data.Functor.Identity (Identity (..))
import Data.List.NonEmpty qualified as NE
import Data.Map qualified as Map
import Data.Monoid qualified as Monoid
import Data.Ratio (Ratio, (%))
import Data.Semigroup qualified as Semigroup
import Data.Sequence qualified as Seq
import Data.Set qualified as Set
import Data.Tree (Tree (Node))
import Data.Word

import PlutusCore (Kind (..), Name (..), Normalized (..), TyName (..), Unique (..), Version (..))
import PlutusCore.Annotation (SrcSpan (..), SrcSpans (..))

-- Note: Binder is not publicly exported; its encodings are tested
-- in the test suite which has access to internal modules.
import PlutusCore.DeBruijn
  ( DeBruijn (..)
  , Index (..)
  , NamedDeBruijn (..)
  , NamedTyDeBruijn (..)
  , TyDeBruijn (..)
  , toFake
  )
import PlutusCore.Default (DefaultFun (..), DefaultUni (..))
import PlutusCore.Flat
import PlutusCore.Flat.Bits (asBytes, bits)
import PlutusCore.Flat.Instances.DList ()
import PlutusCore.Value qualified as V
import Universe (SomeTypeIn (..))

serRaw :: Flat a => a -> [Word8]
serRaw = asBytes . bits

p :: String -> [Word8] -> IO ()
p label bytes' = putStrLn $ label ++ " = " ++ show bytes'

main :: IO ()
main = do
  putStrLn "=== Section A: Flat library types ==="
  putStrLn ""
  putStrLn "-- Maybe Bool"
  p "Nothing :: Maybe Bool" (serRaw (Nothing :: Maybe Bool))
  p "Just True :: Maybe Bool" (serRaw (Just True :: Maybe Bool))
  putStrLn ""
  putStrLn "-- Either Bool ()"
  p "Right () :: Either Bool ()" (serRaw (Right () :: Either Bool ()))
  putStrLn ""
  putStrLn "-- NonEmpty Bool"
  p "True :| [False]" (serRaw (True NE.:| [False]))
  putStrLn ""
  putStrLn "-- Complex Word8"
  p "4 :+ 2 :: Complex Word8" (serRaw (4 :+ 2 :: Complex Word8))
  putStrLn ""
  putStrLn "-- Ratio Word8"
  p "3 % 4 :: Ratio Word8" (serRaw (3 % 4 :: Ratio Word8))
  putStrLn ""
  putStrLn "-- Set Word8"
  p "Set.fromList [1,2,3]" (serRaw (Set.fromList [1, 2, 3] :: Set.Set Word8))
  putStrLn ""
  putStrLn "-- Tree Word8"
  p "Node 1 [Node 2 []]" (serRaw (Node 1 [Node 2 []] :: Tree Word8))
  putStrLn ""
  putStrLn "-- Map Int Bool"
  p "Map.fromList [(1,True)]" (serRaw (Map.fromList [(1 :: Int, True)]))
  putStrLn ""
  putStrLn "-- Seq Word8"
  p "Seq.fromList [1,2]" (serRaw (Seq.fromList [1, 2] :: Seq.Seq Word8))
  putStrLn ""
  putStrLn "-- DList Word8"
  p "DList.fromList [1,2]" (serRaw (DList.fromList [1, 2] :: DList.DList Word8))
  putStrLn ""
  putStrLn "-- Filler"
  p "FillerEnd" (serRaw FillerEnd)
  putStrLn ""
  putStrLn "-- PreAligned Word8"
  p "preAligned 42" (serRaw (preAligned (42 :: Word8)))
  putStrLn ""
  putStrLn "-- Wrapper types"
  p "Identity True" (serRaw (Identity True))
  p "All True" (serRaw (Monoid.All True))
  p "Any False" (serRaw (Monoid.Any False))
  p "Dual (42 :: Word8)" (serRaw (Monoid.Dual (42 :: Word8)))
  p "Sum (42 :: Word8)" (serRaw (Monoid.Sum (42 :: Word8)))
  p "Product (42 :: Word8)" (serRaw (Monoid.Product (42 :: Word8)))
  p "Min (42 :: Word8)" (serRaw (Semigroup.Min (42 :: Word8)))
  p "Max (42 :: Word8)" (serRaw (Semigroup.Max (42 :: Word8)))
  p "Semigroup.First (42 :: Word8)" (serRaw (Semigroup.First (42 :: Word8)))
  p "Semigroup.Last (42 :: Word8)" (serRaw (Semigroup.Last (42 :: Word8)))
  p "Alt (Just True)" (serRaw (Monoid.Alt (Just True) :: Monoid.Alt Maybe Bool))
  p "MkFixed 123 :: Fixed E0" (serRaw (MkFixed 123 :: Fixed E0))

  putStrLn ""
  putStrLn "=== Section B: TPLC types ==="
  putStrLn ""
  p "Version 1 1 0" (serRaw (Version 1 1 0))
  p "Name \"x\" (Unique 0)" (serRaw (Name "x" (Unique 0)))
  p "Type () :: Kind ()" (serRaw (Type () :: Kind ()))
  p "DeBruijn (Index 1)" (serRaw (DeBruijn (Index 1)))
  p "NamedDeBruijn \"x\" (Index 42)" (serRaw (NamedDeBruijn "x" (Index 42)))
  let sp = SrcSpan "f" 1 2 3 4
  p "SrcSpan \"f\" 1 2 3 4" (serRaw sp)
  p "SrcSpans (Set.fromList [sp])" (serRaw (SrcSpans (Set.fromList [sp])))
  p "AddInteger" (serRaw AddInteger)
  p "SubtractInteger" (serRaw SubtractInteger)
  p "SomeTypeIn DefaultUniInteger" (serRaw (SomeTypeIn DefaultUniInteger))
  putStrLn ""
  putStrLn "-- Newtype wrappers"
  p "TyName (Name \"x\" (Unique 0))" (serRaw (TyName (Name "x" (Unique 0))))
  p "Unique 42" (serRaw (Unique 42))
  p "TyDeBruijn (DeBruijn (Index 1))" (serRaw (TyDeBruijn (DeBruijn (Index 1))))
  p
    "NamedTyDeBruijn (NamedDeBruijn \"x\" (Index 42))"
    (serRaw (NamedTyDeBruijn (NamedDeBruijn "x" (Index 42))))
  p "Index 1" (serRaw (Index 1))
  p "Normalized True" (serRaw (Normalized True))
  -- Binder tests are in the test suite (needs internal module access)
  p "FakeNamedDeBruijn (Index 1)" (serRaw (toFake (DeBruijn (Index 1))))

  putStrLn ""
  putStrLn "=== Section E: Value types ==="
  putStrLn ""
  let Just myK = V.k "abc"
      Just myQ = V.quantity 42
  p "K \"abc\"" (serRaw myK)
  p "Quantity 42" (serRaw myQ)
  p "ByteString \"abc\" (for K reference)" (serRaw ("abc" :: B.ByteString))
  p "Integer 42 (for Quantity reference)" (serRaw (42 :: Integer))
