{
  pkgs = hackage:
    {
      packages = {
        "optional-args".revision = (((hackage."optional-args")."1.0.2").revisions).default;
        "criterion-measurement".revision = (((hackage."criterion-measurement")."0.1.2.0").revisions).default;
        "criterion-measurement".flags.fast = false;
        "optics-core".revision = (((hackage."optics-core")."0.3.0.1").revisions).default;
        "newtype".revision = (((hackage."newtype")."0.2.2.0").revisions).default;
        "warp".revision = (((hackage."warp")."3.3.13").revisions).default;
        "warp".flags.allow-sendfilefd = true;
        "warp".flags.network-bytestring = false;
        "warp".flags.warp-debug = false;
        "Stream".revision = (((hackage."Stream")."0.4.7.2").revisions).default;
        "http-client".revision = (((hackage."http-client")."0.6.4.1").revisions).default;
        "http-client".flags.network-uri = true;
        "mtl-compat".revision = (((hackage."mtl-compat")."0.2.2").revisions).default;
        "mtl-compat".flags.two-point-one = false;
        "mtl-compat".flags.two-point-two = false;
        "barbies".revision = (((hackage."barbies")."2.0.2.0").revisions).default;
        "row-types".revision = (((hackage."row-types")."0.4.0.0").revisions).default;
        "io-streams-haproxy".revision = (((hackage."io-streams-haproxy")."1.0.1.0").revisions).default;
        "wai-websockets".revision = (((hackage."wai-websockets")."3.0.1.2").revisions).default;
        "wai-websockets".flags.example = true;
        "cookie".revision = (((hackage."cookie")."0.4.5").revisions).default;
        "void".revision = (((hackage."void")."0.7.3").revisions).default;
        "void".flags.safe = false;
        "streaming".revision = (((hackage."streaming")."0.2.3.0").revisions).default;
        "semigroupoids".revision = (((hackage."semigroupoids")."5.3.4").revisions).default;
        "semigroupoids".flags.comonad = true;
        "semigroupoids".flags.doctests = true;
        "semigroupoids".flags.unordered-containers = true;
        "semigroupoids".flags.distributive = true;
        "semigroupoids".flags.tagged = true;
        "semigroupoids".flags.containers = true;
        "semigroupoids".flags.contravariant = true;
        "byteorder".revision = (((hackage."byteorder")."1.0.4").revisions).default;
        "singleton-bool".revision = (((hackage."singleton-bool")."0.1.5").revisions).default;
        "free".revision = (((hackage."free")."5.1.3").revisions).default;
        "tf-random".revision = (((hackage."tf-random")."0.5").revisions).default;
        "async-timer".revision = (((hackage."async-timer")."0.1.4.1").revisions).default;
        "ghc".revision = (((hackage."ghc")."8.10.2.20201118").revisions).default;
        "Only".revision = (((hackage."Only")."0.1").revisions).default;
        "insert-ordered-containers".revision = (((hackage."insert-ordered-containers")."0.2.3.1").revisions).default;
        "cereal".revision = (((hackage."cereal")."0.5.8.1").revisions).default;
        "cereal".flags.bytestring-builder = false;
        "exceptions".revision = (((hackage."exceptions")."0.10.4").revisions).default;
        "quiet".revision = (((hackage."quiet")."0.2").revisions).default;
        "ghc-paths".revision = (((hackage."ghc-paths")."0.1.0.12").revisions).default;
        "binary".revision = (((hackage."binary")."0.8.8.0").revisions).default;
        "ghc-boot".revision = (((hackage."ghc-boot")."8.10.2.20201118").revisions).default;
        "wl-pprint-text".revision = (((hackage."wl-pprint-text")."1.2.0.1").revisions).default;
        "lazysmallcheck".revision = (((hackage."lazysmallcheck")."0.6").revisions).default;
        "sequence".revision = (((hackage."sequence")."0.9.8").revisions).default;
        "attoparsec-iso8601".revision = (((hackage."attoparsec-iso8601")."1.0.1.0").revisions).default;
        "attoparsec-iso8601".flags.fast = false;
        "attoparsec-iso8601".flags.developer = false;
        "formatting".revision = (((hackage."formatting")."7.1.1").revisions).default;
        "pipes".revision = (((hackage."pipes")."4.3.14").revisions).default;
        "deriving-aeson".revision = (((hackage."deriving-aeson")."0.2.6").revisions).default;
        "aws-lambda-haskell-runtime".revision = (((hackage."aws-lambda-haskell-runtime")."3.0.3").revisions).default;
        "ghc-prim".revision = (((hackage."ghc-prim")."0.6.1").revisions).default;
        "eventful-memory".revision = (((hackage."eventful-memory")."0.2.0").revisions).default;
        "utf8-string".revision = (((hackage."utf8-string")."1.0.1.1").revisions).default;
        "old-time".revision = (((hackage."old-time")."1.1.0.3").revisions).default;
        "bifunctors".revision = (((hackage."bifunctors")."5.5.7").revisions).default;
        "bifunctors".flags.semigroups = true;
        "bifunctors".flags.tagged = true;
        "pure-zlib".revision = (((hackage."pure-zlib")."0.6.7").revisions).default;
        "monoidal-containers".revision = (((hackage."monoidal-containers")."0.6.0.1").revisions).default;
        "monoidal-containers".flags.split-these = true;
        "extra".revision = (((hackage."extra")."1.7.8").revisions).default;
        "logict".revision = (((hackage."logict")."0.7.0.3").revisions).default;
        "srcloc".revision = (((hackage."srcloc")."0.5.1.2").revisions).default;
        "x509-validation".revision = (((hackage."x509-validation")."1.6.11").revisions).default;
        "aeson-casing".revision = (((hackage."aeson-casing")."0.2.0.0").revisions).default;
        "fail".revision = (((hackage."fail")."4.9.0.0").revisions).default;
        "MonadRandom".revision = (((hackage."MonadRandom")."0.5.2").revisions).default;
        "mersenne-random-pure64".revision = (((hackage."mersenne-random-pure64")."0.2.2.0").revisions).default;
        "mersenne-random-pure64".flags.small_base = false;
        "dense-linear-algebra".revision = (((hackage."dense-linear-algebra")."0.1.0.0").revisions).default;
        "hspec-expectations-pretty-diff".revision = (((hackage."hspec-expectations-pretty-diff")."0.7.2.5").revisions).default;
        "split".revision = (((hackage."split")."0.2.3.4").revisions).default;
        "data-fix".revision = (((hackage."data-fix")."0.3.0").revisions).default;
        "stm".revision = (((hackage."stm")."2.5.0.0").revisions).default;
        "text-short".revision = (((hackage."text-short")."0.1.3").revisions).default;
        "text-short".flags.asserts = false;
        "composition-prelude".revision = (((hackage."composition-prelude")."3.0.0.0").revisions).default;
        "composition-prelude".flags.development = false;
        "dec".revision = (((hackage."dec")."0.0.3").revisions).default;
        "microstache".revision = (((hackage."microstache")."1.0.1.1").revisions).default;
        "unix-time".revision = (((hackage."unix-time")."0.4.7").revisions).default;
        "http2".revision = (((hackage."http2")."2.0.5").revisions).default;
        "http2".flags.devel = false;
        "extensible-effects".revision = (((hackage."extensible-effects")."5.0.0.1").revisions).default;
        "extensible-effects".flags.dump-core = false;
        "extensible-effects".flags.lib-werror = false;
        "base-compat-batteries".revision = (((hackage."base-compat-batteries")."0.11.2").revisions).default;
        "constraints-extras".revision = (((hackage."constraints-extras")."0.3.0.2").revisions).default;
        "constraints-extras".flags.build-readme = true;
        "appar".revision = (((hackage."appar")."0.1.8").revisions).default;
        "hourglass".revision = (((hackage."hourglass")."0.2.12").revisions).default;
        "case-insensitive".revision = (((hackage."case-insensitive")."1.2.1.0").revisions).default;
        "dependent-sum-template".revision = (((hackage."dependent-sum-template")."0.1.0.3").revisions).default;
        "network-byte-order".revision = (((hackage."network-byte-order")."0.1.6").revisions).default;
        "sop-core".revision = (((hackage."sop-core")."0.5.0.1").revisions).default;
        "unliftio".revision = (((hackage."unliftio")."0.2.13.1").revisions).default;
        "servant-websockets".revision = (((hackage."servant-websockets")."2.0.0").revisions).default;
        "unix".revision = (((hackage."unix")."2.7.2.2").revisions).default;
        "SHA".revision = (((hackage."SHA")."1.6.4.4").revisions).default;
        "SHA".flags.exe = false;
        "ghc-heap".revision = (((hackage."ghc-heap")."8.10.2.20201118").revisions).default;
        "tasty-quickcheck".revision = (((hackage."tasty-quickcheck")."0.10.1.1").revisions).default;
        "mtl".revision = (((hackage."mtl")."2.2.2").revisions).default;
        "lifted-async".revision = (((hackage."lifted-async")."0.10.1.2").revisions).default;
        "network-uri".revision = (((hackage."network-uri")."2.6.3.0").revisions).default;
        "FloatingHex".revision = (((hackage."FloatingHex")."0.5").revisions).default;
        "network-info".revision = (((hackage."network-info")."0.2.0.10").revisions).default;
        "asn1-parse".revision = (((hackage."asn1-parse")."0.9.5").revisions).default;
        "regex-base".revision = (((hackage."regex-base")."0.94.0.0").revisions).default;
        "foldl".revision = (((hackage."foldl")."1.4.10").revisions).default;
        "pretty-simple".revision = (((hackage."pretty-simple")."4.0.0.0").revisions).default;
        "pretty-simple".flags.buildexample = false;
        "pretty-simple".flags.buildexe = false;
        "moo".revision = (((hackage."moo")."1.2").revisions).default;
        "zlib".revision = (((hackage."zlib")."0.6.2.2").revisions).default;
        "zlib".flags.non-blocking-ffi = false;
        "zlib".flags.bundled-c-zlib = false;
        "zlib".flags.pkg-config = false;
        "rts".revision = (((hackage."rts")."1.0").revisions).default;
        "lazy-search".revision = (((hackage."lazy-search")."0.1.2.1").revisions).default;
        "mmorph".revision = (((hackage."mmorph")."1.1.3").revisions).default;
        "cmdargs".revision = (((hackage."cmdargs")."0.10.20").revisions).default;
        "cmdargs".flags.testprog = false;
        "cmdargs".flags.quotation = true;
        "easy-file".revision = (((hackage."easy-file")."0.2.2").revisions).default;
        "ghci".revision = (((hackage."ghci")."8.10.2.20201118").revisions).default;
        "js-flot".revision = (((hackage."js-flot")."0.8.3").revisions).default;
        "dictionary-sharing".revision = (((hackage."dictionary-sharing")."0.1.0.0").revisions).default;
        "natural-transformation".revision = (((hackage."natural-transformation")."0.4").revisions).default;
        "statistics".revision = (((hackage."statistics")."0.15.2.0").revisions).default;
        "th-expand-syns".revision = (((hackage."th-expand-syns")."0.4.6.0").revisions).default;
        "regex-posix".revision = (((hackage."regex-posix")."0.96.0.0").revisions).default;
        "regex-posix".flags._regex-posix-clib = false;
        "cryptonite".revision = (((hackage."cryptonite")."0.27").revisions).default;
        "cryptonite".flags.support_sse = false;
        "cryptonite".flags.use_target_attributes = true;
        "cryptonite".flags.integer-gmp = true;
        "cryptonite".flags.support_rdrand = true;
        "cryptonite".flags.support_aesni = true;
        "cryptonite".flags.support_deepseq = true;
        "cryptonite".flags.support_pclmuldq = false;
        "cryptonite".flags.check_alignment = false;
        "cryptonite".flags.old_toolchain_inliner = false;
        "alex".revision = (((hackage."alex")."3.2.5").revisions).default;
        "alex".flags.small_base = true;
        "clock".revision = (((hackage."clock")."0.8").revisions).default;
        "clock".flags.llvm = false;
        "double-conversion".revision = (((hackage."double-conversion")."2.0.2.0").revisions).default;
        "double-conversion".flags.developer = false;
        "system-fileio".revision = (((hackage."system-fileio")."0.3.16.4").revisions).default;
        "safe-exceptions".revision = (((hackage."safe-exceptions")."0.1.7.1").revisions).default;
        "dependent-map".revision = (((hackage."dependent-map")."0.4.0.0").revisions).default;
        "adjunctions".revision = (((hackage."adjunctions")."4.4").revisions).default;
        "cryptohash-md5".revision = (((hackage."cryptohash-md5")."0.11.100.1").revisions).default;
        "invariant".revision = (((hackage."invariant")."0.5.3").revisions).default;
        "sum-type-boilerplate".revision = (((hackage."sum-type-boilerplate")."0.1.1").revisions).default;
        "th-orphans".revision = (((hackage."th-orphans")."0.13.11").revisions).default;
        "pem".revision = (((hackage."pem")."0.2.4").revisions).default;
        "http-api-data".revision = (((hackage."http-api-data")."0.4.1.1").revisions).default;
        "http-api-data".flags.use-text-show = false;
        "generic-deriving".revision = (((hackage."generic-deriving")."1.13.1").revisions).default;
        "generic-deriving".flags.base-4-9 = true;
        "megaparsec".revision = (((hackage."megaparsec")."9.0.1").revisions).default;
        "megaparsec".flags.dev = false;
        "syb".revision = (((hackage."syb")."0.7.1").revisions).default;
        "distributive".revision = (((hackage."distributive")."0.6.2").revisions).default;
        "distributive".flags.semigroups = true;
        "distributive".flags.tagged = true;
        "eventful-sql-common".revision = (((hackage."eventful-sql-common")."0.2.0").revisions).default;
        "tuple".revision = (((hackage."tuple")."0.3.0.2").revisions).default;
        "eventful-sqlite".revision = (((hackage."eventful-sqlite")."0.2.0").revisions).default;
        "generic-arbitrary".revision = (((hackage."generic-arbitrary")."0.1.0").revisions).default;
        "nicify-lib".revision = (((hackage."nicify-lib")."1.0.1").revisions).default;
        "persistent-template".revision = (((hackage."persistent-template")."2.9.1.0").revisions).default;
        "asn1-encoding".revision = (((hackage."asn1-encoding")."0.9.6").revisions).default;
        "binary-orphans".revision = (((hackage."binary-orphans")."1.0.1").revisions).default;
        "vector-th-unbox".revision = (((hackage."vector-th-unbox")."0.2.1.7").revisions).default;
        "hscolour".revision = (((hackage."hscolour")."1.24.4").revisions).default;
        "multiset".revision = (((hackage."multiset")."0.3.4.3").revisions).default;
        "generics-sop".revision = (((hackage."generics-sop")."0.5.1.0").revisions).default;
        "system-filepath".revision = (((hackage."system-filepath")."0.4.14").revisions).default;
        "bytestring-builder".revision = (((hackage."bytestring-builder")."0.10.8.2.0").revisions).default;
        "bytestring-builder".flags.bytestring_has_builder = true;
        "QuickCheck".revision = (((hackage."QuickCheck")."2.13.2").revisions).default;
        "QuickCheck".flags.templatehaskell = true;
        "scientific".revision = (((hackage."scientific")."0.3.6.2").revisions).default;
        "scientific".flags.integer-simple = false;
        "scientific".flags.bytestring-builder = false;
        "time-manager".revision = (((hackage."time-manager")."0.0.0").revisions).default;
        "tasty".revision = (((hackage."tasty")."1.3.1").revisions).default;
        "tasty".flags.clock = true;
        "newtype-generics".revision = (((hackage."newtype-generics")."0.5.4").revisions).default;
        "hspec-discover".revision = (((hackage."hspec-discover")."2.7.4").revisions).default;
        "half".revision = (((hackage."half")."0.3").revisions).default;
        "parallel".revision = (((hackage."parallel")."3.2.2.0").revisions).default;
        "indexed-profunctors".revision = (((hackage."indexed-profunctors")."0.1").revisions).default;
        "deepseq".revision = (((hackage."deepseq")."1.4.4.0").revisions).default;
        "errors".revision = (((hackage."errors")."2.3.0").revisions).default;
        "random".revision = (((hackage."random")."1.1").revisions).default;
        "temporary".revision = (((hackage."temporary")."1.3").revisions).default;
        "recursion-schemes".revision = (((hackage."recursion-schemes")."5.1.3").revisions).default;
        "recursion-schemes".flags.template-haskell = true;
        "optics-th".revision = (((hackage."optics-th")."0.3.0.2").revisions).default;
        "boxes".revision = (((hackage."boxes")."0.1.5").revisions).default;
        "validation".revision = (((hackage."validation")."1.1").revisions).default;
        "http-conduit".revision = (((hackage."http-conduit")."2.3.7.3").revisions).default;
        "uuid-types".revision = (((hackage."uuid-types")."1.0.3").revisions).default;
        "string-conversions".revision = (((hackage."string-conversions")."0.4.0.1").revisions).default;
        "optparse-applicative".revision = (((hackage."optparse-applicative")."0.16.0.0").revisions).default;
        "statistics-linreg".revision = (((hackage."statistics-linreg")."0.3").revisions).default;
        "network".revision = (((hackage."network")."3.1.2.0").revisions).default;
        "network".flags.devel = false;
        "word8".revision = (((hackage."word8")."0.1.3").revisions).default;
        "connection".revision = (((hackage."connection")."0.3.1").revisions).default;
        "splitmix".revision = (((hackage."splitmix")."0.0.5").revisions).default;
        "splitmix".flags.optimised-mixer = false;
        "splitmix".flags.random = true;
        "async".revision = (((hackage."async")."2.2.2").revisions).default;
        "async".flags.bench = false;
        "protolude".revision = (((hackage."protolude")."0.3.0").revisions).default;
        "protolude".flags.dev = false;
        "dlist".revision = (((hackage."dlist")."1.0").revisions).default;
        "dlist".flags.werror = false;
        "doctest".revision = (((hackage."doctest")."0.17").revisions).default;
        "time-out".revision = (((hackage."time-out")."0.2").revisions).default;
        "websockets".revision = (((hackage."websockets")."0.12.7.1").revisions).default;
        "websockets".flags.example = false;
        "conduit".revision = (((hackage."conduit")."1.3.3").revisions).default;
        "x509-store".revision = (((hackage."x509-store")."1.6.7").revisions).default;
        "constraints".revision = (((hackage."constraints")."0.12").revisions).default;
        "turtle".revision = (((hackage."turtle")."1.5.21").revisions).default;
        "semigroups".revision = (((hackage."semigroups")."0.19.1").revisions).default;
        "semigroups".flags.bytestring = true;
        "semigroups".flags.unordered-containers = true;
        "semigroups".flags.text = true;
        "semigroups".flags.tagged = true;
        "semigroups".flags.containers = true;
        "semigroups".flags.binary = true;
        "semigroups".flags.hashable = true;
        "semigroups".flags.transformers = true;
        "semigroups".flags.deepseq = true;
        "semigroups".flags.bytestring-builder = false;
        "semigroups".flags.template-haskell = true;
        "data-default".revision = (((hackage."data-default")."0.7.1.1").revisions).default;
        "HUnit".revision = (((hackage."HUnit")."1.6.1.0").revisions).default;
        "cborg-json".revision = (((hackage."cborg-json")."0.2.2.0").revisions).default;
        "lifted-base".revision = (((hackage."lifted-base")."0.2.3.12").revisions).default;
        "data-default-instances-old-locale".revision = (((hackage."data-default-instances-old-locale")."0.0.1").revisions).default;
        "servant-subscriber".revision = (((hackage."servant-subscriber")."0.7.0.0").revisions).default;
        "servant-subscriber".flags.websockets_0_11 = true;
        "tree-diff".revision = (((hackage."tree-diff")."0.1").revisions).default;
        "ordered-containers".revision = (((hackage."ordered-containers")."0.2.2").revisions).default;
        "uniplate".revision = (((hackage."uniplate")."1.6.13").revisions).default;
        "parsec".revision = (((hackage."parsec")."3.1.14.0").revisions).default;
        "crackNum".revision = (((hackage."crackNum")."2.4").revisions).default;
        "th-reify-many".revision = (((hackage."th-reify-many")."0.1.9").revisions).default;
        "http-media".revision = (((hackage."http-media")."0.8.0.0").revisions).default;
        "hsc2hs".revision = (((hackage."hsc2hs")."0.68.7").revisions).default;
        "hsc2hs".flags.in-ghc-tree = false;
        "directory".revision = (((hackage."directory")."1.3.6.0").revisions).default;
        "prettyprinter-ansi-terminal".revision = (((hackage."prettyprinter-ansi-terminal")."1.1.2").revisions).default;
        "yaml".revision = (((hackage."yaml")."0.11.5.0").revisions).default;
        "yaml".flags.no-exe = true;
        "yaml".flags.no-examples = true;
        "transformers-compat".revision = (((hackage."transformers-compat")."0.6.6").revisions).default;
        "transformers-compat".flags.five = false;
        "transformers-compat".flags.generic-deriving = true;
        "transformers-compat".flags.two = false;
        "transformers-compat".flags.five-three = true;
        "transformers-compat".flags.mtl = true;
        "transformers-compat".flags.four = false;
        "transformers-compat".flags.three = false;
        "template-haskell".revision = (((hackage."template-haskell")."2.16.0.0").revisions).default;
        "hspec-expectations".revision = (((hackage."hspec-expectations")."0.8.2").revisions).default;
        "mono-traversable".revision = (((hackage."mono-traversable")."1.0.15.1").revisions).default;
        "psqueues".revision = (((hackage."psqueues")."0.2.7.2").revisions).default;
        "dns".revision = (((hackage."dns")."3.0.4").revisions).default;
        "vector".revision = (((hackage."vector")."0.12.1.2").revisions).default;
        "vector".flags.unsafechecks = false;
        "vector".flags.internalchecks = false;
        "vector".flags.wall = false;
        "vector".flags.boundschecks = true;
        "call-stack".revision = (((hackage."call-stack")."0.2.0").revisions).default;
        "primitive".revision = (((hackage."primitive")."0.7.1.0").revisions).default;
        "profunctors".revision = (((hackage."profunctors")."5.6").revisions).default;
        "safe".revision = (((hackage."safe")."0.3.19").revisions).default;
        "size-based".revision = (((hackage."size-based")."0.1.2.0").revisions).default;
        "ListLike".revision = (((hackage."ListLike")."4.7.2").revisions).default;
        "blaze-builder".revision = (((hackage."blaze-builder")."0.4.1.0").revisions).default;
        "base-compat".revision = (((hackage."base-compat")."0.11.2").revisions).default;
        "js-jquery".revision = (((hackage."js-jquery")."3.3.1").revisions).default;
        "singletons".revision = (((hackage."singletons")."2.7").revisions).default;
        "terminal-size".revision = (((hackage."terminal-size")."0.3.2.1").revisions).default;
        "silently".revision = (((hackage."silently")."1.2.5.1").revisions).default;
        "math-functions".revision = (((hackage."math-functions")."0.3.4.1").revisions).default;
        "math-functions".flags.system-expm1 = true;
        "math-functions".flags.system-erf = true;
        "regex-compat".revision = (((hackage."regex-compat")."0.95.2.0").revisions).default;
        "time-compat".revision = (((hackage."time-compat")."1.9.4").revisions).default;
        "time-compat".flags.old-locale = false;
        "io-streams".revision = (((hackage."io-streams")."1.5.2.0").revisions).default;
        "io-streams".flags.network = true;
        "io-streams".flags.nointeractivetests = false;
        "io-streams".flags.zlib = true;
        "snap-server".revision = (((hackage."snap-server")."1.1.2.0").revisions).default;
        "snap-server".flags.openssl = false;
        "snap-server".flags.portable = false;
        "snap-server".flags.debug = false;
        "snap-server".flags.build-pong = false;
        "snap-server".flags.build-testserver = false;
        "x509-system".revision = (((hackage."x509-system")."1.6.6").revisions).default;
        "ansi-terminal".revision = (((hackage."ansi-terminal")."0.10.3").revisions).default;
        "ansi-terminal".flags.example = false;
        "witherable-class".revision = (((hackage."witherable-class")."0").revisions).default;
        "vector-binary-instances".revision = (((hackage."vector-binary-instances")."0.2.5.1").revisions).default;
        "quickcheck-instances".revision = (((hackage."quickcheck-instances")."0.3.23").revisions).default;
        "quickcheck-instances".flags.bytestring-builder = false;
        "tagged".revision = (((hackage."tagged")."0.8.6").revisions).default;
        "tagged".flags.transformers = true;
        "tagged".flags.deepseq = true;
        "x509".revision = (((hackage."x509")."1.7.5").revisions).default;
        "parsers".revision = (((hackage."parsers")."0.12.10").revisions).default;
        "parsers".flags.parsec = true;
        "parsers".flags.binary = true;
        "parsers".flags.attoparsec = true;
        "cassava".revision = (((hackage."cassava")."0.5.2.0").revisions).default;
        "cassava".flags.bytestring--lt-0_10_4 = false;
        "string-conv".revision = (((hackage."string-conv")."0.1.2").revisions).default;
        "string-conv".flags.lib-werror = false;
        "lens".revision = (((hackage."lens")."4.19.2").revisions).default;
        "lens".flags.j = false;
        "lens".flags.test-properties = true;
        "lens".flags.old-inline-pragmas = false;
        "lens".flags.test-templates = true;
        "lens".flags.trustworthy = true;
        "lens".flags.test-doctests = true;
        "lens".flags.benchmark-uniplate = false;
        "lens".flags.inlining = true;
        "lens".flags.dump-splices = false;
        "lens".flags.test-hunit = true;
        "lens".flags.safe = false;
        "unliftio-core".revision = (((hackage."unliftio-core")."0.2.0.1").revisions).default;
        "containers".revision = (((hackage."containers")."0.6.2.1").revisions).default;
        "OneTuple".revision = (((hackage."OneTuple")."0.2.2.1").revisions).default;
        "wl-pprint-annotated".revision = (((hackage."wl-pprint-annotated")."0.1.0.1").revisions).default;
        "ekg-json".revision = (((hackage."ekg-json")."0.1.0.6").revisions).default;
        "weigh".revision = (((hackage."weigh")."0.0.16").revisions).default;
        "integer-logarithms".revision = (((hackage."integer-logarithms")."1.0.3.1").revisions).default;
        "integer-logarithms".flags.check-bounds = false;
        "integer-logarithms".flags.integer-gmp = true;
        "semialign".revision = (((hackage."semialign")."1.1.0.1").revisions).default;
        "semialign".flags.semigroupoids = true;
        "reflection".revision = (((hackage."reflection")."2.1.6").revisions).default;
        "reflection".flags.slow = false;
        "reflection".flags.template-haskell = true;
        "katip".revision = (((hackage."katip")."0.8.5.0").revisions).default;
        "katip".flags.lib-werror = false;
        "time-interval".revision = (((hackage."time-interval")."0.1.1").revisions).default;
        "these".revision = (((hackage."these")."1.1.1.1").revisions).default;
        "these".flags.assoc = true;
        "bimap".revision = (((hackage."bimap")."0.4.0").revisions).default;
        "dependent-sum".revision = (((hackage."dependent-sum")."0.6.2.0").revisions).default;
        "socks".revision = (((hackage."socks")."0.6.1").revisions).default;
        "wai-cors".revision = (((hackage."wai-cors")."0.2.7").revisions).default;
        "ekg-core".revision = (((hackage."ekg-core")."0.1.1.7").revisions).default;
        "streaming-commons".revision = (((hackage."streaming-commons")."0.2.2.1").revisions).default;
        "streaming-commons".flags.use-bytestring-builder = false;
        "canonical-json".revision = (((hackage."canonical-json")."0.6.0.0").revisions).default;
        "inline-c".revision = (((hackage."inline-c")."0.9.1.3").revisions).default;
        "inline-c".flags.gsl-example = false;
        "base-unicode-symbols".revision = (((hackage."base-unicode-symbols")."0.2.4.2").revisions).default;
        "base-unicode-symbols".flags.base-4-8 = true;
        "base-unicode-symbols".flags.old-base = false;
        "fingertree".revision = (((hackage."fingertree")."0.1.4.2").revisions).default;
        "haskell-lexer".revision = (((hackage."haskell-lexer")."1.1").revisions).default;
        "monad-par".revision = (((hackage."monad-par")."0.3.5").revisions).default;
        "monad-par".flags.newgeneric = false;
        "monad-par".flags.chaselev = false;
        "bytestring".revision = (((hackage."bytestring")."0.10.10.0").revisions).default;
        "ansi-wl-pprint".revision = (((hackage."ansi-wl-pprint")."0.6.9").revisions).default;
        "ansi-wl-pprint".flags.example = false;
        "microlens-th".revision = (((hackage."microlens-th")."0.4.3.6").revisions).default;
        "mainland-pretty".revision = (((hackage."mainland-pretty")."0.7.0.1").revisions).default;
        "mwc-random".revision = (((hackage."mwc-random")."0.14.0.0").revisions).default;
        "wai".revision = (((hackage."wai")."3.2.2.1").revisions).default;
        "th-utilities".revision = (((hackage."th-utilities")."0.2.4.0").revisions).default;
        "basement".revision = (((hackage."basement")."0.0.11").revisions).default;
        "witherable".revision = (((hackage."witherable")."0.3.5").revisions).default;
        "process-extras".revision = (((hackage."process-extras")."0.7.4").revisions).default;
        "setenv".revision = (((hackage."setenv")."0.1.1.3").revisions).default;
        "cryptohash-sha1".revision = (((hackage."cryptohash-sha1")."0.11.100.1").revisions).default;
        "serialise".revision = (((hackage."serialise")."0.2.3.0").revisions).default;
        "serialise".flags.newtime15 = true;
        "flat".revision = (((hackage."flat")."0.4.4").revisions).default;
        "wl-pprint".revision = (((hackage."wl-pprint")."1.2.1").revisions).default;
        "hostname".revision = (((hackage."hostname")."1.0").revisions).default;
        "tasty-smallcheck".revision = (((hackage."tasty-smallcheck")."0.8.1").revisions).default;
        "sbv".revision = (((hackage."sbv")."8.9").revisions).default;
        "sbv".flags.skiphlinttester = false;
        "either".revision = (((hackage."either")."5.0.1.1").revisions).default;
        "old-locale".revision = (((hackage."old-locale")."1.0.0.7").revisions).default;
        "sort".revision = (((hackage."sort")."1.0.0.0").revisions).default;
        "wcwidth".revision = (((hackage."wcwidth")."0.0.2").revisions).default;
        "wcwidth".flags.split-base = true;
        "wcwidth".flags.cli = false;
        "testing-type-modifiers".revision = (((hackage."testing-type-modifiers")."0.1.0.1").revisions).default;
        "StateVar".revision = (((hackage."StateVar")."1.2").revisions).default;
        "safe-exceptions-checked".revision = (((hackage."safe-exceptions-checked")."0.1.0").revisions).default;
        "typed-process".revision = (((hackage."typed-process")."0.2.6.0").revisions).default;
        "vault".revision = (((hackage."vault")."0.3.1.4").revisions).default;
        "vault".flags.useghc = true;
        "servant-foreign".revision = (((hackage."servant-foreign")."0.15").revisions).default;
        "mime-types".revision = (((hackage."mime-types")."0.1.0.9").revisions).default;
        "ieee754".revision = (((hackage."ieee754")."0.8.0").revisions).default;
        "zlib-bindings".revision = (((hackage."zlib-bindings")."0.1.1.5").revisions).default;
        "charset".revision = (((hackage."charset")."0.3.7.1").revisions).default;
        "th-desugar".revision = (((hackage."th-desugar")."1.11").revisions).default;
        "http-client-tls".revision = (((hackage."http-client-tls")."0.3.5.3").revisions).default;
        "contravariant".revision = (((hackage."contravariant")."1.5.2").revisions).default;
        "contravariant".flags.semigroups = true;
        "contravariant".flags.tagged = true;
        "contravariant".flags.statevar = true;
        "atomic-primops".revision = (((hackage."atomic-primops")."0.8.4").revisions).default;
        "atomic-primops".flags.debug = false;
        "data-default-instances-dlist".revision = (((hackage."data-default-instances-dlist")."0.0.1").revisions).default;
        "snap-core".revision = (((hackage."snap-core")."1.0.4.2").revisions).default;
        "snap-core".flags.portable = false;
        "snap-core".flags.debug = false;
        "snap-core".flags.network-uri = true;
        "prometheus".revision = (((hackage."prometheus")."2.1.3").revisions).default;
        "rate-limit".revision = (((hackage."rate-limit")."1.4.2").revisions).default;
        "type-equality".revision = (((hackage."type-equality")."1").revisions).default;
        "aws-lambda-haskell-runtime-wai".revision = (((hackage."aws-lambda-haskell-runtime-wai")."1.0.2").revisions).default;
        "optics-extra".revision = (((hackage."optics-extra")."0.3").revisions).default;
        "freer-simple".revision = (((hackage."freer-simple")."1.2.1.1").revisions).default;
        "parser-combinators".revision = (((hackage."parser-combinators")."1.2.1").revisions).default;
        "parser-combinators".flags.dev = false;
        "blaze-markup".revision = (((hackage."blaze-markup")."0.8.2.7").revisions).default;
        "path".revision = (((hackage."path")."0.8.0").revisions).default;
        "path".flags.dev = false;
        "eventful-core".revision = (((hackage."eventful-core")."0.2.0").revisions).default;
        "tasty-golden".revision = (((hackage."tasty-golden")."2.3.4").revisions).default;
        "tasty-golden".flags.build-example = false;
        "uuid".revision = (((hackage."uuid")."1.3.13").revisions).default;
        "tasty-expected-failure".revision = (((hackage."tasty-expected-failure")."0.12.1").revisions).default;
        "deriving-compat".revision = (((hackage."deriving-compat")."0.5.9").revisions).default;
        "deriving-compat".flags.base-4-9 = true;
        "deriving-compat".flags.template-haskell-2-11 = true;
        "deriving-compat".flags.new-functor-classes = true;
        "persistent".revision = (((hackage."persistent")."2.11.0.1").revisions).default;
        "persistent".flags.nooverlap = false;
        "text".revision = (((hackage."text")."1.2.3.2").revisions).default;
        "Cabal".revision = (((hackage."Cabal")."3.2.0.0").revisions).default;
        "assoc".revision = (((hackage."assoc")."1.0.2").revisions).default;
        "Diff".revision = (((hackage."Diff")."0.4.0").revisions).default;
        "unordered-containers".revision = (((hackage."unordered-containers")."0.2.13.0").revisions).default;
        "unordered-containers".flags.debug = false;
        "base64-bytestring".revision = (((hackage."base64-bytestring")."1.0.0.3").revisions).default;
        "aeson-pretty".revision = (((hackage."aeson-pretty")."0.8.8").revisions).default;
        "aeson-pretty".flags.lib-only = false;
        "base".revision = (((hackage."base")."4.14.1.0").revisions).default;
        "gray-code".revision = (((hackage."gray-code")."0.3.1").revisions).default;
        "servant-client".revision = (((hackage."servant-client")."0.16.0.1").revisions).default;
        "abstract-deque".revision = (((hackage."abstract-deque")."0.3").revisions).default;
        "abstract-deque".flags.usecas = false;
        "tasty-hedgehog".revision = (((hackage."tasty-hedgehog")."1.0.0.2").revisions).default;
        "time-units".revision = (((hackage."time-units")."1.0.0").revisions).default;
        "comonad".revision = (((hackage."comonad")."5.0.6").revisions).default;
        "comonad".flags.distributive = true;
        "comonad".flags.test-doctests = true;
        "comonad".flags.containers = true;
        "hspec".revision = (((hackage."hspec")."2.7.4").revisions).default;
        "time".revision = (((hackage."time")."1.9.3").revisions).default;
        "th-compat".revision = (((hackage."th-compat")."0.1").revisions).default;
        "data-default-class".revision = (((hackage."data-default-class")."0.1.2.0").revisions).default;
        "managed".revision = (((hackage."managed")."1.0.8").revisions).default;
        "base16-bytestring".revision = (((hackage."base16-bytestring")."0.1.1.7").revisions).default;
        "vector-algorithms".revision = (((hackage."vector-algorithms")."0.8.0.3").revisions).default;
        "vector-algorithms".flags.unsafechecks = false;
        "vector-algorithms".flags.internalchecks = false;
        "vector-algorithms".flags.llvm = false;
        "vector-algorithms".flags.boundschecks = true;
        "vector-algorithms".flags.bench = true;
        "vector-algorithms".flags.properties = true;
        "doctest-discover".revision = (((hackage."doctest-discover")."0.2.0.0").revisions).default;
        "prettyprinter".revision = (((hackage."prettyprinter")."1.7.0").revisions).default;
        "prettyprinter".flags.buildreadme = false;
        "iproute".revision = (((hackage."iproute")."1.7.9").revisions).default;
        "tasty-hunit".revision = (((hackage."tasty-hunit")."0.10.0.2").revisions).default;
        "readable".revision = (((hackage."readable")."0.3.1").revisions).default;
        "pretty-show".revision = (((hackage."pretty-show")."1.10").revisions).default;
        "monad-logger".revision = (((hackage."monad-logger")."0.3.35").revisions).default;
        "monad-logger".flags.template_haskell = true;
        "transformers".revision = (((hackage."transformers")."0.5.6.2").revisions).default;
        "hashable".revision = (((hackage."hashable")."1.3.0.0").revisions).default;
        "hashable".flags.sse2 = true;
        "hashable".flags.integer-gmp = true;
        "hashable".flags.sse41 = false;
        "hashable".flags.examples = false;
        "quickcheck-io".revision = (((hackage."quickcheck-io")."0.2.0").revisions).default;
        "wai-extra".revision = (((hackage."wai-extra")."3.1.2").revisions).default;
        "wai-extra".flags.build-example = false;
        "data-default-instances-containers".revision = (((hackage."data-default-instances-containers")."0.0.1").revisions).default;
        "stm-chans".revision = (((hackage."stm-chans")."3.0.0.4").revisions).default;
        "attoparsec".revision = (((hackage."attoparsec")."0.13.2.4").revisions).default;
        "attoparsec".flags.developer = false;
        "blaze-html".revision = (((hackage."blaze-html")."0.9.1.2").revisions).default;
        "th-extras".revision = (((hackage."th-extras")."0.0.0.4").revisions).default;
        "th-extras".flags.base4 = true;
        "digest".revision = (((hackage."digest")."0.0.1.2").revisions).default;
        "digest".flags.bytestring-in-base = false;
        "generic-lens".revision = (((hackage."generic-lens")."2.0.0.0").revisions).default;
        "swagger2".revision = (((hackage."swagger2")."2.6").revisions).default;
        "colour".revision = (((hackage."colour")."2.3.5").revisions).default;
        "transformers-base".revision = (((hackage."transformers-base")."0.4.5.2").revisions).default;
        "transformers-base".flags.orphaninstances = true;
        "happy".revision = (((hackage."happy")."1.20.0").revisions).default;
        "file-embed".revision = (((hackage."file-embed")."0.0.13.0").revisions).default;
        "operational".revision = (((hackage."operational")."0.2.3.5").revisions).default;
        "operational".flags.buildexamples = true;
        "foundation".revision = (((hackage."foundation")."0.0.25").revisions).default;
        "foundation".flags.minimal-deps = false;
        "foundation".flags.doctest = false;
        "foundation".flags.linktest = false;
        "foundation".flags.experimental = false;
        "foundation".flags.bounds-check = false;
        "foundation".flags.bench-all = false;
        "strict".revision = (((hackage."strict")."0.4").revisions).default;
        "strict".flags.assoc = true;
        "hpc".revision = (((hackage."hpc")."0.6.1.0").revisions).default;
        "entropy".revision = (((hackage."entropy")."0.4.1.6").revisions).default;
        "entropy".flags.halvm = false;
        "criterion".revision = (((hackage."criterion")."1.5.7.0").revisions).default;
        "criterion".flags.embed-data-files = false;
        "criterion".flags.fast = false;
        "monad-par-extras".revision = (((hackage."monad-par-extras")."0.3.3").revisions).default;
        "nonempty-containers".revision = (((hackage."nonempty-containers")."0.3.3.0").revisions).default;
        "filepath".revision = (((hackage."filepath")."1.4.2.1").revisions).default;
        "auto-update".revision = (((hackage."auto-update")."0.1.6").revisions).default;
        "code-page".revision = (((hackage."code-page")."0.2").revisions).default;
        "resource-pool".revision = (((hackage."resource-pool")."0.2.3.2").revisions).default;
        "resource-pool".flags.developer = false;
        "asn1-types".revision = (((hackage."asn1-types")."0.3.4").revisions).default;
        "servant-client-core".revision = (((hackage."servant-client-core")."0.16").revisions).default;
        "hint".revision = (((hackage."hint")."0.9.0.3").revisions).default;
        "monad-loops".revision = (((hackage."monad-loops")."0.4.3").revisions).default;
        "monad-loops".flags.base4 = true;
        "Unique".revision = (((hackage."Unique")."0.4.7.8").revisions).default;
        "unbounded-delays".revision = (((hackage."unbounded-delays")."0.1.1.0").revisions).default;
        "hedgehog".revision = (((hackage."hedgehog")."1.0.3").revisions).default;
        "hspec-core".revision = (((hackage."hspec-core")."2.7.4").revisions).default;
        "cborg".revision = (((hackage."cborg")."0.2.4.0").revisions).default;
        "cborg".flags.optimize-gmp = true;
        "unix-compat".revision = (((hackage."unix-compat")."0.5.2").revisions).default;
        "unix-compat".flags.old-time = false;
        "quickcheck-text".revision = (((hackage."quickcheck-text")."0.1.2.1").revisions).default;
        "monad-control".revision = (((hackage."monad-control")."1.0.2.3").revisions).default;
        "process".revision = (((hackage."process")."1.6.9.0").revisions).default;
        "tls".revision = (((hackage."tls")."1.5.4").revisions).default;
        "tls".flags.compat = true;
        "tls".flags.network = true;
        "tls".flags.hans = false;
        "kan-extensions".revision = (((hackage."kan-extensions")."5.2.1").revisions).default;
        "nonempty-vector".revision = (((hackage."nonempty-vector")."0.2.0.2").revisions).default;
        "path-io".revision = (((hackage."path-io")."1.6.2").revisions).default;
        "path-io".flags.dev = false;
        "wai-logger".revision = (((hackage."wai-logger")."2.3.6").revisions).default;
        "th-lift".revision = (((hackage."th-lift")."0.8.2").revisions).default;
        "typerep-map".revision = (((hackage."typerep-map")."0.3.3.0").revisions).default;
        "libyaml".revision = (((hackage."libyaml")."0.1.2").revisions).default;
        "libyaml".flags.system-libyaml = false;
        "libyaml".flags.no-unicode = false;
        "resourcet".revision = (((hackage."resourcet")."1.2.4.2").revisions).default;
        "inline-r".revision = (((hackage."inline-r")."0.10.3").revisions).default;
        "pretty".revision = (((hackage."pretty")."1.1.3.6").revisions).default;
        "generic-lens-core".revision = (((hackage."generic-lens-core")."2.0.0.0").revisions).default;
        "cabal-doctest".revision = (((hackage."cabal-doctest")."1.0.8").revisions).default;
        "Glob".revision = (((hackage."Glob")."0.10.1").revisions).default;
        "algebraic-graphs".revision = (((hackage."algebraic-graphs")."0.5").revisions).default;
        "microlens".revision = (((hackage."microlens")."0.4.11.2").revisions).default;
        "aeson".revision = (((hackage."aeson")."1.5.4.1").revisions).default;
        "aeson".flags.cffi = false;
        "aeson".flags.fast = false;
        "aeson".flags.bytestring-builder = false;
        "aeson".flags.developer = false;
        "abstract-par".revision = (((hackage."abstract-par")."0.3.3").revisions).default;
        "data-ordlist".revision = (((hackage."data-ordlist")."0.4.7.0").revisions).default;
        "wai-app-static".revision = (((hackage."wai-app-static")."3.1.7.2").revisions).default;
        "wai-app-static".flags.print = false;
        "persistent-sqlite".revision = (((hackage."persistent-sqlite")."2.11.0.0").revisions).default;
        "persistent-sqlite".flags.systemlib = false;
        "persistent-sqlite".flags.have-usleep = true;
        "persistent-sqlite".flags.use-pkgconfig = false;
        "persistent-sqlite".flags.build-sanity-exe = false;
        "persistent-sqlite".flags.json1 = true;
        "persistent-sqlite".flags.use-stat3 = false;
        "persistent-sqlite".flags.use-stat4 = true;
        "persistent-sqlite".flags.full-text-search = true;
        "persistent-sqlite".flags.uri-filenames = true;
        "http-types".revision = (((hackage."http-types")."0.12.3").revisions).default;
        "signal".revision = (((hackage."signal")."0.1.0.4").revisions).default;
        "ghc-boot-th".revision = (((hackage."ghc-boot-th")."8.10.2.20201118").revisions).default;
        "jwt".revision = (((hackage."jwt")."0.10.0").revisions).default;
        "th-lift-instances".revision = (((hackage."th-lift-instances")."0.1.17").revisions).default;
        "servant-server".revision = (((hackage."servant-server")."0.16.2").revisions).default;
        "random-shuffle".revision = (((hackage."random-shuffle")."0.0.4").revisions).default;
        "gauge".revision = (((hackage."gauge")."0.2.5").revisions).default;
        "gauge".flags.analysis = true;
        "fmlist".revision = (((hackage."fmlist")."0.9.4").revisions).default;
        "base-orphans".revision = (((hackage."base-orphans")."0.8.3").revisions).default;
        "smallcheck".revision = (((hackage."smallcheck")."1.2.0").revisions).default;
        "http-date".revision = (((hackage."http-date")."0.0.10").revisions).default;
        "servant".revision = (((hackage."servant")."0.16.2").revisions).default;
        "th-abstraction".revision = (((hackage."th-abstraction")."0.3.2.0").revisions).default;
        "memory".revision = (((hackage."memory")."0.15.0").revisions).default;
        "memory".flags.support_bytestring = true;
        "memory".flags.support_basement = true;
        "memory".flags.support_foundation = true;
        "memory".flags.support_deepseq = true;
        "fast-logger".revision = (((hackage."fast-logger")."3.0.2").revisions).default;
        "bsb-http-chunked".revision = (((hackage."bsb-http-chunked")."0.0.0.4").revisions).default;
        "concurrent-output".revision = (((hackage."concurrent-output")."1.10.12").revisions).default;
        "array".revision = (((hackage."array")."0.5.4.0").revisions).default;
        "ekg".revision = (((hackage."ekg")."0.4.0.15").revisions).default;
        "loch-th".revision = (((hackage."loch-th")."0.2.2").revisions).default;
        "path-pieces".revision = (((hackage."path-pieces")."0.2.1").revisions).default;
        "conduit-extra".revision = (((hackage."conduit-extra")."1.3.5").revisions).default;
        "erf".revision = (((hackage."erf")."2.0.0.0").revisions).default;
        "simple-sendfile".revision = (((hackage."simple-sendfile")."0.2.30").revisions).default;
        "simple-sendfile".flags.allow-bsd = true;
        "integer-gmp".revision = (((hackage."integer-gmp")."1.0.3.0").revisions).default;
        };
      compiler = {
        version = "8.10.2.20201118";
        nix-name = "ghc810220201118";
        packages = {
          "ghc" = "8.10.2.20201118";
          "exceptions" = "0.10.4";
          "binary" = "0.8.8.0";
          "ghc-boot" = "8.10.2.20201118";
          "ghc-prim" = "0.6.1";
          "stm" = "2.5.0.0";
          "unix" = "2.7.2.2";
          "ghc-heap" = "8.10.2.20201118";
          "mtl" = "2.2.2";
          "rts" = "1.0";
          "ghci" = "8.10.2.20201118";
          "deepseq" = "1.4.4.0";
          "parsec" = "3.1.14.0";
          "directory" = "1.3.6.0";
          "template-haskell" = "2.16.0.0";
          "containers" = "0.6.2.1";
          "bytestring" = "0.10.10.0";
          "text" = "1.2.3.2";
          "Cabal" = "3.2.0.0";
          "base" = "4.14.1.0";
          "time" = "1.9.3";
          "transformers" = "0.5.6.2";
          "hpc" = "0.6.1.0";
          "filepath" = "1.4.2.1";
          "process" = "1.6.9.0";
          "pretty" = "1.1.3.6";
          "ghc-boot-th" = "8.10.2.20201118";
          "array" = "0.5.4.0";
          "integer-gmp" = "1.0.3.0";
          };
        };
      };
  extras = hackage:
    {
      packages = {
        plutus-contract = ./.plan.nix/plutus-contract.nix;
        iohk-monitoring = ./.plan.nix/iohk-monitoring.nix;
        plutus-use-cases = ./.plan.nix/plutus-use-cases.nix;
        plutus-playground-server = ./.plan.nix/plutus-playground-server.nix;
        shelley-spec-ledger = ./.plan.nix/shelley-spec-ledger.nix;
        typed-protocols-examples = ./.plan.nix/typed-protocols-examples.nix;
        goblins = ./.plan.nix/goblins.nix;
        marlowe-actus = ./.plan.nix/marlowe-actus.nix;
        Win32-network = ./.plan.nix/Win32-network.nix;
        plutus-errors = ./.plan.nix/plutus-errors.nix;
        plutus-core = ./.plan.nix/plutus-core.nix;
        byron-spec-chain = ./.plan.nix/byron-spec-chain.nix;
        plutus-ledger = ./.plan.nix/plutus-ledger.nix;
        contra-tracer = ./.plan.nix/contra-tracer.nix;
        shelley-spec-non-integral = ./.plan.nix/shelley-spec-non-integral.nix;
        lobemo-backend-ekg = ./.plan.nix/lobemo-backend-ekg.nix;
        tracer-transformers = ./.plan.nix/tracer-transformers.nix;
        plutus-doc = ./.plan.nix/plutus-doc.nix;
        plutus-metatheory = ./.plan.nix/plutus-metatheory.nix;
        cardano-binary = ./.plan.nix/cardano-binary.nix;
        cardano-slotting = ./.plan.nix/cardano-slotting.nix;
        plutus-benchmark = ./.plan.nix/plutus-benchmark.nix;
        cardano-crypto-class = ./.plan.nix/cardano-crypto-class.nix;
        servant-purescript = ./.plan.nix/servant-purescript.nix;
        web-ghc = ./.plan.nix/web-ghc.nix;
        ouroboros-network-testing = ./.plan.nix/ouroboros-network-testing.nix;
        typed-protocols = ./.plan.nix/typed-protocols.nix;
        io-sim = ./.plan.nix/io-sim.nix;
        purescript-bridge = ./.plan.nix/purescript-bridge.nix;
        marlowe = ./.plan.nix/marlowe.nix;
        ouroboros-network = ./.plan.nix/ouroboros-network.nix;
        cardano-crypto = ./.plan.nix/cardano-crypto.nix;
        plutus-tx = ./.plan.nix/plutus-tx.nix;
        prettyprinter-configurable = ./.plan.nix/prettyprinter-configurable.nix;
        unlit = ./.plan.nix/unlit.nix;
        plutus-pab = ./.plan.nix/plutus-pab.nix;
        cardano-prelude-test = ./.plan.nix/cardano-prelude-test.nix;
        byron-spec-ledger = ./.plan.nix/byron-spec-ledger.nix;
        marlowe-playground-server = ./.plan.nix/marlowe-playground-server.nix;
        network-mux = ./.plan.nix/network-mux.nix;
        small-steps = ./.plan.nix/small-steps.nix;
        cardano-prelude = ./.plan.nix/cardano-prelude.nix;
        ouroboros-network-framework = ./.plan.nix/ouroboros-network-framework.nix;
        plutus-tx-plugin = ./.plan.nix/plutus-tx-plugin.nix;
        marlowe-symbolic = ./.plan.nix/marlowe-symbolic.nix;
        plutus-ledger-api = ./.plan.nix/plutus-ledger-api.nix;
        marlowe-dashboard-server = ./.plan.nix/marlowe-dashboard-server.nix;
        playground-common = ./.plan.nix/playground-common.nix;
        io-sim-classes = ./.plan.nix/io-sim-classes.nix;
        shelley-spec-ledger-test = ./.plan.nix/shelley-spec-ledger-test.nix;
        };
      };
  modules = [
    ({ lib, ... }:
      {
        packages = {
          "plutus-contract" = { flags = {}; };
          "iohk-monitoring" = {
            flags = {
              "disable-observables" = lib.mkOverride 900 false;
              "performance-test-queue" = lib.mkOverride 900 false;
              };
            };
          "plutus-use-cases" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "plutus-playground-server" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "shelley-spec-ledger" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "typed-protocols-examples" = { flags = {}; };
          "goblins" = { flags = { "development" = lib.mkOverride 900 true; }; };
          "marlowe-actus" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "Win32-network" = { flags = { "demo" = lib.mkOverride 900 false; }; };
          "plutus-errors" = { flags = {}; };
          "plutus-core" = { flags = {}; };
          "byron-spec-chain" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "plutus-ledger" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "contra-tracer" = { flags = {}; };
          "shelley-spec-non-integral" = {
            flags = { "development" = lib.mkOverride 900 false; };
            };
          "lobemo-backend-ekg" = { flags = {}; };
          "tracer-transformers" = { flags = {}; };
          "plutus-doc" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "plutus-metatheory" = { flags = {}; };
          "cardano-binary" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "cardano-slotting" = {
            flags = { "development" = lib.mkOverride 900 false; };
            };
          "plutus-benchmark" = { flags = {}; };
          "cardano-crypto-class" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "servant-purescript" = { flags = {}; };
          "web-ghc" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "ouroboros-network-testing" = { flags = {}; };
          "typed-protocols" = { flags = {}; };
          "io-sim" = { flags = { "asserts" = lib.mkOverride 900 false; }; };
          "purescript-bridge" = { flags = {}; };
          "marlowe" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "ouroboros-network" = {
            flags = {
              "cddl" = lib.mkOverride 900 true;
              "asserts" = lib.mkOverride 900 false;
              "ipv6" = lib.mkOverride 900 false;
              };
            };
          "cardano-crypto" = {
            flags = {
              "golden-tests-exe" = lib.mkOverride 900 false;
              "golden-tests" = lib.mkOverride 900 false;
              };
            };
          "plutus-tx" = { flags = {}; };
          "prettyprinter-configurable" = { flags = {}; };
          "unlit" = { flags = {}; };
          "plutus-pab" = {
            flags = { "defer-plugin-errors" = lib.mkOverride 900 false; };
            };
          "cardano-prelude-test" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "byron-spec-ledger" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "marlowe-playground-server" = { flags = {}; };
          "network-mux" = {
            flags = {
              "asserts" = lib.mkOverride 900 false;
              "ipv6" = lib.mkOverride 900 false;
              };
            };
          "small-steps" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "cardano-prelude" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          "ouroboros-network-framework" = { flags = {}; };
          "plutus-tx-plugin" = { flags = {}; };
          "marlowe-symbolic" = { flags = {}; };
          "plutus-ledger-api" = { flags = {}; };
          "marlowe-dashboard-server" = { flags = {}; };
          "playground-common" = { flags = {}; };
          "io-sim-classes" = {
            flags = {
              "asserts" = lib.mkOverride 900 false;
              "checktvarinvariant" = lib.mkOverride 900 false;
              };
            };
          "shelley-spec-ledger-test" = {
            flags = { "development" = lib.mkOverride 900 true; };
            };
          };
        })
    ];
  }