(program
   1.1.0
   ((\cse ->
       cse cse)
      (\s ds -> case ds [True, (\x xs -> case x [False, (s s xs)])])
      (constr 1
         [ False
         , (constr 1
              [ True
              , (constr 1
                   [ True
                   , (constr 1
                        [ True
                        , (constr 1
                             [ True
                             , (constr 1
                                  [ True
                                  , (constr 1
                                       [ True
                                       , (constr 1
                                            [ True
                                            , (constr 1
                                                 [ True
                                                 , (constr 1
                                                      [ True
                                                      , (constr 0
                                                           [  ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])))