(program
   1.1.0
   ((\cse ->
       cse cse)
      (\s ds ->
         case ds [True, (\x xs -> case (equalsInteger 1 x) [(s s xs), False])])
      (constr 1
         [ 1
         , (constr 1
              [ 2
              , (constr 1
                   [ 3
                   , (constr 1
                        [ 4
                        , (constr 1
                             [ 5
                             , (constr 1
                                  [ 6
                                  , (constr 1
                                       [ 7
                                       , (constr 1
                                            [ 8
                                            , (constr 1
                                                 [ 9
                                                 , (constr 1
                                                      [ 10
                                                      , (constr 0
                                                           [  ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])))