(program
   1.1.0
   ((\cse ->
       cse cse)
      (\s ds -> case ds [False, (\x xs -> case x [(s s xs), True])])
      (constr 1
         [ False
         , (constr 1
              [ False
              , (constr 1
                   [ False
                   , (constr 1
                        [ False
                        , (constr 1
                             [ False
                             , (constr 1
                                  [ False
                                  , (constr 1
                                       [ False
                                       , (constr 1
                                            [ False
                                            , (constr 1
                                                 [ False
                                                 , (constr 1
                                                      [ False
                                                      , (constr 0
                                                           [  ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ])))