(program
   1.2.0
   ((\s ->
       s
         s
         (constr 1
            [ False
            , (constr 1
                 [ False
                 , (constr 1
                      [ False
                      , (constr 1
                           [ False
                           , (constr 1
                                [ False
                                , (constr 1
                                     [ False
                                     , (constr 1
                                          [ False
                                          , (constr 1
                                               [ False
                                               , (constr 1
                                                    [ False
                                                    , (constr 1
                                                         [ False
                                                         , (constr 0
                                                              [  ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]))
      (\s ds -> case ds [False, (\x xs -> case x [(s s xs), True])])))