(program
   1.1.0
   ((\`$dAdditiveMonoid` ->
       (\f ->
          (\z ->
             (\go eta -> go eta)
               ((\s -> s s) (\s ds -> case ds [z, (\x xs -> f x (s s xs))])))
            (case `$dAdditiveMonoid` [(\v v -> v)]))
         (case `$dAdditiveMonoid` [(\v v -> v)])
         (constr 1
            [ 1
            , (constr 1
                 [ 2
                 , (constr 1
                      [ 3
                      , (constr 1
                           [ 4
                           , (constr 1
                                [ 5
                                , (constr 1
                                     [ 6
                                     , (constr 1
                                          [ 7
                                          , (constr 1
                                               [ 8
                                               , (constr 1
                                                    [ 9
                                                    , (constr 1
                                                         [ 10
                                                         , (constr 0
                                                              [  ]) ]) ]) ]) ]) ]) ]) ]) ]) ]) ]))
      (constr 0 [(\x y -> addInteger x y), 0])))