#!/bin/bash
# shellcheck disable=all

plc=plc
TIME=/usr/bin/time

size=4

for machine in CK CEK L
do
    ofile=${machine}-times-fib
    echo "n usr sys mem" > $ofile
    for n in $(seq 1 1 31);
    do 
	echo ${machine} fib $n
	echo -n "$n " >> $ofile
	gpp -DSIZE=$size -DARG=$n progs/Fib.plc > test.plc
	$TIME -o $ofile -a -f "%U %S %M" $plc evaluate -f test.plc -m$machine >/dev/null 2>&1
    done  
done

machine=Y
ofile=Y-times-fib
echo "n usr sys mem" > $ofile
for n in $(seq 1 1 31)
do 
    echo ${machine} fib $n
    echo -n "$n " >> $ofile
    gpp -DSIZE=$size -DARG=$n progs/FibY.plc > test.plc
    $TIME -o $ofile -a -f "%U %S %M" $plc evaluate -f test.plc -mL >/dev/null 2>&1
done  

rm test.plc

