#!/bin/bash
# shellcheck disable=all

plc=$plc
TIME=/usr/bin/time

size=4

for machine in CK CEK L
do
    ofile=${machine}-times-loop
    echo "n usr sys mem" > $ofile
    for n in $(seq 0 20000 1000000);
    do
	echo ${machine} loop $n
	echo -n "$n " >> $ofile
	gpp -DSIZE=$size -DARG=$n progs/Loop.plc > test.plc
	$TIME -o $ofile -a -f "%U %S %M" $plc evaluate -f test.plc -m$machine >/dev/null 2>&1
    done  
done

machine=Y
ofile=${machine}-times-loop
echo "n usr sys mem" > $ofile
for n in $(seq 0 20000 1000000)
do 
    echo ${machine} loop $n
    echo -n "$n " >> $ofile
    gpp -DSIZE=$size -DARG=$n progs/LoopY.plc > test.plc
    $TIME -o $ofile -a -f "%U %S %M" $plc evaluate -f test.plc -mL >/dev/null 2>&1
done  

rm test.plc

