The contract must somehow keep track of bids, because we need to make sure that
only bidders who are _not_ currently the highest bidder can reclaim their bids,
that the highest bidder can claim the token in the end and so on.

This means the contract needs _state_, which is more complicated than just the
value being locked into it. In the last chapter, we could work with trivial `()`
data scripts, because all the state was encoded in the locked value. In this
chapter, we really need non-trivial state in our data scripts. This state will
change through the lifetime of the auction, depending on which actions (bid,
reclaim etc.) are performed.

Abstractly, a _state machine_ is given by a set of possible _states_, an
_initial state_ and - for each state - as set of possible _inputs_ (or
_actions_). Given a state and an input for that state, the _transition function_
determines the next state.

Luckily, there is support for state machine contracts in
module `Language.PlutusTx.StateMachine`:

First of all, a _state machine_ is defined as

[source, haskell]
----
data StateMachine s i = StateMachine 
    { smTransition :: s -> i -> Maybe s
    , smCheck      :: s -> i -> PendingTx -> Bool
    , smFinal      :: s -> Bool
    }
----

Here `s` is the state type, and `i` is the type of inputs.
Function `smTransition` takes the current state and the input and returns either
`Nothing`, if the input is not valid for that state, or `Just` the new state.

The function `smCheck` additionally takes a pending transaction and checks whether
the given input is valid for the given state in the context of that transaction.

The function `smFinal` checks whether a state machine state is _final_, that is, whether
the machine halts when it enters this state.

How are such state machines used? - To create a script acting like a state machine,
the script output will have a data script of type `s`. To consume such an
output, the redeemer script will be of type
`(i, Sealed (HashedDataScript s))`, where the first component is the action
and the second component wraps the new state.
The validator script will verify that the
pending transaction has exactly one output for the same script,
that the data script of that output is the result of applying `smTransition`
to the input data script and the action contained in the redeemer
and finally that the check passes for the given state, action
and pending transaction.

The module provides two more helpers to make working with such state machines
easier:


[source, haskell]
----
-- | A state machine redeemer takes the data
-- script for the new state, and pairs it with the input.
type StateMachineRedeemer s i =
    Sealed (HashedDataScript s) -> (i, Sealed (HashedDataScript s))

-- | A state machine validator takes the old state (the data script),
-- and a pair of the input and the new state (the redeemer output).
type StateMachineValidator s i =
    s -> (i, Sealed (HashedDataScript s)) -> PendingTx -> Bool

mkRedeemer :: forall s i . i -> StateMachineRedeemer s i

-- | Turn a transition function 's -> i -> s' into a validator script.
mkValidator :: Eq s => StateMachine s i -> StateMachineValidator s i
----

We will use this mechanism for our auction script, so we first have to decide
on types for `s` and `i`.
