---
name: "Cost model benchmark"

on:
  workflow_dispatch:

jobs:
  bench:
    name: Cost model benchmark

    runs-on: [self-hosted, plutus-benchmark]

    timeout-minutes: 14400

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run benchmarks
        run: nix --accept-flake-config run .#hydraJobs.x86_64-linux.ghc92.components.exes.plutus-core.cost-model-budgeting-bench -- --csv results.csv

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.csv
          if-no-files-found: error
