name: HLint
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup HLint
        uses: haskell/actions/hlint-setup@v2
        with:
          version: '3.4'

      - name: Quick Install Nix
        uses: nixbuild/nix-quick-install-action@v21 
        with: 
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true 

      - name: Build
        run: nix build .#hlint 

      - name: Run 
        uses: haskell/actions/hlint-run@v1
        with:
          hlint-bin: "./result/bin/hlint --hint=./.github/.hlint.yaml"
          fail-on: status
          path: .

