# This workflow runs the plutus-core-test and plutus-ir-test test suite.
#
# This workflow runs daily at midnight, and it can also be triggered manually.


name: "🌘 Nightly Testsuite"

on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:
    inputs:
      hedgehog-tests:
        description: Number of tests to run (--hedgehog-tests XXXXX)
        required: false
        default: "100000"

      quickcheck-tests:
        description: Number of QuickCheck tests to run per property
        required: false
        default: "100000"
      quickcheck-max-size:
        description: Max QuickCheck size parameter
        required: false
        default: "500"

env:
  HEDGEHOG_TESTS: ${{ github.event.inputs.hedgehog-tests || 100000 }}
  QUICKCHECK_TESTS: ${{ github.event.inputs.quickcheck-tests || 100000 }}
  QUICKCHECK_MAX_SIZE: ${{ github.event.inputs.quickcheck-max-size || 500 }}

jobs:
  run:
    name: Run
    runs-on: [self-hosted, plutus-runner]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Plutus Core Test
        run: |
          pushd plutus-core
          nix run --no-warn-dirty --accept-flake-config .#plutus-core-test -- --hedgehog-tests $HEDGEHOG_TESTS --quickcheck-tests $QUICKCHECK_TESTS --quickcheck-max-size $QUICKCHECK_MAX_SIZE --no-create
          popd

      - name: Run Plutus IR Test
        run: |
          pushd plutus-core
          nix run --no-warn-dirty --accept-flake-config .#plutus-ir-test -- --hedgehog-tests $HEDGEHOG_TESTS --quickcheck-tests $QUICKCHECK_TESTS --quickcheck-max-size $QUICKCHECK_MAX_SIZE --no-create
          popd
