name: Plutus Tx Template

on:
  pull_request:

jobs:
  plutus-tx-template:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout plutus-tx-template
        uses: actions/checkout@master
        with: 
          repository: IntersectMBO/plutus-tx-template
          path: plutus-tx-template 

      # plutus repo will be nested inside the plutus-tx-template repo
      - name: Checkout plutus
        uses: actions/checkout@master
  
      - name: Write cabal.project.local
        uses: DamianReeves/write-file-action@master
        with:
          path: cabal.project.local
          write-mode: overwrite
          contents: |
            packages: 
              plutus/plutus-tx
              plutus/plutus-tx-plugin
              plutus/plutus-core
              plutus/plutus-ledger-api
              plutus/prettyprinter-configurable
            
            allow-newer:
                plutus-tx
              , plutus-tx-plugin
              , plutus-core
              , plutus-ledger-api 
              , prettyprinter-configurable
          
      - name: Build Project With Docker
        run: |
          pwd
          ls -la . 
          ls -la ..

          docker run \
            -v ./.:/workspaces/plutus-tx-template \
            -w /workspaces/plutus-tx-template \
            -i ghcr.io/input-output-hk/devx-devcontainer:x86_64-linux.ghc96-iog \
            bash -ic "cabal update && cabal run plutus-tx-template && test -e validator.uplc"
