# This workflow handles the release process.

name: "🛸 Plutus Release"

on:  
  workflow_dispatch:
    inputs:
      version:
        description: |
          The new version number, e.g. 1.40.0.0
        required: true
        type: string

  pull_request_target:
    types:
      - closed
    branches:
      - 'release/**'

jobs:
  step-1:
    name: Step 1
    runs-on: [self-hosted, plutus-ci]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build Site
        run: | 
          # nix develop --no-warn-dirty --accept-flake-config --command <<< 
          git checkout master 
          git pull --rebase origin master
          git checkout -b release/${{ inputs.version }}
          ./scripts/check-broken-links.sh ${{ inputs.version }}
          git add . 
          git commit -m "Release ${{ inputs.version }}"
          git push 
          gh pr create --title "Release ${{ inputs.version }}" --label "No Changelog Required"

  step-2:
    name: Step 2
    runs-on: [self-hosted, plutus-ci]
    if: github.event_name == 'pull_request_target'
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Create Draft Release
        run: |
          # nix develop --no-warn-dirty --accept-flake-config --command <<< 

          bash ./scripts/prepare-bin.sh

          tag="${${{ github.ref_name }}#release/}"

          gh release create $tag --title "$tag" --generate-notes --latest
          gh release upload $tag pir-x86_64-linux-ghc96 uplc-x86_64-linux-ghc96 --clobber


