name: Pre Commit Check
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  pre-commit-check:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        
      - name: Quick Install Nix
        uses: nixbuild/nix-quick-install-action@v25 
        with: 
          # 2.14.1 seems to have issues, see https://github.com/nixbuild/nix-quick-install-action/issues/29
          nix_version: '2.13.3'
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true 

      - name: Run
        run: nix build .#pre-commit-check 
